### ISSUE TITLE
convertStringEncoding() incorrectly double encodes UTF-8/US-ASCII

### ISSUE THREAD

**Issue by Clorith** [barbushin/php-imap#100]
I'm hitting up an Office365 e-mail account using imap and fetching messages, the body of the message contains Norwegian characters (`æ`, `ø` and `å`), these are all present until you reach [Mailbox.php#L531](https://github.com/barbushin/php-imap/blob/master/src/PhpImap/Mailbox.php#L531) which invokes `convertStringEncoding()`

This seems to be caused by `$params['charset']` being populated with UTF-8, but the Office365 connection explicitly requires US-ASCII (this is causing a double encoding fault as US-ASCII is an UTF-8 subset)

Seems the use of `//IGNORE` in [Mailbox.php#L596](https://github.com/barbushin/php-imap/blob/master/src/PhpImap/Mailbox.php#L596) is the reason for characters going missing, since the double encoded UTF-8 string is then invalid and discarded, of course bypassing `iconv` and going straight to `mbstring` isn't much help either as it is still converted to invalid characters.

**Comment by barbushin** [comment]
Fixed
