### ISSUE TITLE
Problem with serverEncoding

### ISSUE THREAD

**Issue by KuenzelIT** [barbushin/php-imap#101]
Hey,

I get the following error, when using the server encoding:

```
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Unknown: [BADCHARSET (US-ASCII)] The specified charset is not supported. (errflg=2)' in Unknown:0
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Unknown: [BADCH...', 'Unknown', 0, Array)
#1 {main}
  thrown in Unknown on line 0
```

If I remove the server encoding from imap_search, everything works fine. With it I dont get any results and this error. Does anyone have an idea what the problem is (I'm trying to read from an exchange mailbox)?

**Comment by escobar022** [comment]
This could possibly be a exchange level issue, possibly the setting? 
I've been using this on exchange for a while and haven't experienced this.

**Comment by KuenzelIT** [comment]
Hey, thank you for the answer,.
Unfortunately I dont have any experience with exchange and I'm not responsible for the server. I'm going to ask about it. But still, I don't have any problems when using e.g. Thunderbird. Do you know any specific setting on exchange, which could lead to this issue?

**Comment by escobar022** [comment]
No idea sorry, that is very sysadmin/network level. As far as I know its magic.

**Comment by rustem-art** [comment]
Omg! I have too this problem with Exchange.
PHP Fatal error:  Uncaught ErrorException: Unknown: [BADCHARSET (US-ASCII)]
Can help me?

**Comment by rsharpy** [comment]
Same problem for me too when connecting to Outlook.com IMAP. Can you help?

**Comment by littleylv** [comment]
Got the same error with @rsharpy. Anybody solved it please?

**Comment by rustem-art** [comment]
@littleylv 
i can solve this problem only by add specific character param in
```php
$mailbox = new ImapMailbox('{' . $serverAddr . ':' . $serverPort . '' . $serverSecurity . '}' . 
$serverDirectory . '', $serverLogin, $serverPass, storage_path('/tmp/'), $encoding);
            $mails = array();
....
```
and in your app you can select, if MS Outlook mail server then $encoding = 'US-ASCII';
in other UTF-8...

PS sorry for my english.

**Comment by littleylv** [comment]
@rustem-art 

I tried that before. But then I got the wrong encoding subject and content.
It seems that encoding in ``ImapMailbox`` meeds to be ``UTF-8`` too.

At last I do the following changes temporarily:

Before:
``
public function searchMailbox($criteria = 'ALL') {
    $mailsIds = imap_search($this->getImapStream(), $criteria, SE_UID, $this->serverEncoding);
    return $mailsIds ? $mailsIds : array();
}
``
After:
``
public function searchMailbox($criteria = 'ALL', $serverEncoding = null) {
    $mailsIds = imap_search($this->getImapStream(), $criteria, SE_UID, $serverEncoding ?: $this->serverEncoding);
    return $mailsIds ? $mailsIds : array();
}
``

And in my app:
``
$mailsIds = $mailbox->searchMailbox('UNSEEN', stripos($account->username, 'outlook.com') !== false ? 'US-ASCII' : 'UTF-8');
``

It works for me.

And sorry for my english too :)

**Comment by NormanEdance** [comment]
Hello everybody! My solution _searchMailbox()_:
**Before: **
`return $this->imap('search', [ $criteria, SE_UID, $this->serverEncoding]) ?: [];`
**After:**
`return $this->imap('search', [ $this->getImapStream(), $criteria, SE_UID, $this->serverEncoding]) ?: [];`

**Comment by NormanEdance** [comment]
@littleylv , why `stripos($account->username, 'outlook.com') !== false ? 'US-ASCII' : 'UTF-8')`, and not just 'UTF-8' ?

**Comment by commanddotcom** [comment]
> @littleylv , why stripos($account->username, 'outlook.com') !== false ? 'US-ASCII' : 'UTF-8'), and not just 'UTF-8' ? Seems good for me.

It is not about outlook.com only

**Comment by NormanEdance** [comment]
**Before:**

        $mailsIds = $mailbox->searchMailbox('NEW');

**After:** 

        try {
            retry:
            $mailsIds = $mailbox->searchMailbox('NEW');
        } catch (Exception $e) {
            // echo $e;
            if (strpos($e, " [BADCHARSET (US-ASCII)]")) {
                $newEncoding = 'US-ASCII';
                $oldEncoding =  $mailbox->getServerEncoding();
                $mailbox->setServerEncoding('US-ASCII');
                echo "Encoding changed dynamically from {$oldEncoding} to {$newEncoding}.\n";
                goto retry;
            } else {
                throw $e;
            }
        }

**Summary:**
Works perfectly without diggin' into source code. If you know how to improve goto part, let me know.

**Notice:**
You might want to limit attempts, in order to prevent goto looping.

**Comment by NormanEdance** [comment]
### PhpImap\Exception [ 0 ]: Mime string encoding conversion failed ~ APPPATH/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php [753]

**Before:**

	protected function convertStringEncoding($string, $fromEncoding, $toEncoding) {
		if(!$string || $fromEncoding == $toEncoding) {
			return $string;
		}
		...
	}

**After:**

	protected function convertStringEncoding($string, $fromEncoding, $toEncoding) {
		if(!$string || $fromEncoding == $toEncoding || ($fromEncoding == "utf-8" && $toEncoding == "US-ASCII")) {
			return $string;
		}
		...
	}

**Explanation:**

> **ASCII is a subset of UTF-8**, so all ASCII files are already UTF-8 encoded. The bytes in the ASCII file and the bytes that would result from "encoding it to UTF-8" would be exactly the same bytes. There's no difference between them, so there's no need to do anything.
[ (from StackOverflow)](https://stackoverflow.com/a/11303410/5193609)

To reproduce this problem you can use cyrrilic email's subject. It will try to `convertStringEncoding($subject, "utf-8", "US-ASCII")` and throw exception by ...

	if(!$convertedString) {
		throw new Exception('Mime string encoding conversion failed');
	}

... However function's docblock says: _@return string Converted string if conversion was successful, or the original string if not_

**Comment by sven-verkstedt** [comment]
Can also happen if mbstring and/or iconv is not available.. The exception message should mention this possibity ;)

**Comment by Sebi94nbg** [comment]
@KuenzelIT @rustem-art @commanddotcom @NormanEdance @sven-verkstedt 
Can anyone test, if this issue still exists with `php-imap` version 3.0.8? Encoding has been improved, so this might has fixed this kind of issue as well.

**Comment by Sebi94nbg** [comment]
This is an issue on Exchange servers and not related to this library. However, we're still checking, if we can implement a workaround to get it somehow working. See #306.

**Comment by b0boc** [comment]
I found a simple solution, it works for me...

in Mailbox.php on line 544

I changed the line 
public function searchMailbox($criteria = 'ALL', $disableServerEncoding = false)

with

public function searchMailbox($criteria, $disableServerEncoding)

Now I'm using the searchMailbox() like this: 

searchMailbox("ALL", false) - returns all emails

searchMailbox('SINCE "'.date("j F Y", strtotime("-2 days")).'"', true); - Returns all emails received within the last 2 days. 

I works fine for me.

**Comment by Sebi94nbg** [comment]
You have only removed the default values for the arguments. In your both examples, you would always overwrite them, so this shouldn't change anything.

**Comment by b0boc** [comment]
Thank you for your reply. 

searchMailbox() function accepts two arguments, if we pass only one argument sometimes it works, but not all the time. 

1. searchMailbox("ALL") - it works - shows all the emails

2. searchMailbox("SINCE .....") - not working - without passing the second argument will give that error, but if we make it  searchMailbox("SINCE .....", true) it works fine.

In one of the example files, there is only one argument passed and the other is assumed as false by default, it works with Gmail but cracks on Outlook [PHP Fatal error: Uncaught ErrorException: Unknown: [BADCHARSET (US-ASCII)]

It's true I changed nothing by removing the default values, but now I'm forced to input the second argument, which makes the difference for me.
