### ISSUE TITLE
Add raw header to getMail() *feature request*

### ISSUE THREAD

**Issue by shdinx** [barbushin/php-imap#102]
Hi,

Right now you only add the mailing information based on the imap_rfc822_parse_headers() method.
It would be good to have also the raw header within the return object.

You can change line 48:
$head = imap_rfc822_parse_headers(imap_fetchheader($this->getImapStream(), $mailId, FT_UID));

to:
$rawHeader = imap_fetchheader($this->getImapStream(), $mailId, FT_UID);
$head = imap_rfc822_parse_headers($rawHeader);

and add it like:
$mail->header = $rawHeader;

Also, it can be useful to have the IP addresses from the header:
$mail->senderIps = $this->getIpAddress($rawHeader);

```
public function getIpAddress ($rawHeader)
{
    preg_match_all("/(?:\\b[Received|X\\-Originating\\-IP].*?)(?<ip>(?:\\d{1,3}\\.){3}\\d{1,3})/", str_replace(array( "\r", "\n" ), ' ', $rawHeader), $ips);

    if (isset($ips['ip'])) {
        return array_unique( array_filter($ips['ip'], function($v) { return $v != "127.0.0.1"; }) );
    } else {
        return array();
    }
}
```

The regex needs improvement as there is no real validation of an IP address and it can and will match something like this 015.11.06.02 as well.

This is purely a feature request :D

**Comment by barbushin** [comment]
Done
