### ISSUE TITLE
imap_rfc822_parse_headers Error

### ISSUE THREAD

**Issue by Makcym** [barbushin/php-imap#104]
При большом количестве адресатов, скрипт крашится на imap_rfc822_parse_headers.
Как вариант удалять письмо.

 try
		{
			$head = imap_rfc822_parse_headers(imap_fetchheader($this->getImapStream(), $mailId, FT_UID));
		}
		catch(Exception $ex)
		{
			$this->deleteMail($mailId);
		}

**Comment by patie** [comment]
@Makcym english please
