### ISSUE TITLE
[Feature Request] Pagination for mail list

### ISSUE THREAD

**Issue by let-aurn** [barbushin/php-imap#107]
It would be great to be able to paginate searchMailBox() result.

**Comment by wouter-corpoflow** [comment]
You can kind of do this already by using:

```php
$overview = $mailbox->imap('fetch_overview', $from . ':' . $to);
```

`$from = 1;` and `$to = 5;` will give you the oldest 5 e-mails in the IMAP box.

You'll have to write your own pagination logic ofcourse.

**Comment by Sebi94nbg** [comment]
Closing this since a possible solution was provided and can be implemented using an own logic.

It's not planned to add such a logic to the library as it was only intended to simplify the PHP IMAP functions.
