### ISSUE TITLE
getMail() method returns an object even for nonexistent mail ID

### ISSUE THREAD

**Issue by rustikov** [barbushin/php-imap#115]
I would change that, does not seem like a right way. Got me off track for a bit, when I mistyped the variable name for id.

**Comment by Sebi94nbg** [comment]
I've changed this behaviour with [commit c53e9e5](https://github.com/barbushin/php-imap/commit/c53e9e595c231aee64ea0db884e18aa903e3f2b3). When you provide an invalid mail id, which for example does not exist, it will now throw an exception.

This change will be included in the next release.
