### ISSUE TITLE
Class Mailbox not found after upgrading to 2.0.5

### ISSUE THREAD

**Issue by carlosafonso** [barbushin/php-imap#118]
Hi,

I've been using php-imap 2.0.4 without trouble, but after upgrading to 2.0.5 I get the following error:

```php
PHP Fatal error:  Class 'PhpImap\Mailbox' not found
```

At a first glance I cannot see why this is happening, since the `Mailbox` class is still there within the `PhpImap` namespace.

Am I missing something?

Thank you.

**Comment by barbushin** [comment]
Hey,

There was a wrong psr-4 autoload configuration for composer. Fixed in `2.0.6`. Try `composer update`.

Thanks for report!

**Comment by carlosafonso** [comment]
Thank you, did not catch that one.
