### ISSUE TITLE
check more then one email address

### ISSUE THREAD

**Issue by dizews** [barbushin/php-imap#121]
Hello, thanks for your work.

I need to check more then one email address. I stumbled over the static variable $imapStream.
Do you have any plans to make it non static?

**Comment by barbushin** [comment]
Hey

This static variable is inside the method, so it's not going to be shared between different instances of `PhpImap\Mailbox` class.

You should try :)

**Comment by dizews** [comment]
@barbushin I was try it, but for static variable in a method of class this variable the same for the hole instances. [read more](http://php.net/manual/en/language.variables.scope.php#59676)

**Comment by barbushin** [comment]
OMG, you're right! I just tested it with
```
class Foo {
	public function __construct($bar=null) {
		static $foo;
		if($bar) {
			$foo = $bar;
		}
		var_dump($foo);
	}
}

new Foo(123);
new Foo();
```

and in PHP 5.6 result was
```
int 123
int 123
```

It's very strange because I'm 100% sure that in PHP 5.3 result was different. 
Fix is coming soon...

**Comment by barbushin** [comment]
Done. Could you please test it and confirm that it works properly? After that I'll publish new release.

Thank you.
