### ISSUE TITLE
Disable attachment storing

### ISSUE THREAD

**Issue by alzambo** [barbushin/php-imap#122]
Hi,
I need to get just the list of emails without downloading the attachments; is this possible? 
Thanks,

Alex

**Comment by nicanaca0** [comment]
I'd also like this. 

By default it seems to just dump them into the directory of the working file/class which on mysymfony project means the attachments are just dumped into my bundle structure :(.

Ideally if we can disable or just specifiy a path for email attachments specifically that would be great.

**Comment by mcoeur** [comment]
@nicanaca0 > you can already specify the path when creating an instance : 
````php
new PhpImap\Mailbox($server, $email, $password, $path);
````

See the constructor : https://github.com/barbushin/php-imap/blob/master/src/PhpImap/Mailbox.php#L22

Anyways, +1 for this enhancement

**Comment by barbushin** [comment]
Hi guys. See `Mailbox::getMailsInfo()`.

**Comment by nickl-** [comment]
duplicate #150
