### ISSUE TITLE
Not sure how to move/delete emails using this library.

### ISSUE THREAD

**Issue by nicanaca0** [barbushin/php-imap#123]
According to Google I should move the email into the Trash/Bin folder before deleting it to make sure it's delete properly on Google side. 

The issue is I cannot seem to move/delete the email using this library.

moveMail accepts a id and a mailbox but I've tried giving it a Mailbox() object tied to the '{imap.gmail.com:993/imap/ssl/novalidate-cert}[Google Mail]/Bin' path but I've also tried passing in the string '{imap.gmail.com:993/imap/ssl/novalidate-cert}[Google Mail]/Bin' to the moveMail method.

Trying to pass in a Mailbox object results in this: imap_mail_move() expects parameter 3 to be string, object given

But passing in just a string doesn't error but it doesn't move/delete the emails...

Are you aware of this kind of issue? Can you clarify what's needed in the class/method? and maybe add type hinting to make these errors more obvious?

**Comment by nicanaca0** [comment]
The bit I was missing is this:

Note: The mailbox needs to be the "label" name, not the full server string

$mailbox->moveMail($mid, '[Google Mail]/Trash');
$mailbox->deleteMail($mid);

Seems to work for me (completely removed the email from Inbox and doesn't appear in All or Trash or in the search results)

**Comment by melino** [comment]
For the records: some IMAP servers using dots as separator like
`$mailbox->moveMail($mid, 'INBOX.Marketing');`
