### ISSUE TITLE
pop connection

### ISSUE THREAD

**Issue by Zonork** [barbushin/php-imap#124]
Hi how i can connect with gmail acount with pop3? i cant find one example

**Comment by barbushin** [comment]
You can connect only with IMAP, so you need to enable IMAP in Gmail settings, and you example code from README.md.

**Comment by Zonork** [comment]
but in the readme says:

**Comment by barbushin** [comment]
Right, but some features will not work. Anyway, you can try to connect to POP3, see examples at http://php.net/imap_open
