### ISSUE TITLE
Problem with transfer encoding

### ISSUE THREAD

**Issue by portey** [barbushin/php-imap#127]
Hey,

I'm importing different IMAP accounts and with some account when I getting letter content, I have base64 encoded content, it's because in Mailbox class on line 468 there are this code:

`elseif($partStructure->encoding == 2) {
            $data = imap_binary($data);
        }` 

as I understand, it's because transfer encoding is binary and $data must be binary, but when I debug this situation, in $data variable no binary data, there are normal utf8 text, so why can it be? Is it wrong IMAP server response? 

What advices to do in this case?

**Comment by barbushin** [comment]
Yes, looks like IMAP server internal error.
