### ISSUE TITLE
Catch errors

### ISSUE THREAD

**Issue by Sandbird** [barbushin/php-imap#140]
I see that the class Exception is totally empty.
Can someone please paste some code here, that will catch all error messages (like wrong user/pass) and return a nice readable value.
I am trying to add this class in an ajax request, and the Fatal errors terminate the script.
Thanks

**Comment by Sebi94nbg** [comment]
Exception / Error handling has been improved. See above referenced commits.

In PHP you can use [`try-catch`](https://www.php.net/manual/en/language.exceptions.php):
```php
try {
	// Search in mailbox folder for specific emails
	$mails_ids = $mailbox->searchMailbox('ALL');
} catch(PhpImap\Exceptions\ConnectionException $ex) {
	echo "IMAP connection failed: " . $ex;
	die();
}
```
Will be included in the next release.
