### ISSUE TITLE
ignoring attachments when downloading body

### ISSUE THREAD

**Issue by melino** [barbushin/php-imap#150]
Can I download mails without attachments and embedded graphics?

I need to fetch some content/words from the body, but big attachments are slowing down the complete process.

**Comment by nettunodev** [comment]
I'm joining to this request... if I don't declare the directory into which attachments are saved, are they downloaded anyway and then not saved? Is there a way to get just the email body, speeding up the download?

**Comment by dtruel** [comment]
Ok here's how I did it!

```
//first get the email structure, which contains an array of parts
$emailStructure = imap_fetchstructure($mailbox->getImapStream(),$email->uid,FT_UID);
//loop through parts.  If part is 'plain' or 'html' download it!  ignore the rest.
foreach($emailStructure->parts as $partNum => $part){
    if(strtolower($part->subtype) == "plain"){
        $plainText = imap_fetchbody($mailbox->getImapStream(),$email->uid, $partNum + 1, FT_UID | FT_PEEK);
    } else if(strtolower($part->subtype) == "html"){
        $htmlText = imap_fetchbody($mailbox->getImapStream(),$email->uid, $partNum + 1, FT_UID | FT_PEEK);
    }
}
print_r($plainText);
echo "\n";
print_r($htmlText);

**Comment by nettunodev** [comment]
I tried something like that, but it came out that imap_fetchstructure proceeds downloading the whole email, attachments included. Therefore it doesn't help reducing the amount of data that are transferred.

**Comment by Sebi94nbg** [comment]
Attachments can be ignore with the next available release:
```php
$mailbox->setAttachmentsIgnore(true);
```

Attachments will be processed by default, so you don't need to change your existing and already working code.
