### ISSUE TITLE
Line 527 Mailbox.php | Looks to the wrong id?

### ISSUE THREAD

**Issue by rtbweb** [barbushin/php-imap#157]
On line 527 from mailbox.php the id looks like wrong. when you send a mail from laravel 5 with your outlook account there id set a content-id. Mailbox.php look to content-id to see if there is a attachment.

// attachments
        $attachmentId = $partStructure->ifid
            ? trim($partStructure->id, " <>")
            : (isset($params['filename']) || isset($params['name']) ? mt_rand() . mt_rand() : null);

In my opinion $partStructure->ifid needs to be changed to $partStructure->ifdisposition. We had trouble that the html text was null. After changing it works great. Can you check this and change it?

grtz,

Rik

**Comment by barbushin** [comment]
Sorry for late response, but I still can't reproduce it. Could you send email with ifdisposition header to barbushin3@gmail.com?

**Comment by gitstashgithub** [comment]
Hi @barbushin although the mailbox.php has been updated several times since then I am having the same problem with the ifid. 

Currently on line 667

**Comment by Sebi94nbg** [comment]
@rtbweb @gitstashgithub 
Are you still facing this issue with the current latest version 3.0.17?

**Comment by Sebi94nbg** [comment]
Closing this since nobody replied and all seems to work as expected.
