### ISSUE TITLE
E-mail content ignore old replies

### ISSUE THREAD

**Issue by Cannonb4ll** [barbushin/php-imap#160]
When either using: `$mail->textHtml` or `$mail->textPlain` if I am replying to a e-mail, the subcontent is also included in that mail.

I am using this package to create tickets in a support system, but replies get really long this way because it includes the older e-mails that customers reply to in their email client.

Is there any way to avoid this?

**Comment by barbushin** [comment]
You can try to use some another mail client.

**Comment by surgiie** [comment]
@Cannonb4ll I know this is a pretty old issue, but im basically in similar situation, curious to what you ended up using.
