### ISSUE TITLE
Gmail Thread

### ISSUE THREAD

**Issue by mabilbao** [barbushin/php-imap#162]
Hi Guys,

I have an issue when I try to get the last emails of the thread from Gmail, I am only getting the first emails of the thread. Can you help me, please?

This is my code:

```
$inbox = new Mailbox($hostname, $username, $password, sys_get_temp_dir());
$emails = $inbox->searchMailbox('ALL');
if( $emails) {
    \Log::info(json_encode($emails));
    foreach($emails as $email_number) {
        $email = $inbox->getRawMail($email_number);
        \Log::info("------------------------------------------");
        \Log::info(json_encode($email));
        \Log::info("------------------------------------------");
    }
}
```

The situation in my Gmail account is:
- I sent an email to X with CC --> I got it
- X answered me and CC --> I got it
- I also cannot get any other email from this thread after this point.
- CC answered  --> I did not get it
- X answered me and CC --> I did not get it

Thanks for the help and let me know if you need more information.

**Comment by barbushin** [comment]
Try to use `sortMails()` method.
