### ISSUE TITLE
slow!!!!

### ISSUE THREAD

**Issue by qwe356558603** [barbushin/php-imap#167]
I downloaded data is a bit slow, I want to batch updates email  body and not with attachments.
Hope to write this way!!!!

**Comment by escobar022** [comment]
This is most likely a server issue with the email server or connection.

**Comment by barbushin** [comment]
Now you can use `getMailHeader()` method.

**Comment by nickl-** [comment]
duplicates #150

**Comment by Sebi94nbg** [comment]
Attachments can be ignore with the next available release:
```php
$mailbox->setAttachmentsIgnore(true);
```

Attachments will be processed by default, so you don't need to change your existing and already working code.
