### ISSUE TITLE
Null filePath in attachments

### ISSUE THREAD

**Issue by fede91it** [barbushin/php-imap#169]
Hello,

For each all my attachments I have a null filePath attribute. How to download an attached image or file?

**Comment by 91Abdullah** [comment]
You need to specify third parameter as directory in new MailBox object. For reference:

public function __construct($imapPath, $login, $password, **$attachmentsDir = null**, $serverEncoding = 'UTF-8') {
		$this->setImapPath($imapPath);
		$this->imapLogin = $login;
		$this->imapPassword = $password;
		$this->serverEncoding = strtoupper($serverEncoding);
		if($attachmentsDir) {
			if(!is_dir($attachmentsDir)) {
				throw new Exception('Directory "' . $attachmentsDir . '" not found');
			}
			$this->attachmentsDir = rtrim(realpath($attachmentsDir), '\\/');
		}
	}
Attachments would automatically be downloaded in specified folder.
