### ISSUE TITLE
Email Priority

### ISSUE THREAD

**Issue by littleylv** [barbushin/php-imap#176]
``
public function getMail($mailId, $markAsSeen = true) {
$headersRaw = imap_fetchheader($this->getImapStream(), $mailId, FT_UID);
$head = imap_rfc822_parse_headers($headersRaw);
``

It seems that php function 'imap_rfc822_parse_headers' dose not parse informations like 'X-Priority' or 'Importance' which contain in '$headersRaw'. So we must parse that manually. 
I would like to get an email's 'Importance (low/high/normal)'. But I dont think it's a good idea to change your core code by myself as it may cause conflicts when composer updating.
Could you please parse some other useful infomation that 'imap_rfc822_parse_headers' misses manually in your code please.

:)

**Comment by Sebi94nbg** [comment]
@littleylv @barbushin this ticket can be closed since the PR has been merged. :)
