### ISSUE TITLE
Link in signature instead of cid:attachment_id

### ISSUE THREAD

**Issue by obaiidfarooq** [barbushin/php-imap#179]
Link in signature instead of cid:attachment_id {
	connected mailbox: INBOX.sent
	cid not appearing only in forwarded messages but the image is appearing in other mail client like thunderbird
        also inline attachments array is not appearing in after we get attachments data from imap server.
}
for instance:
&#x3C;img width=211 height=48 id=&#x22;Picture_x0020_1&#x22; src=&#x22;imap://email@xyz.com@imap-server:143/fetch&#x3E;UID&#x3E;.INBOX&#x3E;35?part=1.1.2&#x26;filename=image001.jpg&#x22; alt=&#x22;Description: Description: email-signature&#x22;&#x3E;

**Comment by barbushin** [comment]
Man, sorry, but I'm not sure I can completely understand your problem. Could you give more extended description with more examples?

**Comment by Sebi94nbg** [comment]
Closing this due to no feedback.

Feel free to provide more information by commenting this issue or create a new issue.
