### ISSUE TITLE
no address list in getMailsInfo(), attachments duplicate

### ISSUE THREAD

**Issue by santaclaus21** [barbushin/php-imap#180]
What I need to do is:
- read email headers list from mailbox
- if address: xxx@asd.df exists in "TO" then 
- getmail, and later attachments.

The problems:
1) getMailsInfo() return only name od sender/receiver and no whole array but only FIRST
2) so, I run getMail() to obtain full list "TO" [in this moment function saves attachements (!) I don't need that] I would rather to do this later
3) If "TO" constains "xxx@asd.df" - then I need to get this emails (loop) so I run foreach($mail->getAttachments() as $ak => $av) - because in this moment I need to store file names in database.

What happend, attachemens has been downloaded twice. 
First time when call getMail... and second time when I run getAttachments().
Second one problem is that class could be check existing files (if exist in __DIR__) to do NOT DOWNLOAD THEM AGAIN [!]. It is horrible problem. If you don't delete email from mailbox... all the time when you read mailbox (getMail() - to get full address list) - attachements are saved again.. and again and again - still the same with changed part of file_name. 

You can check email in __DIR__ by name + md5() ... whatever. Please.... I have got 60GB attachements in a few months.

regards.

**Comment by barbushin** [comment]
Fixed. Feel free to use `getMailHeader()` method.

**Comment by santaclaus21** [comment]
Great! Thank you very much!

**Comment by santaclaus21** [comment]
Maybe I'm wrong but I've got an error (without composer):

'''
require_once ("PhpImap/Mailbox.php");
require_once ("PhpImap/IncomingMail.php");
require_once ("PhpImap/IncomingMailHeader.php");
....
$mailbox = new PhpImap\Mailbox(_ECFG::server, _ECFG::user, _ECFG::password, __DIR__.'/attach', 'utf-8');
$mails = array();

// Get some mail
$mailsIds = $mailbox->searchMailBox('ALL');
//if(!$mailsIds) { die('Skrzynka jest pusta'); }

$minfo = $mailbox->getMailsInfo($mailsIds);
  foreach ($minfo as $mh)
  {
    $mail = $mailbox->getMail($mh->uid);
...
Fatal error: Class 'PhpImap\IncomingMailHeader' not found in /srv/projects/_libs/prod/www/php/PhpImap/IncomingMail.php on line 7
...
'''

**Comment by santaclaus21** [comment]
found it...

require_once ("PhpImap/Mailbox.php");
require_once ("PhpImap/IncomingMailHeader.php");
require_once ("PhpImap/IncomingMailAttachment.php");
require_once ("PhpImap/IncomingMail.php");
