### ISSUE TITLE
searchMailbox failing with office 365

### ISSUE THREAD

**Issue by timo002** [barbushin/php-imap#184]
Hello,

When using office365 I'm unable to get all `UNSEEN` e-mails. I found out that in the `searchMailbox()` function `imap_search()` is used with the default charset `UTF-8`.

However, searching with the `UNSEEN` tag fails in that case. Removing the charset will fix this issue.

**Comment by jcornide** [comment]
Same problem here, but removing the charset doesn't fix the issue for me, neither passing null when creating the object as charset param or commenting the setEncoding line in the Mailbox class

**Comment by commanddotcom** [comment]
You can specify the charset.

		$mailbox = new PhpImap\Mailbox(
			$hostname, 
			$user 
			$pass, 
			false, // attachment
			'US-ASCII' // charset for outlook.office365.com
		);

 Later you might need `setServerEncoding()` method to get emails

**Comment by Sebi94nbg** [comment]
As already stated before: All search criterias can be used by changing the charset to `US-ASCII` or by disabling the charset for the `searchMailbox()` at all: `searchMailbox('SUBJECT "test"', true)` (`true` says "disable server encoding")

**Note:** Disabling the server encoding is not released in master branch yet. Version 3.0.11 will hopefully include it.

Search criterias with UTF-8 characters will still fail on Microsoft Exchange (Exchange, Outlook Office 365) servers as they do not support this. We're still checking, if we can implement a workaround to get it somehow working. See #306.
