### ISSUE TITLE
Undefined property: stdClass::$disposition

### ISSUE THREAD

**Issue by Apo-S** [barbushin/php-imap#190]
I got this error

> Undefined property: stdClass::$disposition in [../vendor/php-imap/php-imap/src/PhpImap/Mailbox.php, line 639]
> 
> Trace:
> PhpImap\Mailbox::initMailPart() - ROOT/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php, line 639
> PhpImap\Mailbox::getMail() - ROOT/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php, line 532

In this line

> if($partStructure->type == 2 && $partStructure->subtype == 'RFC822' && $partStructure->disposition !== "attachment") {

**Comment by codematiq** [comment]
This occurs again in 3.0.22. Please review!

**Comment by Sebi94nbg** [comment]
Already fixed: #347
