### ISSUE TITLE
Hundreds of files generated in directory

### ISSUE THREAD

**Issue by tribulant** [barbushin/php-imap#194]
It seems when the getMail() method is called, hundreds of files are generated in the directory of the script from the emails being read.

I'm on cPanel and use IMAP with the script and each time getMail() is called, this happens. Images, .mobileconfig files, attachments, etc. like it is downloading everything locally.

Any ideas why?

**Comment by tribulant** [comment]
I found this code which causes it:

`file_put_contents($attachment->filePath, $data);`

And I see there is a `$attachmentsDir` variable on the constructor function which is set to __DIR__ in the sample so that's the reason.

By setting this to `null` or `false`, the problem is resolved and attachments are not downloaded it seems.

Thanks, please mark this as invalid.

**Comment by mountainguan** [comment]
Every time when using getMail() will generate new files, because of the attachment id will generate by random every time.Even my mail has been get before,it still doing the same thing.

**Comment by Sebi94nbg** [comment]
As long as you don't set the directory path in the constructor, this library will not save any files:

`$mailbox = new PhpImap\Mailbox('{imap.gmail.com:993/imap/ssl}INBOX', 'some@gmail.com', '*********');`

When you specify the directory, it will save all attached files only once:

`$mailbox = new PhpImap\Mailbox('{imap.gmail.com:993/imap/ssl}INBOX', 'some@gmail.com', '*********', __DIR__);`
