### ISSUE TITLE
Email has no Body

### ISSUE THREAD

**Issue by primus852** [barbushin/php-imap#198]
I have an email where I don't have any `body` but my Outlook Application shows it normally
`$message = $parser->parse(file_get_contents(Constants::TMP_PATH . $file));`
`$message->getHtmlContent()` is `""`
`$message->getTextContent()` is `null`

In my `file_get_contents(Constants::TMP_PATH . $file)` I have a part like this (including the blank lines, markdown does not work properly here it seems):
`MIME-Version: 1.0

PG1ldGEgaHR0cC1lcXVpdj0iQ29udGVudC1UeXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJz
ZXQ9dXRmLTgiPihTZXJ2ZXI6ICZxdW90O0RBVEVWLUxPSE4mcXVvdDspIChBdWZ0cmFnOiAmcXVv
dDtCYWNrdXAgLSBCZXJnIC0gRGF0ZXYtTG9obi1JbmtyZW1lbnRlbGwmcXVvdDspIERlciBBdWZ0
cmFnIHd1cmRlIGVyZm9sZ3JlaWNoIGFiZ2VzY2hsb3NzZW4uIEVzIHRyYXRlbiBqZWRvY2ggZGll
IGZvbGdlbmRlbiBCZWRpbmd1bmdlbiBhdWY6CgoxIERhdGVpZW4gd3VyZGVuIMO8YmVyc3BydW5n
ZW4uCg==`

Which is the base64 encoded eMail Body. Any chance that the parser detects that?

**Comment by FusionPwN** [comment]
I've been getting the same exact issue, but for me it's decoding a winmail.dat attachment and passing it as plain text

**Comment by commanddotcom** [comment]
> I've been getting the same exact issue, but for me it's decoding a winmail.dat attachment and passing it as plain text

Fix in this pull request: https://github.com/barbushin/php-imap/pull/239
Commit: https://github.com/barbushin/php-imap/pull/239/commits/8693f71e3430c99f7f4ca1d994cf9fb3368dd360

**Comment by FusionPwN** [comment]
@commanddotcom I've tried that already it did not work

**Comment by FusionPwN** [comment]
`object(stdClass)[12]
  public 'type' => int 2
  public 'encoding' => int 0
  public 'ifsubtype' => int 1
  public 'subtype' => string 'RFC822' (length=6)
  public 'ifdescription' => int 0
  public 'ifid' => int 0
  public 'lines' => int 92
  public 'bytes' => int 6176
  public 'ifdisposition' => int 0
  public 'ifdparameters' => int 0
  public 'ifparameters' => int 0
  public 'parameters' => 
    object(stdClass)[13]
  public 'parts' => 
    array (size=1)
      0 => 
        object(stdClass)[14]
          public 'type' => int 3
          public 'encoding' => int 3
          public 'ifsubtype' => int 1
          public 'subtype' => string 'MS-TNEF' (length=7)
          public 'ifdescription' => int 0
          public 'ifid' => int 0
          public 'bytes' => int 4534
          public 'ifdisposition' => int 0
          public 'ifdparameters' => int 0
          public 'ifparameters' => int 1
          public 'parameters' => 
            array (size=1)
              ...`

**Comment by FusionPwN** [comment]
it's passing the whole part of "Content-Type: message/rfc822" as text to my email app, but it does not it show anywhere on webmail

**Comment by FusionPwN** [comment]
I bypassed the issue by doing this:
`if (!$isAttachment && strchr($data, 'Content-Type: application/ms-tnef; name="winmail.dat"')) {
	$isAttachment = true;
 }`
Since webmail is really getting a winmail.dat attachment no need to decode it

**Comment by helloHupc** [comment]
I have the same problem,an email can't normal parse body. textHtml is '' and plainHtml is ''. Is the reson that my version is 3.0.5

there is the email's partStructure:


{"type":1,"encoding":0,"ifsubtype":1,"subtype":"MIXED","ifdescription":0,"ifid":0,"ifdisposition":0,"ifdparameters":0,"ifparameters":1,"parameters":[{"attribute":"boundary","value":"----=_001_NextPart276727435753_=----"}],"parts":[{"type":1,"encoding":0,"ifsubtype":1,"subtype":"ALTERNATIVE","ifdescription":0,"ifid":0,"ifdisposition":0,"ifdparameters":0,"ifparameters":1,"parameters":[{"attribute":"boundary","value":"----=_002_NextPart104486840068_=----"}],"parts":[{"type":0,"encoding":3,"ifsubtype":1,"subtype":"PLAIN","ifdescription":0,"ifid":0,"lines":13,"bytes":954,"ifdisposition":0,"ifdparameters":0,"ifparameters":1,"parameters":[{"attribute":"charset","value":"GB2312"}]},{"type":0,"encoding":4,"ifsubtype":1,"subtype":"HTML","ifdescription":0,"ifid":0,"lines":96,"bytes":7400,"ifdisposition":0,"ifdparameters":0,"ifparameters":1,"parameters":[{"attribute":"charset","value":"GB2312"}]}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":954602,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMS5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMS5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1295030,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMi5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMi5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1826224,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMy5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMy5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1265572,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtNC5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtNC5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":2052882,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtNS5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtNS5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1192884,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtNi5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtNi5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1778016,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtNy5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtNy5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1541670,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtOC5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtOC5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1214116,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTAucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTAucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1357254,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTEucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTEucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1663096,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTIucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTIucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":2328112,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTMucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTMucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":2003748,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTQucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTQucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":2176566,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTUucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTUucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1315660,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTYucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTYucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1298680,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTcucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTcucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":2247640,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTgucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTgucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":34690,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?vfW9rdau0MdFz+7Evy25qdOmyczJ6sfrse1WMi4wLnhsc3g=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?vfW9rdau0MdFz+7Evy25qdOmyczJ6sfrse1WMi4wLnhsc3g=?="}]}]}

**Comment by Sebi94nbg** [comment]
@helloHupc this fix should be included in 3.0.7 or newer. I recommend to update to the latest version as a lot of issues have been fixed the last week.

**Comment by helloHupc** [comment]
> @helloHupc this fix should be included in 3.0.7 or newer. I recommend to update to the latest version as a lot of issues have been fixed the last week.

OK,thank you I try to update my version

**Comment by Sebi94nbg** [comment]
@helloHupc could you verify, if this issue has been solved with the latest version?

**Comment by ecgk** [comment]
I've updated to 3.0.20 and textHtml is NULL. :(

**Comment by Sebi94nbg** [comment]
Thanks for the feedback. We will further investigate this issue!

**Comment by ecgk** [comment]
Can anyone see the email body content? Is it a version issue or is it something else?

**Comment by Sebi94nbg** [comment]
@ecgk can you please show me your used code? Can you share the mail with us, which is empty for you?

If you don't want to share it here, you also can send me the EML file with all headers to php-imap AT outlook DOT com. Feel free to replace any (confidential) values in the mail with some random data (eg. your email with something@example.com or so).

**Comment by ecgk** [comment]
Im not reading EML, is a gmail account. Am I doing something wrong?

```
$mailbox = new \PhpImap\Mailbox('{imap.gmail.com:993/imap/ssl}INBOX', '***@***.org', '***!', __DIR__);
$mailsIds = $mailbox->searchMailBox("UNSEEN");

if ( !empty($mailsIds) ) {

    foreach ( $mailsIds as $mail_id ) {

        $mail = $mailbox->getMail($mail_id, FALSE);

        if ( !empty($mail->textHtml) ) {

            ...

            $mailbox->markMailAsRead($mail_id);
        }
    }
}
```

**Comment by Sebi94nbg** [comment]
Yes, I know. But when you could provide me the EML file, I could debug it. :)

You can get the EML file of your email by downloading it as described here: https://support.google.com/mail/answer/29436?hl=en

Do you know in which version it was working? Then I could compare the changes and patch it.

Your code snippet looks fine. Should definitely work.

**Comment by ecgk** [comment]
I've sent you the EML. In version 3.0.2 is working fine.
Thanks!

**Comment by Sebi94nbg** [comment]
Thanks. Got it.

Was this email sent from an Apple mail client from a Mac or any other Apple device (eg. iPhone, iPad, ...)?

Just asking, because all your emails contain this `--Apple-Mail=_2D35...` in the footer. :)

**Comment by Sebi94nbg** [comment]
There are only 179 commits in 22 files. :D
https://github.com/barbushin/php-imap/compare/3.0.2...3.0.23

Ok, your attached email is returning text for me, but the email, which contains the attached email is returning for me the entire email incl. headers.

So, something is wrong. I'll check this.

**Comment by Sebi94nbg** [comment]
The issue should be somewhere around these lines: [Mailbox.php L678](https://github.com/barbushin/php-imap/compare/3.0.2...3.0.23#diff-7f3ff3cf2fa5babe1eef4ffaa2ecc250L678) - [L693](https://github.com/barbushin/php-imap/compare/3.0.2...3.0.23#diff-7f3ff3cf2fa5babe1eef4ffaa2ecc250L693)

Maybe the `if`-conditions fails as they are more strict now: `$partStructure->type === TYPEMESSAGE` instead of `$partStructure->type == 2` for example.

**Comment by ecgk** [comment]
Some of the mails are from Apple mail client, others not. What should I do then? Im using version 3.0.2 for now. Thanks @Sebi94nbg

**Comment by Sebi94nbg** [comment]
You only have to wait. I'm already working on a fix. :)

**Comment by ecgk** [comment]
Thanks @Sebi94nbg. 💯

**Comment by Sebi94nbg** [comment]
@ecgk I've released a new version, which includes the fix for your issue: [3.0.24](https://github.com/barbushin/php-imap/releases/tag/3.0.24)

Please note, that not every mail has a HTML version, but every mail should have a plain text version, so you may check this first:

```php
if ($email->textHtml) {
        echo "Message HTML:\n" . $email->textHtml;
} else {
        echo "Message Plain:\n" . $email->textPlain;
}
```

I was able to parse your provided email with the used code from the examples: https://github.com/barbushin/php-imap/blob/3.0.24/examples/get_and_parse_unseen_emails.php

Let me know, what you think. :)

**Comment by ecgk** [comment]
Thanks. I've tried that with 3.0.24 and still not body. :(

**Comment by Sebi94nbg** [comment]
This is strange, because I am able to get the body from your provided email. :(

Is your application maybe caching some old code?

**Comment by ecgk** [comment]
Yes is caching, but after updating the package I've runned:
```
composer dump-autoload
php artisan clear-compiled
php artisan config:clear
php artisan route:clear
php artisan optimize
php artisan cache:clear
php artisan route:cache
php artisan view:clear
php artisan config:cache
php artisan queue:restart
```

If I run:
`composer show | grep imap`

I get:
`php-imap/php-imap                       3.0.24             Manage mailboxes, filter/get/delete emails in PHP (supports IMAP/POP3/NNTP)
`
Am I doing something wrong?

**Comment by Sebi94nbg** [comment]
Ah, Laravel. Ok, yes - you cleared every existing cache. :D

Ok, then it should be fine.

Back to your code since you're using the latest version and for me it's returning the body from your test mail.

What does it return for you, when you output the body immediately after getting the mail?

```php
$mail = $mailbox->getMail($mail_id, FALSE);

dd($mail->textPlain); // also try ->textHtml
```

**Comment by ecgk** [comment]
Well.. that is weird... 
`dd($mail->textPlain, $mail->textHtml);`
both return the mail body... 

If I change this:
`if ( !empty($mail->textHtml) )`
to this:
`if ( $mail->textHtml != '' )`
Everything goes fine.

It's weird right? In v3.0.2 asking if not empty works and now it doesn't...

**Comment by Sebi94nbg** [comment]
I've fixed this issue as well. I hope, your code is now fully working again.

![Nervous Look](https://pandagif.com/gifs/0IzKyf98RP.gif)

Released the fix in [3.0.25](https://github.com/barbushin/php-imap/releases/tag/3.0.25).

**Comment by ecgk** [comment]
😆 Yes! Thank you, now it's working again. 
Thanks @Sebi94nbg !

**Comment by Sebi94nbg** [comment]
Great, then I'll close this issue. Feel free to re-open / comment it, if there is anything else. :)
