### ISSUE TITLE
imap_utf7_encode wrap broke the headers parser

### ISSUE THREAD

**Issue by aymanrb** [barbushin/php-imap#201]
After upgrading to the Version 3.0.0 I found out my mail headers (subject, to, from, etc...) were all missing. Rolling back to version 2.2.5 makes it work again.

This is caused by the wrapping of the headerRaw argument by the `**imap_utf7_encode**` before parsing it with _imap_rfc822_parse_headers_.

**Comment by barbushin** [comment]
Fixed in release v3.0.1. Ayman, could you please check if it works now?

**Comment by NormanEdance** [comment]
Omg! Thank you, dude! `PhpImap\Exception [ 0 ]: IMAP method imap_rfc822_parse_headers() failed with error: Warning: message has unknown MIME version` is gone!

**Comment by aymanrb** [comment]
Yep, fixed for the headers :) not sure if the **utf7_encode** wrapping affected any other method. For now it looks fine

**Comment by barbushin** [comment]
@NormanEdance  @aymanrb Guys, thanks for bug report, and tests.
