### ISSUE TITLE
Too aggressive error checking on `imap()` function

### ISSUE THREAD

**Issue by underdpt** [barbushin/php-imap#207]
Hi,

I'm facing this error on some mails, calling `getMail` function:

`IMAP method imap_fetchheader() failed with error: Unexpected characters at end of address: ?=`

This exception is thrown at function `imap`, and after digging a bit, it seems to me that this function is way too pessimistic about the errors from `imap_errors()`, so that if there are any error, a exception is thrown or the function returns `false`, discarding the results of the `imap_...` function.

I would suggest to not throw the exception if the `$result` of the `imap_` function is not empty, and treat the error like a warning.

I've been reviewing all the `imap_...` functions used on the project, and lots of them returns `false` if an error happens. The unsafe ones with this approach would be:

- `imap_status()` always returns an object
- `imap_fetch_overview()`returns an array
- `imap_headers()` returns an array
- `imap_sort`returns an array
- `imap_num_msg()`returns an integer
- `imap_fetchbody()` returns a string
- `imap_fetchheader()` returns a string
- `imap_fetchstructure()` returns an object
-  `imap_body()` returns a string
- `imap_delete()` always returns true
- `imap_expunge()` always returns true

Except for the last two, it should suffice to check if the result is empty.

So the question is: would you take a look a PR that takes this into account? Maybe having an array of imap functions and what checks should be done to his output (`is_array`, `is_object` ...) to discard it or not, and having an option to `imap()` to allow for this less aggressive error detection.

**Comment by underdpt** [comment]
Of course, a way simpler function would be to change 

```php
if($errors) {
	if($throwExceptionClass) {
		throw new $throwExceptionClass("IMAP method imap_$methodShortName() failed with error: " . implode('. ', $errors));
	}
	else {
		return false;
	}
}
```

to:
```php
if($errors && empty($result)) {
	if($throwExceptionClass) {
		throw new $throwExceptionClass("IMAP method imap_$methodShortName() failed with error: " . implode('. ', $errors));
	}
	else {
		return false;
	}
}
```

but i'm not sure it would not have any side effects (testing it right now, but I only have a few test cases)

**Comment by barbushin** [comment]
100% agreed. Thanks!
