### ISSUE TITLE
Incorrect date with time zone

### ISSUE THREAD

**Issue by donriga** [barbushin/php-imap#209]
i have some problem, if getMail return date, this does not take time zone in message date

**Comment by adrium** [comment]
The OP is correct. Consider the following header:

    Date: Fri, 08 Jun 2018 09:57:36 +0200

The stored date in this case is:

    $incomingMail->date === '2018-06-08 09:57:36'

The Timezone information is lost and invalid timestamps will be calculated.

The mail above is sent on 1528444656 but the calculation based on `$incomingMail->date` would have to assume UTC and that leads to the incorrect result of 1528451856.

**Comment by nettunodev** [comment]
I have the same issue. Parsing this date "Thu, **24** Jul 2018 11:10:37 +0200" leads to **26** Jul 2018 11:10:37. I was testing the fix proposed by @adrium and it doesn't seem to work.

**Comment by Sebi94nbg** [comment]
Fixed with PR #301.
