### ISSUE TITLE
Problem downloading .gz attachments

### ISSUE THREAD

**Issue by MarkM80** [barbushin/php-imap#211]
Hello,

I have some problems downloading .gz files. The download of tar.gz files is working well. 

a print_r($mail); shows me the following result:

PhpImap\IncomingMail Object
(
[textPlain] => my sample mail
begin 644 mysamplefile.gz
M'XG(`(K%'%H``^Q=6V_;2)9^WU\AY*$QC=FR2-:%K#2"1O?,;,]B.H,!)L`N
M,%@TBF1)TFS<8JD9?O7[RG=;$GSF++%D2$GRNSG[G/KX59ESHZ;B:
MJHFNING,L;^.(]8S<1X3<QNPGHWEDQ'J'1OZ)X_'=].XGZ",'X?X/=A\#Y,1G\,PB#X

It seems that the script recognize the attachment "mysamplefile.gz" but also "open" the file directly.

a print_r($mail->getAttachments()); shows me this result:

attachment:
Array
(
)

Do you guys have any idea?

Best,
Mark

**Comment by cristicotet** [comment]
I think the email is not properly formatted. If you connect to the mailbox using webmail or other client how does it display the attachment?

**Comment by MarkM80** [comment]
thx cristicotet for your answer. the email format is ok via web client I can download the attachment without any problem.

After some testing I identified the following problem:
1. tar.gz attachments which includes a file like example.csv can be downloaded without any issues 
2. tar.gz attachments which include as file like example (without any extension) can't be downloaded

Even a not existing extension like "example_file.blabla" within a tar.gz works well. 

isn't this strange? Any ideas how to solve this issue without changing the attachments file name?

**Comment by Sebi94nbg** [comment]
Related to #278. Closing this issue here. Working on all this kind of issues in the referenced issue.
