### ISSUE TITLE
switchMailbox broken in last release.

### ISSUE THREAD

**Issue by cristicotet** [barbushin/php-imap#218]
In the last merge the switchMailbox function is broken. I've added a comment to the commit. This is the comment:
imap_reopen needs `resource $imap_stream` as the 1st argument. Setting `$prependConnectionAsFirstArg` to false means you already have this on `$args` argument. But `$args` is `$this->imapPath` in this case. This results in `switchMailbox` to not do anything.

**Comment by commanddotcom** [comment]
Why this issue is still open? The bug is fixed
