### ISSUE TITLE
Replace img CID

### ISSUE THREAD

**Issue by tasmanwebsolutions** [barbushin/php-imap#220]
Hi I would like to know how to replace the CID in the img tag

The image as download OK in to my folder

![cid](https://user-images.githubusercontent.com/5113934/34376833-dea11bf6-eb52-11e7-8e9d-46fc56216e42.PNG)

```
public function view() {
        // 4. argument is the directory into which attachments are to be saved:
        $mailbox = new PhpImap\Mailbox('{mail.riwakabowlingclub.co.nz:993/imap/ssl/novalidate-cert}INBOX', 'info@riwakabowlingclub.co.nz', 'MSCdgm78ZAQwsx@', FCPATH . 'downloads/email/');

        $mail = $mailbox->getMail($this->uri->segment(4));

        print_r($mail);
        echo "\n\nAttachments:\n";
        print_r($mail->getAttachments());
}
```

**Comment by barbushin** [comment]
See https://github.com/barbushin/php-imap/blob/master/src/PhpImap/IncomingMail.php#L40

**Comment by tasmanwebsolutions** [comment]
I added this below but nothing changed. 

$mail->getInternalLinksPlaceholders();

There no user guide?

**Comment by tasmanwebsolutions** [comment]
How do I call that function
