### ISSUE TITLE
Incorect mime type for files

### ISSUE THREAD

**Issue by Francois-Cright** [barbushin/php-imap#221]
Hello!

Everyting work fine, files are downloaded and can retrieve them but they are consider as text/html instead of correct extension (.pdf .doc etc.).
Firefox open the file like this: myfile.doc.htm

Anyone got this issue and a way to correct it ?

**Comment by commanddotcom** [comment]
What do you mean saying "they are consider as"? What is the extension of the files? .html?

**Comment by Francois-Cright** [comment]
No, they are still with the correct extension but it open a blank web page having the name of the file in the browser instead of downloading the file. If I force the download, like with a pdf, the program say that it cannot open it, **"bad format. The format seem to be an html document"**

**Comment by Francois-Cright** [comment]
I found it, There where spaces in the file name and the true file name has them replaced with underscore. argh!
