### ISSUE TITLE
How can I get the X-Failed-Recipients?

### ISSUE THREAD

**Issue by Daniyal-Javani** [barbushin/php-imap#227]
Hello
I want to store email addresses that are failed so I need to get the X-Failed-Recipients, I can see it in email source but how can I get it through php-imap? I try getRawMail but it's not in there.

**Comment by Sebi94nbg** [comment]
@Daniyal-Javani do you have an example email (header) or at least the excerpt of it?

All other headers, which are not RFC compliant and not commonly used are retrieved using this piece of code for each single header, which we want:

`$header->priority = (preg_match("/Priority\:(.*)/i", $headersRaw, $matches)) ? trim($matches[1]) : "";`

See line [572](https://github.com/barbushin/php-imap/blob/master/src/PhpImap/Mailbox.php#L572).

So you could do something similar in your application code to get `X-Failed-Recipients` from the `headersRaw`:
```php
$mail_header = $mailbox-> getMailHeader($mailId);
$failed_recipients = (preg_match("/Failed-Recipients\:(.*)/i", $mail_header->headersRaw, $matches)) ? trim($matches[1]) : "";
```

Contains some relevant information regarding the mentioned header: https://stackoverflow.com/questions/5298285/detecting-if-an-email-is-a-delivery-status-notification-and-extract-informatio
