### ISSUE TITLE
multipart/related

### ISSUE THREAD

**Issue by mrforsythexeter** [barbushin/php-imap#229]
Currently the library doesn't appear to handle Content-Type: multipart/related;..

So a message I am trying to process looks like this....
```
Content-Type: multipart/mixed;
	boundary="_009_VI1PR0302MB26699386E951CE94DC5F0DECAFF30VI1PR0302MB2669_"
MIME-Version: 1.0

--_009_VI1PR0302MB26699386E951CE94DC5F0DECAFF30VI1PR0302MB2669_
Content-Type: multipart/related;
	boundary="_008_VI1PR0302MB26699386E951CE94DC5F0DECAFF30VI1PR0302MB2669_";
	type="text/html"

--_008_VI1PR0302MB26699386E951CE94DC5F0DECAFF30VI1PR0302MB2669_
Content-Type: text/html; charset="iso-8859-1"
Content-ID: <A0192685C2D7804B828B7169A059B2A9@xxxxxxxxxxxxxxxxx.co.uk>
Content-Transfer-Encoding: quoted-printable
```

The last Boundary has the HTML message. (There are other parts after this.. more attachments). Should the library not attempt to load this into the textHtml? or is this a badly formatted email?

It is in the attachments, however the attachments don't appear to hold the mime type from each part.

With this, I could scan the attachments in an attempt to get the right part, and decode from there.

**Comment by nickl-** [comment]
related #39

**Comment by Sebi94nbg** [comment]
Fix has been merged.
