### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by billynoah** [barbushin/php-imap#233]
Docs start at item "4" - is there something missing?  Would love to see some more in depth examples, code samples or anything else to illustrate usage.

**Comment by barbushin** [comment]
There is no docs for this project. Where did you find it?

**Comment by ErikThiart** [comment]
In the readme: https://github.com/barbushin/php-imap/blob/master/README.md looks like something was cut off (incomplete)

**Comment by billynoah** [comment]
@ErikThiart - yes that's what I meant.  Are there any other docs or code samples available that illustrate how to use this library?

**Comment by commanddotcom** [comment]
[I've added few examples to the wiki](https://github.com/barbushin/php-imap/wiki/Examples-of-usage)

**Comment by Sebi94nbg** [comment]
I've updated the README and wiki to provide some more and better information:

- [README](https://github.com/barbushin/php-imap/tree/develop)
- [Wiki](https://github.com/barbushin/php-imap/wiki)

The documentation will be further improved.
