### ISSUE TITLE
Use of undefined constant SE_UID

### ISSUE THREAD

**Issue by ErikThiart** [barbushin/php-imap#234]
```
Notice: Use of undefined constant SE_UID - assumed 'SE_UID' in /var/www/html/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 244

Fatal error: Uncaught Error: Call to undefined function PhpImap\imap_utf7_encode() in /var/www/html/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:847 Stack trace: #0 /var/www/html/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(244): PhpImap\Mailbox->imap('search', Array) #1 /var/www/html/index.php(12): PhpImap\Mailbox->searchMailbox('ALL') #2 {main} thrown in /var/www/html/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 847
```

**Comment by barbushin** [comment]
Check if php_imap extension is enabled in your PHP. Check phpinfo()

**Comment by Flow999Cloud** [comment]
@barbushin  Same issue to me.
It works well when I try to call searchMailbox function on browser.
But it doesn't work when I try to call searchMailbox function via cron job. It just return to me the above error message.
Could you let me know what is the issue?
Thanks in advance.

**Comment by mirsabbir** [comment]
restart the server.

**Comment by tonypetro** [comment]
Fatal error: Uncaught Error: Class 'PhpImap\Mailbox' not found in /var/www/vhosts/ ...
Please how to solve this problem?
