### ISSUE TITLE
Non-ASCII encoding (Cyrrillyc etc.)

### ISSUE THREAD

**Issue by vitovt** [barbushin/php-imap#235]
When I try get list of IMAP folders which names contains non ASCII character - script gives error like this:

`PHP Fatal error:  Uncaught exception 'PhpImap\Exception' with message 'IMAP method imap_search() failed with error: must be in SELECTED state' in /usr/local/bin/get-email-prices/web/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:863`
`Stack trace:`
`#0 /usr/local/bin/get-email-prices/web/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(246): PhpImap\Mailbox->imap('search', Array)`
`#1 /usr/local/bin/get-email-prices/web/get_p0068_price.php(62): PhpImap\Mailbox->searchMailbox('UNSEEN')`
`#2 {main}
  thrown in /usr/local/bin/get-email-prices/web/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 863
`

### The problem is in:
> inbuild imap_utf7_decode() function

### The solutions is:

to replace it with 
> mb_convert_encoding()

`--- /usr/local/bin/get-email-prices/web/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php.orig   2018-03-31 22:15:37.964180999 +0300`
`+++ /usr/local/bin/get-email-prices/web/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php        2018-03-31 22:36:55.860180999 +0300`
`@@ -228,7 +228,9 @@`
`        public function getListingFolders($pattern = '*') {`
`                $folders = $this->imap('list', [$this->imapPath, $pattern]) ?: [];`
`                foreach($folders as &$folder) {`
`-                       $folder = imap_utf7_decode($folder);`
`+                       //$folder = imap_utf7_decode($folder);`
`+                       //$folder = imap_base64($folder);`
`+                       $folder = mb_convert_encoding($folder, "UTF-8", "UTF7-IMAP");`
`                }`
`                return $folders;`
`        }`
`@@ -844,7 +846,8 @@`
`                }`
`                foreach($args as &$arg) {`
`                        if(is_string($arg)) {`
`-                              $arg = imap_utf7_encode($arg);`
`+                               //$arg = imap_utf7_encode($arg);`
`+                               $arg = mb_convert_encoding($arg, "UTF7-IMAP", "UTF-8");`
`                        }`
`                }`
`                if($prependConnectionAsFirstArg) {`

**Comment by eatsleepcoderepeat** [comment]
Had the same problem, your fix did it for me.

Thanks!

**Comment by Sebi94nbg** [comment]
@barbushin can be closed as well: [Commit a6b2dd5](https://github.com/barbushin/php-imap/pull/296/commits/a6b2dd5409ed3de62696a1705fd27fedcfda06d7)

See PR #296.
