### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jolleychris** [barbushin/php-imap#236]
I can't find much documentation in terms of available methods and syntax, am I missing something?
I've seen a few specific examples, that have helped, but the project is described as being able to sort / filter mails etc. 
How can I leverage these facilities?

**Comment by NeftaliAcosta** [comment]
in the mailbox.php file all methods are documented with the values they receive and return.

**Comment by Sebi94nbg** [comment]
I've updated the README and wiki to provide some more and better information:

- [README](https://github.com/barbushin/php-imap/tree/develop)
- [Wiki](https://github.com/barbushin/php-imap/wiki)

The documentation will be further improved.
