### ISSUE TITLE
Saving files problem (Windows)

### ISSUE THREAD

**Issue by FuZuK** [barbushin/php-imap#238]
I attached the file with name "file_without_extension.". After that tried to save the files from this email but have got warning:
PHP Warning:  file_put_contents(C:\webbylab\fintickets-be\tmp\1069_1122515021324670732_file_without_extension.): failed to open stream: Permission denied in C:\webbylab\fintickets-be\vendor\php-imap\php-imap\src\PhpImap\Mailbox.php on line 706
Maybe this is related with fact that windows doesn't allow to save files with dot at the end of the name.
Version: 2.2.5

**Comment by Sebi94nbg** [comment]
You can save files without specifing any extension without any problems. Just try to save a new text file with the name `1069_1122515021324670732_file_without_extension.`. It will work - just tested in on Windows 10. :)

> failed to open stream: Permission denied

This sounds more like wrong permissions. Please make sure, that your web server has write permissions to the required directory.

If you're using the IIS as web server, the group "Users" should have full access to the directory `C:\webbylab\fintickets-be\tmp\` in the default configuration.

You may need to check under which user your process is running and which permissions / groups this user has / is assigned to.

**Comment by pedrofsantoscom** [comment]
This issue happens when saving any file without an extension but has the `.`at the end . You can try saving a file via php with the name `test.` that the same Permission denied warning shows up. If you try manually creating `test.` on windows, the OS will remove the `.` 
.
Untested solution:
IncomingMailAttachment.php saveToDisk():
```php
    public function saveToDisk()
    {
        $path = $this->filePath;
        $pi = pathinfo($path);
        if (empty($pi["extension"]))
            $path = $pi["filename"];
        if (false === @file_put_contents($path, $this->dataInfo->fetch())) {
            unset($this->filePath);
            unset($this->file_path);

            return false;
        }

        return true;
    }
```

**Comment by Sebi94nbg** [comment]
On which OS did you test it? I don't get any permission denied warning on Windows 10 x64 1903.

I only get the warning, that the file may get corrupted by changing (or removing) it's extension, but this is no permission denied message.

**Comment by pedrofsantoscom** [comment]
W10 x64 1803.
You read it wrong. I meant that windows removes the dot from the `test.` file name when creating it manually on windows (with the "file may get corrupted by changing" message). But via php if you try to create a file `test.`, it gives out the permission denied warning.
