### ISSUE TITLE
Regex for internal links

### ISSUE THREAD

**Issue by Kethryweryn** [barbushin/php-imap#24]
Hi,

The current regex in getInternalLinksPlaceholders doesn't work with links similar to 
="cid:image002.jpg@01CE7665.19E11940"

I had to change the line to :

```php
return preg_match_all('/=["\'](cid:([\w\.%*@-]+))["\']/i', $this->textHtml, $matches) ? array_combine($matches[2], $matches[1]) : array();
```

This will add the @ . - % and * characters to the list of accepted characters in the internal links.

@ and . are commonly used, % is for hex encoding the special chars, * seems to be used in http://tools.ietf.org/html/rfc2392

Not really sure if you can have the - but well, won't hurt. ;-)

I removed the ? in cid (didn't understand why there was one).

This sill won't work with "mid:" links, but I didn't have any in my mails to test it.

Thanks for the quick fixes.

**Comment by barbushin** [comment]
@Kethryweryn Thanks for report, and thanks a lot for issue!
