### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by avinash403** [barbushin/php-imap#241]
Is there a way to fetch all mails at once (just like getMailsInfo) instead of looping over it ? Basically i want to get the all the mail's body in one shot. Looping over it is making it very slow

**Comment by commanddotcom** [comment]
You can ignore attachments to improve performance. I made commit fc8b35fd6ce12a52949ee5f2cd71269468c69a1a and [pull request](https://github.com/barbushin/php-imap/pull/239) but it is still in the queue so you need to modify code on your own.

**Comment by eatsleepcoderepeat** [comment]
Hi, 
I don't think it's the loop that's causing it to be slow, it's probably the IMAP server.

For me, searching / filtering was slow, I solved part of that problem by hooking my mailserver up to a freshly spun up Apache Solr instance.

**Comment by Sebi94nbg** [comment]
Closing this as we need to iterate over all emails to get their body.

There is no PHP function, which returns the body with the initial call. You always need to fetch the email IDs and then the required information (header, body, ...) from each email.

The speed of the looping depends on the IMAP server, where you fetch your emails and the server, where you execute your PHP script.
