### ISSUE TITLE
The emoji expression in the email contents cannot be parsed successfully

### ISSUE THREAD

**Issue by lincome** [barbushin/php-imap#244]
![2](https://user-images.githubusercontent.com/7379732/40033594-a01664ae-582b-11e8-9cbc-f9850c2a9af0.png)
![1](https://user-images.githubusercontent.com/7379732/40033595-a05f9c00-582b-11e8-86d3-5f5597a0d3ab.png)
Does anyone have the same problem? How to solve

**Comment by commanddotcom** [comment]
Duplicate for #232

**Comment by mountainguan** [comment]
I think that would be the same problem for my issue #250

**Comment by Sebi94nbg** [comment]
Duplicate of #232.
