### ISSUE TITLE
fetching mail without encryption

### ISSUE THREAD

**Issue by avinash403** [barbushin/php-imap#245]
how do we tell Mailbox that we do not want any encryption while fetching mail ?

$mailbox = new PhpImap\Mailbox('{imap.gmail.com:993/imap/ssl}INBOX', 'some@gmail.com', '*********', __DIR__);

In above line, if we remove ssl for no encryption, throws an exception with message saying
IMAP method imap_open() failed with error: Can't open mailbox {host:143/imap/}INBOX: invalid remote specification

**Comment by Sebi94nbg** [comment]
This should do the trick:
`$mailbox = new PhpImap\Mailbox('{imap.gmail.com:143/imap}INBOX', 'some@gmail.com', '*********', DIR);`

Make sure, that you have NO ending `/` after the keyword `imap`.

You also need to make sure, that the email server supports unsecured / not encrypted IMAP.

GMail (Google) for example **requires** SSL: https://support.google.com/mail/answer/7126229?hl=en

**Comment by Sebi94nbg** [comment]
Closing this as it's already very old and the solution was provided.
