### ISSUE TITLE
Undefined property: stdClass::$host

### ISSUE THREAD

**Issue by putnik** [barbushin/php-imap#247]
Similar to what was in issue #149.

If the header contains an incorrect value, e.g.
```
From: http://example.com@noreply
```
then the `imap_rfc822_parse_headers()` function returns such an array:
```
array(3) {
  [0] =>
  class stdClass#3 (1) {
    public $mailbox =>
    string(4) "http"
  }
  [1] =>
  class stdClass#4 (2) {
    public $mailbox =>
    string(13) "//example.com"
    public $host =>
    string(7) "noreply"
  }
  [2] =>
  class stdClass#5 (0) {
  }
}
```
So `host` doesn't exist in first element in `src/PhpImap/Mailbox.php` at line `550`:
```
$header->fromAddress = strtolower($head->from[0]->mailbox . '@' . $head->from[0]->host);
```

**Comment by StApostol** [comment]
I also get this error when getting the message with header
`From: =?UTF-8?Q?first_part:_second_part?= <info@somesite.com>`

```
"from": array:3 [
    0 => {
      "mailbox": "=?UTF-8?Q?first_part"
    }
    1 => {
      "personal": "_second_part?="
      "mailbox": "info"
      "host": "somesite.com"
    }
    2 => {}
  ]
```

**Comment by Sebi94nbg** [comment]
`http://example.com@noreply` is no valid and RFC conform email address. I'm not sure, how you could even receive such an email header.

However, this explains, why the `imap_rfc822_parse_headers()` function is unable to get the correct values.

I've just committed a change to grab these information from array 0 (preferred) or 1. If none of both contains the searched value, it will be set to `NULL`.

Please note, that this library will NOT check, if the values are RFC conform and valid or not. You should already make sure at your mail server, that you only send / receive RFC conform emails.
