### ISSUE TITLE
Attachments shouldn't always be iconv'd

### ISSUE THREAD

**Issue by Kethryweryn** [barbushin/php-imap#25]
Hi,

The method initMailPart tries to convert all attachments as soon as a charset is defined.

However, the charset will sometimes be defined for attachments other than text (happened to me with .xlsx attachments).

The iconv line should be changed to convert only text parts : 

```php
if(!empty($params['charset']) && $partStructure->type === 0) {
            $data = iconv($params['charset'], $this->serverEncoding, $data);
        }
```

Sorry, I'm opening a lot of bug reports, I should have just compiled everything and made a push request but my company coding policy uses spaces instead of tabs so the merge would show the entire file as different for you... ;-)

**Comment by barbushin** [comment]
Fixed in 136261e8fd62bed48dc663f66026f786b6e01ebe. Thank you for report!
