### ISSUE TITLE
SendMail

### ISSUE THREAD

**Issue by boxbillinggit** [barbushin/php-imap#252]
can you add the functions of sending an e-mail?

`public function sendMails($to, $subject, $body, $headers, $cc, $bcc, $return_path,$save) {
		\imap_mail($to, $subject, $body, $headers, $cc, $bcc, $return_path); 
}`

**Comment by Sebi94nbg** [comment]
`php-imap` is - as the name already says - made for IMAP interactions, not SMTP.

You may want to checkout [PHPMailer](https://github.com/PHPMailer/PHPMailer) for sending RFC conform emails.
