### ISSUE TITLE
Limit mail reading

### ISSUE THREAD

**Issue by NeftaliAcosta** [barbushin/php-imap#256]
I am testing my system created with this library, and it occurred to me to use an outlook account with more than 10 years, the amount of emails is impressive.

Is there a way to limit it to bring the first 100 emails?
Is there a way to store all the mails in cache to avoid making requests to the server at any time?

**Comment by aymanrb** [comment]
You can definitely limit the messages by narrowing your search criteria. 

For example:
```
$mailIds = $mailbox->searchMailBox('SINCE "July 25 2018"');
```
For a full list of the search Criteria check: http://php.net/imap_search

Regarding the cache part you will need to create / use your own caching mechanism. This library is not intended to work as a mail client but rather as a wrapper to the IMAP protocol methods to ease the connection and manipulation of mailboxes
