### ISSUE TITLE
caching to improve loading time

### ISSUE THREAD

**Issue by NeftaliAcosta** [barbushin/php-imap#257]
the mail tray has many emails, I need to know how to cache the emails so that the load time is optimal since it takes a long time to load.
#IneedHelp

**Comment by commanddotcom** [comment]
This is imap library. It don't have built-in cache and it shouldn't be in this lib. 
If you're requesting one email more than once then something is wrong with your app.

Otherwise you can consider ignoring attachments to boost your app c31245182619023181bff54a98fe7bfab708b4cb

**Comment by NeftaliAcosta** [comment]
![image](https://user-images.githubusercontent.com/15948880/43874423-77acaa32-9b51-11e8-885e-50dfad31edc0.png)

I'm really trying to incorporate an email manager. I understand that the library has no cache. Can you suggest "something" to speed up the loading time?

Thank you

**Comment by Sebi94nbg** [comment]
As already mentioned: This library only provides IMAP functionalities.

Caching and creating indexes is a different part. Usually, this needs to be configured on server side or in the application itself. Mail clients usually sync the most important information (usually the mail headers), that they don't need to fetch those every time using IMAP. When the user opens an email later, the mail client only needs to get all information (body and attachements for example) for this single email by it's UID.

So I would create a command, which runs in a queue in the background to check regulary for new emails. Then just cache / save their headers in a temporary file, database (SQLite, MySQL, MS SQL, ...), Memcache or anything else.

Useful commands for this command might be [imap_status](https://www.php.net/manual/en/function.imap-status.php) and [imap_ping](https://www.php.net/manual/de/function.imap-ping.php) as they can reduce the IMAP traffic / operations.

Both of these functions can be used by this library:

```php
$mailbox = new PhpImap\Mailbox('{imap.gmail.com:993/imap/ssl}INBOX', 'some@gmail.com', '*********', __DIR__);
$mailbox->imap('status', array(string $mailbox , int $options));
$mailbox->imap('ping');
```

---
References:
- https://stackoverflow.com/questions/31498706/how-improve-email-fetching-by-php-imap
- https://www.reddit.com/r/PHP/comments/3dtcmb/how_improve_email_fetching_by_php_imap/
- https://stackoverflow.com/questions/33060991/php-imap-header-caching

**Comment by NeftaliAcosta** [comment]
Thank you very much.
