### ISSUE TITLE
Use of undefined constant SE_UID - assumed 'SE_UID'

### ISSUE THREAD

**Issue by Flow999Cloud** [barbushin/php-imap#260]
Hi, @barbushin 
Thanks for your great work on this library.

I just have some problems in using this library with cron jobs.
When I run `searchMailbox` function via cron jobs, it's sending the above error message.
Can you please let me know how can I fix it

Thanks.

**Comment by commanddotcom** [comment]
I have theory that it has noting to do with _php-imap_ library

**Comment by Flow999Cloud** [comment]
Hi, @commanddotcom 
Thanks for your reply, and nice to meet you.

I tried to find out the solution for all day long yesterday, and have some insights at the moment.
I think this is something related with php extension running issue. That is, the difference between on browser and CLI. Referencing [this issue(#234)](https://github.com/barbushin/php-imap/issues/234), I can see that the php extension is not enabled on the CLI mode, and it is only enabled on a browser mode. I am not sure why php extension is not working on the CLI mode.

If you have any other thoughts, please let me know.
Thanks.

**Comment by commanddotcom** [comment]
If I was you I won't even try to find the issue before rebuilding the server. At least you should reinstalled php and\or imap extension.

But if you ask me for the best guess I would say that you should pay attention who is the owner of php process. Something might be messed up with permissions. For example `imap.so` might be available only for root. Let's say that by default php runs as root, but cron runs php as some other user - that might cause the issue.

**Comment by barbushin** [comment]
PHP has different configs for web server and for cli mode. Just check if
php-imap extension is enabled for cli.

сб, 4 авг. 2018 г., 19:39 Flow999Cloud <notifications@github.com>:

**Comment by Flow999Cloud** [comment]
Thanks so much for your help. @commanddotcom , @barbushin 

I am using Mamp on my Mac to run the apache server and mysql server. Also I am running my project using vhost. (ex. testproject.test). That's why multiple php.ini files are exist on my Mac, and I had to setup correct php path in the cron job testing to use one of the php.ini files. That is, 
`/usr/local/etc/php/7.2/php.ini`
or `/Applications/MAMP/bin/php/php7.2.1/conf/php.ini`

So, I fixed the issue by updating cron job setting and following change is just I made in it.
`php /Volumes/Path/To/Project/artisan schedule:run >> /dev/null 2>&1`
to `/usr/local/bin/php /Volumes/Path/To/Project/artisan schedule:run >> /dev/null 2>&1`

Thanks again for your help. :pray:

**Comment by mirsabbir** [comment]
restart the server
