### ISSUE TITLE
Theres a way to return the headers like a object?

### ISSUE THREAD

**Issue by LeonardoPessatti** [barbushin/php-imap#266]
Theres a way to return the headers in individual objects, not in a unique string like in getMailHeader()?

**Comment by gbtux** [comment]
$cnx = new Mailbox(......);
$sorted = $cnx->sortMails(SORTDATE, true);
        $msgs = array_chunk($sorted, $per_page);
        $msgs = $msgs[$page-1];
        $result = $cnx->getMailsInfo($msgs);
var_dump($result);

Note $per_page is just an integer 
OK for you ?
BR

**Comment by LeonardoPessatti** [comment]
Yes, thank you.
