### ISSUE TITLE
Download attachment

### ISSUE THREAD

**Issue by grekpg** [barbushin/php-imap#268]
i see my attachment 

IncomingMailAttachment {#563 ▼
  +id: "14221071831878934793"
  +contentId: "auto_cid_2817556830"
  +name: "cpanel-logo-tiny.png"
  +filePath: null
  +disposition: "attachment"
}

how i can download it ?

**Comment by agafforov** [comment]
You don't need to download it manually. Set attachmentsDir in \PhpImap\Mailbox and it downloads them to given directory.
