### ISSUE TITLE
You don't need to download attachments manually. Set attachmentsDir in \PhpImap\Mailbox and it downloads them to given directory. Then in the IncomingMailAttachment->filePath you will see it's location.

### ISSUE THREAD

**Issue by grayVTouch** [barbushin/php-imap#270]
_Originally posted by @agafforov in https://github.com/barbushin/php-imap/issues/268#issuecomment-441263546_

How to set up to not download attachments??

**Comment by Xylane** [comment]
Just don't set attachmentsDir, and attachments won't downlod automatically :)

**Comment by Sebi94nbg** [comment]
Yep, agree. The code of `php-imap` will not save any attachements, when you do not specify the path.

Example:
```php
$mailbox = new PhpImap\Mailbox('{imap.gmail.com:993/imap/ssl}INBOX', 'some@gmail.com', '*********');
```

@barbushin I think this can be closed as well as it's already very old and there was no feedback for over 1 month after providing the solution.
