### ISSUE TITLE
Redirecting page if imap username and password not match in imap_open connection

### ISSUE THREAD

**Issue by awesomerfworld** [barbushin/php-imap#271]
Hallo @barbushin 

by the way, thanks a lot for build this plugin. 

I wanna ask you something or may i need help, how i redirect to the other page if imap username and imap password is not match ? (i mean redirect to page , not throwing exception). I'am using laravel.

thank you very much.
RF

**Comment by barbushin** [comment]
Hi

I don't think it's possible.

чт, 6 дек. 2018 г., 12:41 Ronniawan Fadhlillah notifications@github.com:

**Comment by commanddotcom** [comment]
```php

function handleEmailError($error) {
	if (strpos($error, 'AUTHENTICATIONFAILED') !== false) {
		header("Location:http://example.com/");
	} 
}

// bla-bla-bla

$mailbox = new PhpImap\Mailbox('{imap.gmail.com:993/imap/ssl}INBOX', 'some@gmail.com', '*********', __DIR__);

try {
	$Mailboxes = $mailbox->getMailboxes('*'); // any action
} catch(Exception $e) {
	handleEmailError($e->getMessage());
}

```

**Comment by Sebi94nbg** [comment]
@awesomerfworld I handle your scenario like this in my Laravel application:

```php
<?php
$mbox_connection = new Mailbox($mailbox, $mailbox_username, $mailbox_password, $attachment_dir);

try {
	// PHP.net imap_search criteria: http://php.net/manual/en/function.imap-search.php
	$mailsIds = $mbox_connection->searchMailbox('UNSEEN');
} catch(ConnectionException $ex) {
	$this->error("IMAP connection failed: " . $ex->getMessage());
	die();
}

if(empty($mailsIds)) {
	$this->comment("No unseen emails found.");
	$mbox_connection->disconnect();
	die();
}

$this->info("Parsing " . count($mailsIds) . " new email(s). Please wait...");

foreach($mailsIds as $mailId) {
	// Do something with each single email
	// Eg. marking them as read, storing them somewhere, ...
}

$mbox_connection->disconnect();
```

This is an excerpt of my [Laravel Artisan Command](https://laravel.com/docs/5.8/artisan).

**Comment by awesomerfworld** [comment]
Hai all, thank you for all the answer. by the way, i forget to close this case and i've been solve my problem (i'm so sorry ;)). my laravel script like this, 

`$crtConnection = @imap_open("$request->mailbox", $request->email, $request->password);
       imap_errors();
       imap_alerts();

       if($crtConnection == true)
       {
         $ad = ActiveDirectory::where('email', '=', $request->email)->where('active','=','1')->first();
         if($ad!=null)
         {
           Auth::loginUsingId($ad->id);
         }
       }
       return back()->withErrors(['Email and password is incorrect. Or maybe your account currently suspended by Administrator']);`

one more time, thank you all. Having fun :)

**Comment by Sebi94nbg** [comment]
Thanks for the feedback and your example code!

Can you please close this issue? Only @barbushin and you can close it. :)
