### ISSUE TITLE
Not reading arabic characters while fetching from outlook.com

### ISSUE THREAD

**Issue by avinash403** [barbushin/php-imap#274]
Firstly it wasn't fetching mails at all from outlook.com, and was showing 
```
IMAP method imap_search() failed with error: [BADCHARSET (US-ASCII)] The specified charset is not supported.
```
For a workaround I changed the encoding for cases where this exception comes. Now if email body has arabic characters, it skips them and fetches the rest of  the body.

STEPS TO REPRODUCE:
Fetch mail from an outlook account with encoding as `US-ASCII` and body as below 
```
مقتطفات من: صن تزو. "فن الحرب". كتب أبل. Something in english
```

After fetching body will only have 
```
Something in english
```

**Comment by Sebi94nbg** [comment]
Fixed with above referenced commit. Will be included in the next release.
