### ISSUE TITLE
Composer version is not the same as repo

### ISSUE THREAD

**Issue by delta1186** [barbushin/php-imap#275]
Your repo is on version 3.0.6.  When you install the package using composer it says it is version 3.0.6, but it is not.  I completely removed the package without luck.  Still installed old version.  How I know this was just be comparing changes from repo on 3.0.6 and they are not reflected on the version installed.  My version's composer.json file still has the reference:

 "extra": {
        "branch-alias": {
            "dev-master": "3.0-dev"
        }
    }

Might need to look at package on packagist.

**Comment by Sebi94nbg** [comment]
@barbushin can you please look into this? This is currently blocking users to update their `php-imap` using `composer`.

Latest version: 3.0.8
Available version at [Packagist](https://packagist.org/packages/php-imap/php-imap): 3.0.6

My `composer.json` requires this package as described here:
```
{
    "require": {
        "php-imap/php-imap": "^3.0",
    }
}
```

**Comment by barbushin** [comment]
Fixed
