### ISSUE TITLE
i need to insert port at my imap path 

### ISSUE THREAD

**Issue by stoneasher** [barbushin/php-imap#288]
my smtp path is smtp.domain.com and port is 465

the default one one is :
`protected $imapPath;`

i want to append the port to it so it become :
`protected $imapPath = smtp.ionos.com:465;`

i need to add the port without syntax error

it throw out this  error : 
Parse error: syntax error, unexpected ':', expecting variable (T_VARIABLE) in /homepages/htdocs/mydomain.net/core/PhpImap/Mailbox.php on line 11

Any help would be appreciable .

**Comment by Sebi94nbg** [comment]
First of all: You're using the wrong server and port. This *php-imap* repository is providing IMAP functionalities, so you can read incoming emails using the IMAP protocol. The server and port, you've mentioned is only used for sending outgoing emails using the SMTP protocol.

If you want to send emails, the php-imap repository will not help you at all as it does not provide any features to send emails. In this case, you may want to take a look at the [PHPMailer](https://github.com/PHPMailer/PHPMailer) repository.

It is NOT necessary to change anything in the `PhpImap/Mailbox.php`. Please revert your changes to the original.

In your application, you should have a code, where you define your mailbox. The wiki of this repository for example has a full example: https://github.com/barbushin/php-imap/wiki/My-working-example

This is an excerpt of the example from the wiki:
```
// Configuration for the Mailbox class
$hoststring = '{imap.gmail.com:993/imap/ssl/novalidate-cert}INBOX';

// Construct the $mailbox handle
$mailbox = new Mailbox($hoststring, $username, $password, $attachdir);
```

Based on the [documentation of IONOS](https://www.ionos.com/help/email-office/general-topics/settings-for-your-email-programs-imap-pop3/), your `$hoststring` should look like this:

`{imap.ionos.com:993/imap/ssl}INBOX` (with SSL)
or
`{imap.ionos.com:143/imap}INBOX` (Unsecured; without SSL)

German IONOS (previous called Profitbricks) customers may want to use the DE servers:

`{imap.ionos.de:993/imap/ssl}INBOX` (with SSL)
or
`{imap.ionos.de:143/imap}INBOX` (Unsecured; without SSL)

German documentation: https://www.ionos.de/hilfe/e-mail-office/mail-basic-verwalten/einstellungen-fuer-ihr-e-mail-programm-imap-pop3/

I hope, I could help you.
