### ISSUE TITLE
[BUG] Issue with certain date format

### ISSUE THREAD

**Issue by yellow1912** [barbushin/php-imap#310]
**Environment (please complete the following information):**
 - PHP IMAP version: Latest
 - PHP Version: [e.g. 7.2]
 - Type of execution: [php-fpm]

**Describe the bug**
The line 945 in Mailbox.php reads like this:

```
$dateRegex = '/\\s*\\(.*?\\)/';
                        $dateFormatted = \DateTime::createFromFormat(\DateTime::RFC2822, preg_replace($dateRegex, '', $dateHeader));
                        return $dateFormatted->format('Y-m-d H:i:s');
```

If the date does not meet the expected format, the $dateFormatted is a boolean variable so we need to ensure either throw an exception or just take current datetime as alternative?

**To Reproduce**

Use this date string for example: 7 Nov 2018 23:44:15 -0500

**Comment by Sebi94nbg** [comment]
You're right. This is causing the following error:
> Error: Call to a member function format() on boolean

I would rather just take the current datetime as throwing an exception would always end in the result, that you can not parse these emails.

I'll commit this change this evening.

**Comment by Sebi94nbg** [comment]
This issue has been fixed. See references above.

- If the given `$dateHeader` is empty, it will throw an `InvalidParameterException`
- If the provided `$dateHeader` can not be formatted, it will return the current datetime (as before)
- If the provided `$dateHeader` could be formatted, it will return this formatted / normalized datetime

The latest release [3.0.12](https://github.com/barbushin/php-imap/releases/tag/3.0.12) includes this fix.
