### ISSUE TITLE
[BUG] in Mailbox::setConnectionArgs()

### ISSUE THREAD

**Issue by olegbaturin** [barbushin/php-imap#313]
**Describe the bug**
Exception if setting only $retriesNum and leave $options = 0.

public function setConnectionArgs($options = 0, $retriesNum = 0, $params = null)
$supported_options = array(OP_READONLY, OP_ANONYMOUS, OP_HALFOPEN, CL_EXPUNGE, OP_DEBUG, OP_SHORTCACHE, OP_SILENT, OP_PROTOTYPE, OP_SECURE);
if(!in_array($options, $supported_options)) {
throw new InvalidParameterException('');
}

**To Reproduce**
$mailbox->setConnectionArgs(0, 3, []);

**Expected behavior**
Skip setting $options if 0

**Comment by Sebi94nbg** [comment]
I've fixed this issue with the above reference commit.

Possible function calls will be:

```php
// Change $options (integer and constants are possible)
$mailbox->setConnectionArgs(2);
$mailbox->setConnectionArgs(OP_READONLY);

// Change $options and $retriesNum
$mailbox->setConnectionArgs(2, 3);
$mailbox->setConnectionArgs(OP_READONLY, 3);

// Change $options, $retriesNum and $params
$mailbox->setConnectionArgs(0, 3, ['DISABLE_AUTHENTICATOR' => 'GSSAPI']);
$mailbox->setConnectionArgs(OP_READONLY, 3, ['DISABLE_AUTHENTICATOR' => 'GSSAPI']);

// Change only $retriesNum (set before required parameters to their defaults)
$mailbox->setConnectionArgs(0, 3);

// Change only $params (set before required parameters to their defaults)
$mailbox->setConnectionArgs(0, 0, ['DISABLE_AUTHENTICATOR' => 'GSSAPI']);
```

The next release will include this fix.
