### ISSUE TITLE
[BUG] Exception by emails with empty subject

### ISSUE THREAD

**Issue by raumkreuzer** [barbushin/php-imap#315]
**Environment (please complete the following information):**
 - PHP IMAP version: 3.0.12
 - PHP Version: PHP 7.2.17-0ubuntu0.18.04.1
 - Type of execution: CLI

**Describe the bug**
Exception by emails with empty subject

PHP Fatal error:  Uncaught Exception: decodeMimeStr() Can not decode an empty string!
/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(713): PhpImap\Mailbox->decodeMimeStr('', 'UTF-8')

**To Reproduce**
Steps to reproduce the behavior.

The used code:
```php
$mail = $this->mailbox->getMail($mailId, false);
```
**Solution could be:**

./vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:713

org:
$header->subject = isset($head->subject)  ? $this->decodeMimeStr($head->subject, $this->serverEncoding) : null;

to:
$header->subject = isset($head->subject) **AND !empty($head->subject)** ? $this->decodeMimeStr($head->subject, $this->serverEncoding) : null;

**Comment by Sebi94nbg** [comment]
Already solved in #314. The new version has been released: [3.0.13](https://github.com/barbushin/php-imap/releases/tag/3.0.13)
