### ISSUE TITLE
Empty date - "parseDateTime() expects parameter 1 to be a parsable string datetime"

### ISSUE THREAD

**Issue by tomnuss** [barbushin/php-imap#318]
I found an issue with an empty date line. The e-mail has a line with "Date:", but it's empty afterwards. As a result, I'm getting the following error: 

> parseDateTime() expects parameter 1 to be a parsable string datetime

Tested with version 3.0.14. 

By editing `Mailbox.php` it can be solved by adding ` AND !empty($head->date)` to line 744. 

```
if(isset($head->date) AND !empty($head->date)) {
	$header->date = self::parseDateTime($head->date);
} else {
	$now = new DateTime;
	$header->date = self::parseDateTime($now->format('Y-m-d H:i:s'));
}
```

It's an e-mail sent to my Gmail box. Happy to share the original e-mail, but other than the line "Date:" with no date, there is nothing else unusual and the above solves the issue.

**Comment by Sebi94nbg** [comment]
Thanks for reporting this issue! I've quickly fixed it and published a new release [3.0.15](https://github.com/barbushin/php-imap/releases/tag/3.0.15). :)
