### ISSUE TITLE
a wrong call in fetch function

### ISSUE THREAD

**Issue by helloHupc** [barbushin/php-imap#324]
my phpimap version is 3.0.15
in DataPartInfo.php line 64, the $this->data has been imap_base64(),why also call decodeMimeStr function. Isn't it shuoud to call convertStringEncoding.
I have a problem in there,the email content is parsed to disorder coding. When I change the function to  convertStringEncoding,it's ok.
like this in line 64:
$this->data = $this->mail->convertStringEncoding($this->data, $this->charset, $this->mail->getServerEncoding());

the MIME header element I debugged is:
DQqy4srUDQoNCg0KaHVwZW5nY2hlbkByZGMuZ253YXkuY29tDQo=

**Comment by Sebi94nbg** [comment]
Fix will be included in the next release.
