### ISSUE TITLE
[BUG] another character encoding issue

### ISSUE THREAD

**Issue by codematiq** [barbushin/php-imap#335]
I was getting weird characters (question marks etc - [)](https://i.stack.imgur.com/7bolA.png) instead of Lithuanian letters (ąčęėįšųūžĄČĘĖĮŠŲŪŽ) while fetching emails. Was looking for resolution for good few days - and nothing helped. Tried ALL POSSIBLE encoding.decoding solutions - nothing helped.

Then i discovered - php-imap/php-imap version ^2.0 DOES NOT HAVE this encoding problem. I Switched from 3.0 to 2.0 and weird characters were gone! Normal letters were back: ąčęėįšųūžĄČĘĖĮŠŲŪŽ

So in version 3.0 something with encodings has to be fixed. Please do.

**Comment by Sebi94nbg** [comment]
Thanks for reporting this issue!

Can you please share your used code, which you used to test / identify this issue? Or can you mention, which encoding function of `php-imap` is causing this?

**Comment by codematiq** [comment]
Will try to reproduce in different environments (vanilla PHP, Laravel, Symfony) - will report results and what potentialy may cause anomaly.

**Comment by codematiq** [comment]
I have reproduced the issue.
1. Pulled latest php-imap/php-imap
2. Loaded it and **as per instruction** fetched emails

Here's my code:
```php
<?php

require 'vendor/autoload.php';
use PhpImap\Mailbox;


$mailbox = new Mailbox(
    '{mail.******.com:993/imap/ssl}INBOX', // hidden for security
    'test@******', // hidden for privacy
    '******', // hidden for security
    __DIR__,
    'UTF-8'
);

try {
    $mailsIds = $mailbox->searchMailbox('ALL');
    $mailbox->setAttachmentsIgnore(true);

    if ($mailsIds)
    {

        foreach ($mailsIds as $mailId)
        {
            $mail = $mailbox->getMail($mailId);

            echo 'Subject: '.$mail->subject.'<br>';
            echo 'From: '.$mail->fromName.'<br>';
            echo "<br>";
            echo 'Body: '.$mail->textHtml.'<br>';
            echo "<br>";
            echo "<hr>";
        }

    } else {
        echo "inbox is empty";
    }

} catch(PhpImap\Exceptions\ConnectionException $ex) {
    echo "IMAP connection failed: " . $ex;
    die();
}
```
With version 3.0 i get weird symbols.

![Screenshot 2019-05-29 at 09 55 26](https://user-images.githubusercontent.com/44578107/58536704-fcd26f00-81f9-11e9-87dc-05f4b8a67310.png)

With version 2.0 - all lithuanian symbols are displayed correctly.

![Screenshot 2019-05-29 at 10 11 16](https://user-images.githubusercontent.com/44578107/58536771-27bcc300-81fa-11e9-99f6-b1963ccff128.png)

### This was tested in vanilla PHP 7.3 and in Laravel 5.8. Same symptoms.

**Comment by Sebi94nbg** [comment]
Thanks for testing it in so many frameworks! I'll create some more PHPUnit tests for your case and fix the issue(s) based on these results.

**Comment by Sebi94nbg** [comment]
@codematiq which exact version `2.0.x` did you use, where it works fine?

I'm currently debugging with `2.0.9`: https://github.com/barbushin/php-imap/compare/2.0.9...master

**Comment by Sebi94nbg** [comment]
@codematiq your feedback is required.

**Comment by codematiq** [comment]
> @codematiq which exact version `2.0.x` did you use, where it works fine?
> 
> I'm currently comparing [2.0.9...master](https://github.com/barbushin/php-imap/compare/2.0.9...master).

It is 2.2.5 which works fine

**Comment by Sebi94nbg** [comment]
Thanks, I'll compare https://github.com/barbushin/php-imap/compare/2.2.5...master.

**Comment by hyncica** [comment]
I'm currently experiencing same issue. I think this was caused by commit e4d5130b7d539bc636c397c68f7c94cb62ef8e3b that made method convertStringEncoding skip conversion for all windows encodings.

**Comment by Sebi94nbg** [comment]
@codematiq @hyncica 
Can you please test this again with the new version [3.0.22](https://github.com/barbushin/php-imap/releases/tag/3.0.22)? Thank you!

**Comment by hyncica** [comment]
Version 3.0.22 works fine for me.

**Comment by codematiq** [comment]
Characters are now working fine. This one is seems to be solved. However there's another issue in Mailbox.php. I will list it separately.

**Comment by Sebi94nbg** [comment]
Great. Thanks for testing and your feedback! :)

Feel free to open new issues, when you find more.
