### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by D4V3M0NK** [barbushin/php-imap#336]
Just a note to add to the documentation, one also needs PHP's **mbstring** installed, otherwise even when running through the documentation examples, you'll receive :

```
PHP Fatal error:  Uncaught Error: Call to undefined function PhpImap\mb_list_encodings() in /var/www/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:108
Stack trace:

#0 /var/www/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(48): PhpImap\Mailbox->setServerEncoding('UTF-8')

#1 /var/www/html/test.php(10): PhpImap\Mailbox->__construct('{imap.gmail.com...', ....)

#2 {main}
  thrown in /var/www/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 108
```

**Environment:**
 - PHP IMAP version: [e.g. 3.0.20]
 - PHP Version: [e.g. 7.2.17]
 - Type of execution: [e.g. CLI / Apache2]

**Comment by Sebi94nbg** [comment]
- Updated the documentation / readme
- Updated PHPUnit tests to test all required extensions
- Added code to avoid the fatal PHP error

It's currently in the `develop` branch: https://github.com/barbushin/php-imap/tree/develop

All changes will be included in the next release.
