### ISSUE TITLE
[Improvement] Show, if email has attachments or not without processing these

### ISSUE THREAD

**Issue by ceo-zenlix** [barbushin/php-imap#340]
Thank you for good product! =)
And, how i can check (without loading attachments), if attachments is exists in mail?

**Comment by Sebi94nbg** [comment]
This is currently not possible, unfortunately.

You can either load attachments and see how many exists or don't load them and don't see, if this email has attachments or not.

I'll update this issue to a feature request / improvement to be able to do this with upcoming releases. :)

**Comment by ceo-zenlix** [comment]
@Sebi94nbg thank you very much!

**Comment by Sebi94nbg** [comment]
This improvement has been implemented!

```php
// Get any message
// In this example, we will just take the first one
$mail = $mailbox->getMail($mailsIds[0]);

// Show, if $mail has one or more attachments
echo "\nMail has attachments? ";
if($mail->hasAttachments()) {
	echo "Yes\n";
} else {
	echo "No\n";
}
```

I've updated the README as well as the wiki: https://github.com/barbushin/php-imap/wiki/Getting-Started

This change will be included in the next release.

**Comment by ceo-zenlix** [comment]
@Sebi94nbg it's great!!!
