### ISSUE TITLE
[BUG]  ErrorException Undefined property: stdClass::$disposition

### ISSUE THREAD

**Issue by Parsk** [barbushin/php-imap#347]
Thank you for a great tool, been using it without issue for many years, however the newest version seemed to have resurrected an old bug.

 - PHP IMAP version: 3.0.22
 - PHP Version: 7.0.33
 - Type of execution: CLI

Similar to issue https://github.com/barbushin/php-imap/issues/190

`at HandleExceptions->handleError(8, 'Undefined property: stdClass::$disposition', '/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php', 873, array('mail' => object(IncomingMail), 'partStructure' => object(stdClass), 'partNum' => 3, 'markAsSeen' => false, 'emlParse' => false, 'options' => 3, 'dataInfo' => object(DataPartInfo), 'this' => object(Mailbox), 'params' => array(), 'isAttachment' => false))in Mailbox.php line 873
`

Called by

`Mailbox->initMailPart(object(IncomingMail), object(stdClass), 3, false)in Mailbox.php line 828`

**Comment by barbushin** [comment]
Fix released in 3.0.23. Check please
