### ISSUE TITLE
Returned string from textPlain and textHtml

### ISSUE THREAD

**Issue by Robinjoeh** [barbushin/php-imap#354]
- PHP IMAP version: 3.0.26
 - PHP Version: 7.3.6
 - Type of execution: Daemon

The `$mail->textHtml` sometimes returns a base64 encoded string (which when decoded contains some message headers, the body HTML, and body plain text). When it is not base64-encoded, it returns the body HTML and the body plain text.

The same applies for `$mail->textPlain`, which also returns a string with body HTML and plain text.

Is this expected behaviour?

**A sample return of `$mail->textHtml` below:**

> --000000000000c69381051a482fdf
> --
> Content-Type: text/plain; charset="UTF-8"; format=flowed; delsp=yes
>  
> Here goes the text content
> Here goes the text content
> Here goes the text content
>  
>  
>  
> --000000000000c69381051a482fdf
> Content-Type: text/html; charset="UTF-8"
> Content-Transfer-Encoding: quoted-printable
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
> <!doctype html public "- / /w3c / /dtd xhtml 1.0 strict / /en" "http: / /www.w3.org /tr /xhtml1 /dtd /xhtml1-strict.dtd">
> <html xmlns=http://www.w3.org/1999/xhtml dir=auto>
> <head>
> <meta name=viewport content=initial-scale=1>
> <style type=text/css>
> a {color: #4285F4;}
> #body_container{max-width:600px;}
> </style>
> </head>
> <body>
>  Here goes the HTML
>  Here goes the HTML
>  Here goes the HTML
> </body></html>
> 
> --000000000000c69381051a482fdf--

**Comment by Sebi94nbg** [comment]
Can you please provide an example header, if possible and show us, what's the current behaviour and which behaviour you have expected?

As far as I understood your issue, this should be related to #198 and #200.

**Comment by Sebi94nbg** [comment]
@Robinjoeh friendly reminder.

**Comment by Sebi94nbg** [comment]
Closing this issue due to no feedback after more than two weeks. Feel free to comment this issue or open a new issue.
