### ISSUE TITLE
[Question] Move to different folder

### ISSUE THREAD

**Issue by D4V3M0NK** [barbushin/php-imap#355]
From what I can gather, once you're connected to a specific folder within a mailbox, you're able to perform a number of functions, and this is all working wonderfully. 

If I were to then require to perform other functions in another folder (same mailbox), do I create a new PhpImap\Mailbox object with all it's associated connections and the alternative folder as it's last parameter, in order to access that folder, or is there an IMAP "select" equivalent, which allows me to navigate between folders?

**Comment by Sebi94nbg** [comment]
Please take a look at the [Getting Started](https://github.com/barbushin/php-imap/wiki/Getting-Started) from the wiki.

You can switch the mailbox folder at any time using the function `switchMailbox($folderPath)`.

Example:
```php
// Initially connect to mailbox folder 'INBOX'
$mailbox = new PhpImap\Mailbox(
	'{imap.gmail.com:993/imap/ssl}INBOX', // IMAP server incl. flags and optional mailbox folder
	'some@gmail.com', // Username for the before configured mailbox
	'*********' // Password for the before configured username
);

// Do something (eg. getting mails)

// Switch from mailbox folder 'INBOX' to eg. 'SENT'
$mailbox->switchMailbox('SENT')

// Do something (eg. getting mails)
```

In the README, you'll also find an example at the bottom to loop through all folders: https://github.com/barbushin/php-imap/blob/master/README.md

You can use every single PHP IMAP function, which you can find here: https://www.php.net/manual/en/ref.imap.php

If there is no explicit `php-imap` function like `switchMailbox()`, you can use the function `imap()` of this library. Also see the README at the bottom. :)

**Comment by D4V3M0NK** [comment]
Perfect, just what I was looking for, thank you.

**Comment by Sebi94nbg** [comment]
I'm glad, that I could help you. Thanks for closing this issue! :)
