### ISSUE TITLE
ask one question

### ISSUE THREAD

**Issue by helloHupc** [barbushin/php-imap#357]
if the $mailsIds is seen, $mailbox->markMailsAsRead($mailsIds) ,what is the return of the function.
I have a situation，the next is my program execute sequence：
1.$mailsIds = $mailbox->searchMailbox('UNSEEN');
2.$mailbox->markMailsAsRead($mailsIds);
3.$mail = $mailbox->getMail($value);
I met one mailsId ，arrive step 2 is return，so I want to know what is the return of step 2.
the other, is there one function I can get the status of mailsId. is seen or unseen

**Comment by Sebi94nbg** [comment]
It's currently not returning anything, but it should throw an exception of the type `Exception::class` when it failed. So a `try-catch` should do the trick:
```php
$mailsIds = $mailbox->searchMailbox('UNSEEN');

try {
    $mailbox->markMailsAsRead($mailsIds);
} catch (Exception $ex) {
    die("Failed to mark mails as read due to this error: " . $ex->getMessage());
}

$mail = $mailbox->getMail($value);
```

**Comment by Sebi94nbg** [comment]
Closing this due to no feedback after 2 weeks. Feel free to comment this issue or re-open a new issue.
