### ISSUE TITLE
[BUG] Undefined property: stdClass::$host in reply_to

### ISSUE THREAD

**Issue by StApostol** [barbushin/php-imap#359]
**Environment:**
 - PHP IMAP version: 2.0.3 Judging by the code, the error is observed on the version 3.0.26
 - PHP Version: 7.1
 - Type of execution: CLI

**Describe the bug**
When trying parse email from SMTP server, get the fatal error `Undefined property`

**To Reproduce**
Send header with "Reply-To"
`Reply-To: : User name <user@example.com>`

The used code:
```php
$mailbox = new Mailbox(...
$mailbox->getMail($emailId);
```

**Expected behavior**
Skip empty data.

**Screenshots / Outputs**
```php
array:3 [
  0 => {#2356
    +"mailbox": ""
  }
  1 => {#2357
    +"personal": "User name"
    +"mailbox": "user"
    +"host": "example.com"
  }
  2 => {#2359}
]
```

**Additional context**
Why for other fields entered check for the presence of the host, but not here
https://github.com/barbushin/php-imap/blob/3.0.26/src/PhpImap/Mailbox.php#L893

**Comment by Sebi94nbg** [comment]
Thanks for reporting this issue! I'll check the entire code as soon as possible and update all conditions to the same logic to avoid such issues in future.

**Comment by Sebi94nbg** [comment]
I've committed a fix (see reference above).

I'll release a new version with this fix soon.
