### ISSUE TITLE
Use connection info in $this->imapPath by function

### ISSUE THREAD

**Issue by xBitsSec** [barbushin/php-imap#360]
## Mailbox.php

In my case i will only define the connection info for imap_open without a defined folder. In this case will brake the functions 'switchMailbox, checkMailbox, crateMailbox, deleteMailbox, renameMailbox, subscribeMailbox and unsubscribeMail'.

The direct usage of $this->imapPath in this functions generate an error, if the connection info absolute without an sub path. In normal case and access level can the user only change the folder in the mailbox.

But my quick solution was, to fix this with an additional function, the will generate a correct path. I replace this in the functions, was described above. In the function switchMailbox if the logic more sensible, reopen is only needed, if a connection info in the string, on else only the imapPath will modified.

I hope you can use this code snipets/changes :)

Here some screenshots and the zip file with the modified Mailbox.php

![image](https://user-images.githubusercontent.com/27640321/60569974-d8296400-9d70-11e9-9a2a-8af5f72e572e.png)
![image](https://user-images.githubusercontent.com/27640321/60569978-dcee1800-9d70-11e9-9e06-7ac7d4af22b9.png)
![image](https://user-images.githubusercontent.com/27640321/60569990-e11a3580-9d70-11e9-8153-548482ac59b2.png)
![image](https://user-images.githubusercontent.com/27640321/60569994-e4adbc80-9d70-11e9-828b-a80adfdffe19.png)

[Mailbox.php.zip](https://github.com/barbushin/php-imap/files/3353579/Mailbox.php.zip)

**Comment by Sebi94nbg** [comment]
So, this is an improvement, right? Because I didn't really get, what you want with your issue here. Or is this a bug?

Please always provide some example codes, your current and expected result. This helps a lot to understand the issue.

Feel free to create a new pull request with your changes. Then we can review, test and merge this. :)

**Comment by Sebi94nbg** [comment]
I've now checked your attached code and tested it. Looks good.

I've implemented it as an improvement. Thanks for sharing your improvement! :)

I'll release a new version with this change soon.
