### ISSUE TITLE
textHtml is empty when attaching an image

### ISSUE THREAD

**Issue by jegudin** [barbushin/php-imap#364]
Faced a problem: when sending a letter with text and image attachment. The image is saved, and the text of the letter is empty.

In the process of studying, I found out that if the image is inserted directly into the text of the letter, then everything is fine. However, if the image is simply attached, the text of the letter is missing.

Studying the code made such an edit  (Mailbox.php, line 1009).
It was:
`$this->initMailPart($mail, $subPartStructure, $partNum, $markAsSeen);`
It became:
`$this->initMailPart($mail, $subPartStructure, $partNum.'.'.($subPartNum + 1), $markAsSeen);`

Apologize for my bad english

**Comment by Sebi94nbg** [comment]
Might be related to #358.

**Comment by sharevb** [comment]
As part of developping a mailing group system in my WordPress plugin, I encountered this problem too, with Gmail "multipart/related" kind of embedding of emails sent. I found here [some explaination](https://www.electrictoolbox.com/php-imap-message-parts/) of the need to flatten parts and I did a quick (and very dirty in `vendor` composer managed folder for testing purpose) integration in this [commit](https://github.com/comptoirdesappli/amapress/commit/3a73ffcdd0677c45922d1fbb8a7d231fb5dbcae0) of my plugin.

Hope this can help

**Comment by sharevb** [comment]
Just made a pull request #365

**Comment by Sebi94nbg** [comment]
Thanks! Seems to fix these kind of issues. :)

I'll release a new version with your fix soon.
