### ISSUE TITLE
[BUG] Fatal error in php 5.6

### ISSUE THREAD

**Issue by hyncica** [barbushin/php-imap#369]
**Environment (please complete the following information):**
 - PHP IMAP version: 3.0.27
 - PHP Version: 5.6.33
 - Type of execution: CLI

**Describe the bug**
The function added in commit d26d8e4444eec169fae1e16aaffcb99b2e8d8160 uses type hinting for primitive types. This was only added in php 7.0 but the composer.json specifies php 5.6 as minimal requirement allowing the installation of version that doesn't work in PHP 5.6 environment.

**To Reproduce**
Run the PHP IMAP version 3.0.27 with PHP 5.6 environment.

The used code:
```php
    protected function createMailboxInstance()
    {
        $mailbox = new \PhpImap\Mailbox(
            '{' . $this->server . '}' . $this->mailboxFolder,
            $this->username,
            $this->password,
            $this->ensureAttachmentFolder(),
            $this->encoding
        );

        $mailbox->setAttachmentsIgnore($this->ignoreAttachments);
        return $mailbox;
    }

  $this->mailbox = $this->createMailboxInstance();
  $ids = $this->mailbox->searchMailbox();
```

**Screenshots / Outputs**
PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in D:\Projects\nemovitosti\vendor\php-imap\php-imap\src\PhpImap\Mailbox.php on line 1405
PHP Compile Error 'yii\base\ErrorException' with message 'Default value for parameters with a class type hint can only be NULL'

**Comment by Sebi94nbg** [comment]
Thank for this bug report! This explains, why PHP 5.6 failed in Travis. :)

I've already committed the fix (see above). I'll release a new version soon.
