### ISSUE TITLE
[Feature Request] New mail id when moving mails

### ISSUE THREAD

**Issue by ScreamingDev** [barbushin/php-imap#373]
Moving mails makes imap copy the mail to the other location and then delete the original.
This leads to a changed mail id and without knowing it there is no possibility to continue.
Therefor the move_mail method could return the new mail id.

**Comment by Sebi94nbg** [comment]
The PHP function [imap_mail_move()](https://www.php.net/manual/de/function.imap-mail-move.php) is unfortunately only returning `true` (success) or `false` (error). Thus, it can't return the new mail id.

**Comment by ScreamingDev** [comment]
Thus, the package which makes using the IMAP extension easier neither likes to solve this?
I am confused.
