### ISSUE TITLE
[BUG] You can not see the files in the Cyrillic alphabet

### ISSUE THREAD

**Issue by Sa1ch** [barbushin/php-imap#384]
- PHP IMAP version: 3.0.30
 - PHP Version: 7.3.7
 - Type of execution: Web Server

Hello! my letter has files with Russian names and I can not download them
![image](https://user-images.githubusercontent.com/28288185/65420473-74707d80-de2b-11e9-9d03-83f09f3129d6.png)

script defines only 2 files:
Pravila_OSAGO.pdf AND Pamyatka-OSAGO.pdf 

added later:
print the parameters $partStructure->parameters

`
array(1) {
--
  | [0]=>
  | object(stdClass)#43 (2) {
  | ["attribute"]=>
  | string(4) "name"
  | ["value"]=>
  | string(17) "Pravila_OSAGO.pdf"
  | }
  | }
  | array(1) {
  | [0]=>
  | object(stdClass)#45 (2) {
  | ["attribute"]=>
  | string(4) "name"
  | ["value"]=>
  | string(18) "Pamyatka-OSAGO.pdf"
  | }
  | }
  | array(1) {
  | [0]=>
  | object(stdClass)#47 (2) {
  | ["attribute"]=>
  | string(5) "name*"
  | ["value"]=>
  | string(221) "utf-8''%D0%97%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BE%20%D0%B7%D0%B0%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B8%20%D0%B4%D0%BE%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D0%B0%20%D0%9E%D0%A1%D0%90%D0%93%D0%9E.pdf"
  | }
  | }
  | array(1) {
  | [0]=>
  | object(stdClass)#49 (2) {
  | ["attribute"]=>
  | string(5) "name*"
  | ["value"]=>
  | string(74) "utf-8''%D0%9F%D0%BE%D0%BB%D0%B8%D1%81%20%D0%9E%D0%A1%D0%90%D0%93%D0%9E.pdf"
  | }
  | }

`

--
translated through an interpreter Google translator

**Comment by Sebi94nbg** [comment]
Is it possible for you to send us a test email to "php-imap [AT] outlook [DOT] com" with which we can debug this issue better?

**Comment by Sa1ch** [comment]
sent by 1274_aliluev_st@ruautoblog.ru

**Comment by Sebi94nbg** [comment]
Thanks. I've quickly tested it and it seems to work fine with the current latest code from the `develop` branch:

```bash
> dir .\files\

    Verzeichnis: D:\Sebastian\git\php-imap\files

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12.11.2019     17:24         491109 144_13097f3bfd8b6cf4eac0baed09172a369c928efe_Pravila_OSAGO.pdf
-a----       12.11.2019     17:24         213911 144_87c44d3aa65d4177f5c83940bb9dba37264d5a60_Заявление_о_заключении_договора_ОСАГО.pdf
-a----       12.11.2019     17:24        1118631 144_9245f87993888ba6a02f3f1554f4906e589f9df8_PamyatkaOSAGO.pdf
-a----       12.11.2019     17:24         339102 144_b11bc833b0f9fc43f581ea6dcf788e04126a1f8d_Полис_ОСАГО.pdf
-a----       12.11.2019     17:24           4810 144_b2e4b285c8dfbe3734331199fc7f97763100fc21_Полис_ОСАГО.sgn
```

I'll close this issue for now. I'll release a new version in the next minutes. Please test this then again and feel free to comment or reopen this issue, when you still face this issue.
