### ISSUE TITLE
[BUG] $mail->textPlain (and $mail->textHtml) has concatenated attachment's contents

### ISSUE THREAD

**Issue by akozeka** [barbushin/php-imap#390]
**Environment:**
 - PHP IMAP version: 3.0.30

**Describe the bug**
When mail has text file attached the attachment's contents are concatenated to mail body text (and the same effect for mail body html text if html file is attached).

**To Reproduce**
Example email contents:
```
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="------------050DCCD6987E043DBADFA5A4"

This is a multi-part message in MIME format.
--------------050DCCD6987E043DBADFA5A4
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit

Text attachment


--------------050DCCD6987E043DBADFA5A4
Content-Type: text/plain; charset=UTF-8;
 name="Attachment.txt"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="Attachment.txt"

MQ0KMg0KMw0KNA0KNQ0KNg0KNw0KOA0KOQ==
--------------050DCCD6987E043DBADFA5A4
```

**Expected behavior**
textPlain variable should have text: Text attachment
but has: Text attachment1
2
3
4
5
6
7
8
9

**Additional context**
No bug in version 3.0.1

**Comment by Sebi94nbg** [comment]
@akozeka Do you still have this issue with the current version 3.0.31?

**Comment by akozeka** [comment]
@Sebi94nbg Seems issue is fixed for .txt files but still active for .html files.
How to reproduce:

```
--------------B42AF503298E47E1A15BB011
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body text="#000000" bgcolor="#FFFFFF">
    <p><b>HTML</b></p>
    <p>attachment</p>
    <p><br>
    </p>
  </body>
</html>

--------------B42AF503298E47E1A15BB011--
Content-Type: text/html; charset=UTF-8;
 name="Attachment.html"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="Attachment.html"
```

Contents of Attachment.html are concatenated to textHtml property (in 3.0.31).

**Comment by Sebi94nbg** [comment]
@akozeka is it possible, that you can send us such a test email to "php-imap [AT] outlook [DOT] com", that we can debug it directly with this one?

**Comment by akozeka** [comment]
@Sebi94nbg Sure, sent.

**Comment by Sebi94nbg** [comment]
Thanks for the sample mail!

I think, I've fixed this issue with the above commit. I've tested it with your and some other emails. Seems to be fixed.

I'll release a new version in the next minutes. Feel free to comment or reopen this issue later. :)
