### ISSUE TITLE
[BUG] Wrong charset, conversion from 'X-UNKNOWN'

### ISSUE THREAD

**Issue by tito10047** [barbushin/php-imap#393]
**Environment:**
 - PHP IMAP version: 3.0.30
 - PHP Version: 7.2.12
 - Type of execution: CLI

**Describe the bug**
iconv(): Wrong charset, conversion from `'X-UNKNOWN' to 'UTF-8//IGNORE'` is not allowed in ...\vendor\php-imap\php-imap\src\PhpImap\Mailbox.php on line 1225

**To Reproduce**
See the code below and the attached email.

The used code:
```php
$mailbox = new \PhpImap\Mailbox($imapPath, $login, $password, sys_get_temp_dir());
$mail = $mailbox->getMail($mailId);
var_dump($mail->textPlain);
```

[email.txt](https://github.com/barbushin/php-imap/files/3767076/email.txt)

when encoding crashes then `$mail->textPlain` return empty string.

***Second problem***
in Mailbox:1227 not throw exception because `iconv` return in this case `false` and `isset(false)` return `true`
```php
if (!isset($convertedString)) {
    throw new Exception('Mime string encoding conversion failed');
}
```

**Comment by Sebi94nbg** [comment]
Improved the code to try the conversion and if it fails, it will return the original value.

Released in version [3.0.31](https://github.com/barbushin/php-imap/releases/tag/3.0.31).
