### ISSUE TITLE
[Feature Request] Return original string instead of exception

### ISSUE THREAD

**Issue by tito10047** [barbushin/php-imap#397]
**Is your feature request related to a problem? Please describe.**
here also return original string instead of exception.
In mailbox I want parse all emais, but when library throw exception I cant do anything with wrong email and must skip it.

https://github.com/barbushin/php-imap/blob/0c65ac8f3e273b20e6d20ba2c479608a8fd8c364/src/PhpImap/Mailbox.php#L1286

**Comment by Sebi94nbg** [comment]
Fixed in the `develop` branch. I'll include this fix in the next release.
