### ISSUE TITLE
[BUG] Issue with decodeMimeStr() when value is only a whitespace

### ISSUE THREAD

**Issue by felix-goecking** [barbushin/php-imap#400]
The issue occurs for me in the following line:
`            $header->fromName = (isset($head->from[0]->personal) and !empty($head->from[0]->personal)) ? $this->decodeMimeStr($head->from[0]->personal, $this->getServerEncoding()) : ((isset($head->from[1]->personal) and (!empty($head->from[1]->personal))) ? $this->decodeMimeStr($head->from[1]->personal, $this->getServerEncoding()) : null);
`

The value of $head->from[0]->personal is only an whitespace character (" "). Thus the check for isset and empty is ok, but in the decodeMimeStr()-method the given value is trimmed so that the value is empty. Thus an exception is thrown!

Here the value of the head->from array:
`array (
  0 => 
  stdClass::__set_state(array(
     'personal' => ' ',
     'mailbox' => 'john.doe',
     'host' => 'gmx.net',
  )),
)`

**Comment by Sebi94nbg** [comment]
Fixed in the `develop` branch. I'll include this fix in the next release.
