### ISSUE TITLE
[Feature Request] Improve handling of invalid MIME types

### ISSUE THREAD

**Issue by twmobius** [barbushin/php-imap#403]
I came against an issue with an email where the subject and from headers where using ISO-8859-X encoding without the proper MIME encoding `=?iso-8859-X` 

The `convertStringEncoding()` method trusts blindly the charset returned from `imap_mime_header_decode()` and if the charset is `default` it returns the string as is, expecting it to be a valid UTF-8 string.

However there are clients out there which sent invalid emails (unfortunately). 

I am opening this ticket to discuss if there is a better way to handle this.

Currently to avoid having similar issues, I extended Mailbox and instead of simply trusting the result from `imap_mime_header_decode` in `default` or `ascii` charsets I pass the string via the `mb_detect_encoding()` to verify that it is actually ASCII, or default.

Something along the following lines (for example to match ISO-8859-15):

```
public function convertStringEncoding($string, $fromEncoding, $toEncoding)
{
  if (!$string || $fromEncoding == $toEncoding) {
    return $string;
  }

  $mbLoaded = \extension_loaded('mbstring');

  if ( preg_match('/default|ascii/i', $fromEncoding) ) {
    if( !$mbLoaded ) {
      return $string;
    }

    $encoding = mb_detect_encoding($string, [
      'ASCII', 'ISO-8859-15', 'UTF-8'
    ]);

    if( $encoding == 'ISO-8859-15' ) {
      $string = mb_convert_encoding($string, $toEncoding, 'ISO-8859-15');
      return $string;
    }

    return $string;
  }
  ...
}
```

However this is not the best option since a different charset may appear which `mb_detect_encoding` will not properly detect when using a fixed array of encodings. 

Does anyone have any ideas on how mail clients detect such errors and correct them?

**Comment by Sebi94nbg** [comment]
Thanks for opening this discussion topic @twmobius!

Do you maybe have an example, which we can use for our PhpUnit tests? https://github.com/barbushin/php-imap/blob/master/tests/unit/MailboxTest.php#L486-L516

**Comment by Sebi94nbg** [comment]
@twmobius do you have an example, which we can add to our PHPUnit tests?

**Comment by twmobius** [comment]
@Sebi94nbg I cannot post the specific email source publicly sorry, however I am guessing it's easy to reproduce. Just add an ISO-8859-X encoded string in the Subject: header and pass it through the `imap_mime_header_decode()` method. 

`imap_mime_header_decode` will return charset to be `default`. The default however in this case is not UTF-8.

**Comment by Sebi94nbg** [comment]
I only wanted a few test strings - not the entire email or it's header. Only the test string. :)

If you can't provide such strings, I'll search some.

**Comment by twmobius** [comment]
I could get one in ISO-8859-7 (Greek) quickly. 

[iso-8859-7.txt](https://github.com/barbushin/php-imap/files/3910268/iso-8859-7.txt)

**Comment by Sebi94nbg** [comment]
Thanks! I'll check this as soon as possible.

**Comment by Sebi94nbg** [comment]
I believe, we can remove the method `Mailbox::convertStringEncoding($string, $fromEncoding, $toEncoding)` and replace it with `Mailbox::decodeMimeStr($string)`.

I don't see any reason, why we should use this method anywhere. Or we merge these two methods?

How do you think about this, @bapcltd-marv?

**Comment by bapcltd-marv** [comment]
reducing code used is always a good thing :)

**Comment by Sebi94nbg** [comment]
Ok, then let's merge `Mailbox::convertStringEncoding($string, $fromEncoding, $toEncoding)` into `Mailbox::decodeMimeStr($string)`. :)

This is only a very small change. I'm currently working on a different project, but I can do that later. :)

**Comment by Sebi94nbg** [comment]
Ok, done. See commit [e40d8](https://github.com/barbushin/php-imap/commit/e40d88dadd8001f431cd7c578df67500af1d2805).

I've not merged it. I've simply removed the entire function, because it doesn't make sense to convert specific strings to a different encoding - this can break the expected string.

**Comment by Sebi94nbg** [comment]
Travis CI seems to be happy. Closing this issue. :)
