### ISSUE TITLE
is there/should there be a folderPath attribute to IncomingMail data model?

### ISSUE THREAD

**Issue by yuliangruan** [barbushin/php-imap#406]
**Environment (please complete the following information):**
 - PHP IMAP version: 3.0.33
 - PHP Version: 7.2.24
 - Type of execution: daemon

when pulling mailbox, can do getListingFolders() and searchMailBox() to get id's and then looping to getMail(),   the returned mail/message object doesn't identify which folder it came from from getListingFolders.     I could triple nested loop but wondering if there's better way

```
forEach (getListingFolders() as $folder) 
  forEach (searchMailBox($folder)) as $mailIds)
    foreach ($mailsIds as $mailId)
      getMail($mailId)
    
```

**Comment by yuliangruan** [comment]
hmm apparently can't move between folders while connected to do a in-folder search.   only way i could see is to reconnect under the new folder.   is there a better way?

**Comment by Sebi94nbg** [comment]
I've added two new properties to the `IncomingMailHeader`:
- `imapPath` (eg. `{imap.gmail.com:993/imap/ssl}INBOX`)
- `mailboxFolder` (eg. `INBOX` )

You can now easily access those properties like this:

```php
<?php
    declare(strict_types=1);

    require_once __DIR__.'/../vendor/autoload.php';

    use PhpImap\Exceptions\ConnectionException;
    use PhpImap\Mailbox;

    $mailbox = new Mailbox(
        '{imap.gmail.com:993/imap/ssl}INBOX', // IMAP server and mailbox folder
        'some@gmail.com', // Username for the before configured mailbox
        '*********', // Password for the before configured username
        __DIR__, // Directory, where attachments will be saved (optional)
        'US-ASCII' // Server encoding (optional)
    );

    foreach($mailbox->getListingFolders() as $folder) {
        $mailbox->switchMailbox($folder);
        echo "Scanning folder '".$folder."'...\n";

        $mailIds = $mailbox->searchMailBox('ALL');
        foreach ($mailIds as $mailId) {
            $mail = $mailbox->getMail($mailId);
            echo $mail->mailboxFolder."\n";
        }
    }
```

I hope this solves your issue. I'll close this ticket for now. Feel free to comment / reopen it, when it doesn't solve your issue.

The above changes are currently only in `develop` branch. They will get merged into `master` and released soon.
