### ISSUE TITLE
[BUG] Clearing error buffer before throwing an exception

### ISSUE THREAD

**Issue by slischka** [barbushin/php-imap#407]
**Environment:**
 - PHP IMAP version: 3.0.33
 - PHP Version: 7.1.33
 - Type of execution: CLI

**Clearing error buffer before throwing an exception**
Hello, I am using Tracy with all error reporting. And if user provides invalid credentils, the mailobx throws and `Exception` for example `Can not authenticate to IMAP server: [AUTHENTICATIONFAILED] Invalid credentials`

The problem starts here, because the imap error buffer is not cleared here and when the proces ends. Tracy logs an Notice. 

I fixed it with this code 
```php
try {
	return $this->getMailbox()->searchMailbox($criteriaString);
} catch (\Throwable $e) {
	@imap_errors();

	throw $e;
}
```

But it can be fixed inside `initImapStream` function. Just simply add `@imap_errors();` on line `src/PhpImap/Mailbox.php:410`.

```php
protected function initImapStream()
{
	foreach ($this->timeouts as $type => $timeout) {
		$this->imap('timeout', [$type, $timeout], false);
	}

	$imapStream = @imap_open($this->imapPath, $this->imapLogin, $this->imapPassword, $this->imapOptions, $this->imapRetriesNum, $this->imapParams);

	if (!$imapStream) {
		$lastError = imap_last_error();
                @imap_errors(); //cleare the buffer

		if (!empty(trim($lastError))) {
			throw new Exception('IMAP error: '.$lastError);
		} else {
			throw new Exception('Connection error: Unable to connect to '.$this->imapPath);
		}
	}

	@imap_errors();

	return $imapStream;
}
```

But I dont know if this is intended. 

Thanks.

**Comment by Sebi94nbg** [comment]
I've updated the code. This change will be included in the next release.
