### ISSUE TITLE
Attachment name error

### ISSUE THREAD

**Issue by zubkab** [barbushin/php-imap#409]
Environment:
 - PHP IMAP version: 3.0.33
 - PHP Version: 7.1.26
 - Type of execution: Web Server

Describe the bug
class Mailbox
function downloadAttachment

code:
elseif (!isset($params['filename']) or empty(trim($params['filename'])) && (!isset($params['name']) or empty(trim($params['name'])))) 

Operator Precedence
correctly:
elseif ((!isset($params['filename']) or empty(trim($params['filename']))) && (!isset($params['name']) or empty(trim($params['name']))))

**Comment by Sebi94nbg** [comment]
I've updated the code. The change will be included in the next release.
