### ISSUE TITLE
[BUG] property filePath keeps original value and attachment not saved correctly

### ISSUE THREAD

**Issue by georgehristov** [barbushin/php-imap#414]
**Environment:**
 - PHP IMAP version: 3.0.11
 - PHP Version: 7.0.33
 - Type of execution: Web Server

**Describe the bug**
When using `setFilePath` method only the `file_path` property value is changed. The `filePath` property is used when saving the file to disk which results in saving the file to undesired location.

**To Fix**
Change `setFilePath` method to (presumably keeping both properties is for backward compatibility)
```
public function setFilePath($filePath)
{
   $this->filePath = $this->file_path = $filePath;
}
```

**Comment by Sebi94nbg** [comment]
Closing this, because php-imap v3.0.11 is already very old. Please update your library

Closing this issue for now. Feel free to comment or reopen this issue if you still should face this issue.
