### ISSUE TITLE
query re: Mailbox::getMailMboxFormat()

### ISSUE THREAD

**Issue by bapcltd-marv** [barbushin/php-imap#427]
**Environment (please complete the following information):**
environment not applicable

**Your Text**
I'm about 90% sure (i.e. not totally) that https://github.com/barbushin/php-imap/blob/9c1469c053d4f1473cbd3648fc7ae363f6b3aace/src/PhpImap/Mailbox.php#L1400 should be `$option | FT_PREFETCHTEXT`, as the `&&` results in a bool, which when passed non-strictly to the `int $options` param of imap_fetchheader would result in a 1, meaning it's always stuck at `FT_UID`.

**Comment by Sebi94nbg** [comment]
Thanks for all the PR and this feedback!

I'll check, merge and test them all as soon as possible. Hopefully this weekend.

**Comment by Sebi94nbg** [comment]
Can we close that @bapcltd-marv ?

**Comment by bapcltd-marv** [comment]
yup
