### ISSUE TITLE
Parsing forwared mails

### ISSUE THREAD

**Issue by vzhilov** [barbushin/php-imap#43]
Works great but if I get forwarded message it saves the HTML message body to attachment folder. If an actual attachment with html will be attached also it couldn't be possible to undertand what is attahcment and what is message body.

**Comment by escobar022** [comment]
Working on this! Sub parts are very interesting, and not easily assembled.

**Comment by barbushin** [comment]
@escobar022 That's great, Adnres! :+1:

**Comment by escobar022** [comment]
So i figured this out, but it is necessary to have the php mbstring extension and php mailparse extension, thoughts?

**Comment by barbushin** [comment]
@escobar022 Thanks for this research, Adnres, but we can't ask users to install any extension, sometime it's impossible. If this feature will be implemented in php-imap, it should be implemented without any extension, as all other php-imap features.

**Comment by escobar022** [comment]
You are right! I will find a way without it as I'm only issuing it to set a file name

**Comment by escobar022** [comment]
I was able to do without the mailparser! Will send a pull request.

**Comment by barbushin** [comment]
Cool, man! You did a great job :+1:

**Comment by maiklez** [comment]
Any idea with subparts?

**Comment by Sebi94nbg** [comment]
> I was able to do without the mailparser! Will send a pull request.

@escobar022 can you please provide the solution here as code snippet or PR? Would be very great! Thanks! :)

**Comment by Sebi94nbg** [comment]
I've just forwarded myself a HTML email and I could parse it without getting it saved as attachment.

Is anyone still facing this issue with the current latest version 3.0.17?

What should be the expected result and how does it look like right now?

**Comment by Sebi94nbg** [comment]
Closing this, since nobody replied with an expected result and for me it's working as expected.
