### ISSUE TITLE
query re: param types

### ISSUE THREAD

**Issue by bapcltd-marv** [barbushin/php-imap#432]
**Environment (please complete the following information):**
n/a

**Your Text**
Just wondering what the parameter type is intended to be on the following methods:
* Mailbox::markMailAsRead()
* Mailbox::markMailAsUnread()
* Mailbox::markMailAsImportant()

**Comment by Sebi94nbg** [comment]
I believe a `string` since it can be a random ID (string) or an incremental number (integer). See https://github.com/barbushin/php-imap/blob/master/src/PhpImap/Mailbox.php#L670 .

**Comment by Sebi94nbg** [comment]
@bapcltd-marv Thank you very much for all your commits and the time you put in! Unfortunately I'm a bit busy at the moment, as I'm looking for a new apartment. But soon I should have more time again and then I can work more here. Thanks again for all the awesome improvements and changes!

**Comment by bapcltd-marv** [comment]
you're welcome :)

**Comment by bapcltd-marv** [comment]
further investigation suggests it should be an int; it looks like it's only the range/sequence parameters that need to be strings.

**Comment by Sebi94nbg** [comment]
@bapcltd-marv Do you know, if there is any solution to fix these warnings in Travis CI?

`Warning: constant(): Couldn't find constant OPENTIMEOUT in <file name>.`

I would like to fix these in order to keep the Travis CI output clean, but I didn't find a solution yet.

**Comment by Sebi94nbg** [comment]
Another point: You changed, how IMAP is being tested - with a fake server, right? Does this also support 2FA using OAuth?

**Comment by bapcltd-marv** [comment]
the change from `OPENTIMEOUT` to `constant('OPENTIMEOUT ')` was to suppress a warning in the phpunit output, re: https://3v4l.org/EL2Sv
> Warning: Use of undefined constant OPENTIMEOUT - assumed 'OPENTIMEOUT' (this will throw an Error in a future version of PHP)

To fix them, I'd be asking where the constant gets defined, as it's not in the codebase?

> Another point: You changed, how IMAP is being tested - with a fake server, right? Does this also support 2FA using OAuth? See #411.

nope, actual server. slapping some credentials into travis secrets so they don't need to be hardcoded or stored in the repo as encrypted strings.

It could probably do oauth, but you'd need to add some additional environment variables for travis to pick up the secrets from & for the test to add an additional test case.

**Comment by bapcltd-marv** [comment]
> It could probably do oauth, but you'd need to add some additional environment variables for travis to pick up the secrets from & for the test to add an additional test case.

specifically, https://github.com/barbushin/php-imap/blob/1f64151820dbcf3d6c6133bc7099c4cb54a59e48/tests/unit/LiveMailboxTest.php#L27 and https://github.com/barbushin/php-imap/blob/1f64151820dbcf3d6c6133bc7099c4cb54a59e48/tests/unit/LiveMailboxTest.php#L58 is what would need modifying.

**Comment by Sebi94nbg** [comment]
Thanks! `OPENTIMEOUT` and so on are predefined constants from PHP for the`imap_` functions. See https://www.php.net/manual/de/function.imap-timeout.php

**Comment by bapcltd-marv** [comment]
> Thanks! `OPENTIMEOUT` and so on are predefined constants from PHP for the`imap_` functions. See https://www.php.net/manual/de/function.imap-timeout.php

seems to only be `IMAP_OPENTIMEOUT`, not `OPENTIMEOUT` ?

**Comment by Sebi94nbg** [comment]
Yes, with `IMAP_` as prefix.

> One of the following: IMAP_OPENTIMEOUT, IMAP_READTIMEOUT, IMAP_WRITETIMEOUT, or IMAP_CLOSETIMEOUT.

**Comment by Sebi94nbg** [comment]
@bapcltd-marv How many more changes do you want to make? I would like to check and close the open tickets this week and then release a new version as soon as possible.

**Comment by bapcltd-marv** [comment]
unless I stumble across new bugs, this week will be mostly spent on integrating the patches back into the downstream fork.

**Comment by Sebi94nbg** [comment]
I've commented #465.

I've some test emails in my inbox, which were multiple times reported here, so I'll test all changes from the develop branch against those to make sure, that we don't break anything again. :)

And then we hopefully can merge the develop branch into master and release a new version by end of this week. :)

**Comment by bapcltd-marv** [comment]
> I'll test all changes from the develop branch against those to make sure

are there any test cases you have that could be used for fleshing out `LiveMailboxTest` as per #448 fix? https://github.com/barbushin/php-imap/blob/8774b07117ecf69c4fe585dba81de883d642af66/tests/unit/LiveMailboxTest.php#L227 https://github.com/barbushin/php-imap/blob/8774b07117ecf69c4fe585dba81de883d642af66/tests/unit/LiveMailboxTest.php#L733

**Comment by Sebi94nbg** [comment]
Most of the time just encoding things or missing attachments. I would need to double-check those emails again.

I can share the mail credentials with you. It's a Microsoft mail account - can only receive emails, not send. Simply write me a short email (see my profile) and I'll provide you the credentials in order to check those emails in order to implement some tests or something.

**Comment by bapcltd-marv** [comment]
that'll need to be deferred until I've the time free :D

**Comment by bapcltd-marv** [comment]
p.s. I should note that the live mailbox tests don't currently send emails, they're just appending composed messages to a mailbox.

**Comment by bapcltd-marv** [comment]
> that'll need to be deferred until I've the time free :D

tbh, I'd prefer to provide guidance on fleshing out the live mailbox tests
