### ISSUE TITLE
Uncaught Exception: IMAP error: Can not authenticate to IMAP server

### ISSUE THREAD

**Issue by AdamCZ001** [barbushin/php-imap#440]
Sometimes it reports an error log

`[23-Jan-2020 10:01:28 Europe/Prague] PHP Fatal error:  Uncaught Exception: IMAP error: Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (authenticate) in /vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:413
Stack trace:
#0 /vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(385): PhpImap\Mailbox->initImapStream()
#1 /vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(324): PhpImap\Mailbox->initImapStreamWithRetry()
#2 /vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(1437): PhpImap\Mailbox->getImapStream()
#3 /vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(550): PhpImap\Mailbox->imap('search', Array)
#4 /funkce.php(2394): PhpImap\Mailbox->searchMailbox('ALL')
#5 ajax_adam.php(969): stahnoutNoveEmaily(NULL)
#6 {main}
  thrown in /vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 413`

**Comment by Sebi94nbg** [comment]
Please always provide some code and some information like the used library version.

It's very hard to support you, when you only provide an error message without any further information.

Please see the getting started wiki page for an example: https://github.com/barbushin/php-imap/wiki/Getting-Started

If possible, you should always use the `try-catch` logic to avoid such errors.

**Comment by AdamCZ001** [comment]
Updating php-imap/php-imap (3.0.6 => 3.0.33): Downloading (100%)
