### ISSUE TITLE
[BUG] decodeMimeStr, encoding windows-1251

### ISSUE THREAD

**Issue by disprog** [barbushin/php-imap#447]
subject содержит заголовок
=?UTF-8?B?0KLQtdGB0YLQvtCy0LDRjyDQt9Cw0LTQsNGH0LA=?=
После вызова decodeMimeStr получается
РўРµСЃС‚РѕРІР°СЏ Р·Р°РґР°С‡Р
Хотя должна получится строка: "Тестовая задача"
Проблема в том, что $toCharset получается UTF-8 (вместо Windows-1251):
```php
  $toCharset = isset($element->charset) && preg_match('/(UTF\-8)|(default)/i', $element->charset) ? 'UTF-8' : $toCharset;
```

**Comment by Sebi94nbg** [comment]
Should be fixed with the last commit (see above). This fix will be included with the next release. It's currently only available in the `develop` branch.
