### ISSUE TITLE
Attachment filtering

### ISSUE THREAD

**Issue by adamkasprzak** [barbushin/php-imap#450]
Hi!

Thank your for this script - it works very well! After some struggle to get each attachment name and extension, I'm using it to differ pdfs from other attachments which has influence on replies to senders and db inserts.

What I miss is the ability to set the file extensions limitation for default script processing to folder. Right now I gett all the junk (including inline images and vcf attached cards) in my folder designated for pdfs only. 

Is there such possibility?

Thanks,
Adam

**Comment by bapcltd-marv** [comment]
filtering emails or filtering `IncomingMail::getAttachments()` ?

**Comment by adamkasprzak** [comment]
filtering attachments, I would like to decide whether to save the attachment or not, based on the extension.

**Comment by bapcltd-marv** [comment]
should be a straightforward `array_filter()` call ?

**Comment by Sebi94nbg** [comment]
Or maybe something like this?
```
<?php
    require_once __DIR__.'/../vendor/autoload.php';
    use PhpImap\Exceptions\ConnectionException;
    use PhpImap\Mailbox;

    $mailbox = new Mailbox(
        '{imap.gmail.com:993/imap/ssl}INBOX', // IMAP server and mailbox folder
        'some@gmail.com', // Username for the before configured mailbox
        '*********' // Password for the before configured username
    );

    try {
        $mail_ids = $mailbox->searchMailbox('UNSEEN');
    } catch (ConnectionException $ex) {
        die('IMAP connection failed: '.$ex->getMessage());
    } catch (Exception $ex) {
        die('An error occured: '.$ex->getMessage());
    }

    foreach ($mail_ids as $mail_id) {
        echo "+------ P A R S I N G ------+\n";

        $email = $mailbox->getMail(
            $mail_id, // ID of the email, you want to get
            false // Do NOT mark emails as seen (optional)
        );

	// Save attachments one by one
	if (!$mailbox->getAttachmentsIgnore()) {
		$attachments = $email->getAttachments();

		foreach ($attachments as $attachment) {
			// Only save PDF files (file name *.pdf; eg. sample.pdf)
			if (! preg_match('/\.pdf$/i', $attachment->name)) {
				continue;
			}

			echo '--> Saving PDF file '.(string) $attachment->name.'...';

			// Set individually filePath for each single attachment
			// In this case, every file will get the current Unix timestamp
			$attachment->setFilePath(__DIR__.'/files/'.\time());

			if ($attachment->saveToDisk()) {
				echo "OK, saved!\n";
			} else {
				echo "ERROR, could not save!\n";
			}
		}
	}
```

I'll close this issue now due to inactivity and no feedback since end of January.

**Comment by Pream-webapps** [comment]
To download specific attachments, use the following snippet
$except = array("rar", "zip", "mp3", "mp4", "mp3", "mov", "flv", "wmv", "swf", "png", "gif", "jpg", "ico", "jpeg", "xls", "xlsx", "pdf	", "bmp", "avi");
 $imp = implode('|', $except);
					 if (!preg_match('/\.('.$imp.')$/', $attachment->name)) {
						 continue;
					 }
