### ISSUE TITLE
how to find multiple messages ?

### ISSUE THREAD

**Issue by nancysavchenko** [barbushin/php-imap#455]
$mails_ids = $mailbox->searchMailbox('TEXT "<671428003.2077041.1570588326824.JavaMail.open-xchange@opme11oxm28aub.bagnolet.francetelecom.fr>"', SE_FREE, "UTF-8");
    $mails_ids = $mailbox->searchMailbox('SUBJECT "Accusé de Réception"', SE_FREE, "UTF-8");

**Comment by Sebi94nbg** [comment]
What exactly do you mean with that? Something like this?

```php
$mails_ids_text = $mailbox->searchMailbox('TEXT "<671428003.2077041.1570588326824.JavaMail.open-xchange@opme11oxm28aub.bagnolet.francetelecom.fr>"', SE_FREE, "UTF-8");
$mails_ids_subject = $mailbox->searchMailbox('SUBJECT "Accusé de Réception"', SE_FREE, "UTF-8");
```

**Comment by nancysavchenko** [comment]
$mailbox = new PhpImap\Mailbox(
    '{adadada.t-online.de:993/imap/ssl}INBOX', 
    'ususususs', 
    'cerofireaaagag93', 
    null,
    'US-ASCII' // force charset different from UTF-8
);

try {
    // Search in mailbox folder for specific emails
    // PHP.net imap_search criteria: http://php.net/manual/en/function.imap-search.php
    // Here, we search for "all" emails
    $mails_ids = $mailbox->searchMailbox('TEXT "<671428003.2077041.1570588326824.JavaMail.open-xchange@opme11oxm28aub.bagnolet.francetelecom.fr>"', SE_FREE, "UTF-8");
   $mails_ids = $mailbox->searchMailbox('TEXT "Your free 30 days of Netflix awaits."', SE_FREE, "UTF-8");
} catch(PhpImap\Exceptions\ConnectionException $ex) {
    echo "IMAP connection failed: " . $ex;
    die();
}

// Switch server encoding
$mailbox->setServerEncoding('UTF-8');

// Loop through all emails
foreach($mails_ids as $mail_id) {
    // Just a comment, to  see, that this is the begin of an email
    // Get mail by $mail_id
    $email = $mailbox->getMail(
        $mail_id, // ID of the email, you want to get
        false // Do NOT mark emails as seen
    );



    echo "from-name: " . (isset($email->fromName)) ? $email->fromName : $email->fromAddress . "<br>";
    echo "from-email: " . $email->fromAddress . "<br>";
    echo "subject: " . $email->subject . "<br>";
    echo "message_id: " . $email->messageId . "<br>";

    if($email->textHtml) {
        echo "Message HTML:\n" . $email->textHtml;
    } else {
        echo "Message Plain:\n" . $email->textPlain;
    }
}

// Disconnect from mailbox
$mailbox->disconnect();


?

**Comment by nancysavchenko** [comment]
> 
> 
> What exactly do you mean with that? Something like this?
> 
> ```
> $mails_ids_text = $mailbox->searchMailbox('TEXT "<671428003.2077041.1570588326824.JavaMail.open-xchange@opme11oxm28aub.bagnolet.francetelecom.fr>"', SE_FREE, "UTF-8");
> $mails_ids_subject = $mailbox->searchMailbox('SUBJECT "Accusé de Réception"', SE_FREE, "UTF-8");
> ```

how to do it ?

> 
> 
> What exactly do you mean with that? Something like this?
> 
> ```
> $mails_ids_text = $mailbox->searchMailbox('TEXT "<671428003.2077041.1570588326824.JavaMail.open-xchange@opme11oxm28aub.bagnolet.francetelecom.fr>"', SE_FREE, "UTF-8");
> $mails_ids_subject = $mailbox->searchMailbox('SUBJECT "Accusé de Réception"', SE_FREE, "UTF-8");
> ```

<?php

require 'vendor/autoload.php';

$mailbox = new PhpImap\Mailbox(
    '{secureimap.t-online.de:993/imap/ssl}INBOX', 
    'reykagagagazan@t-online.de', 
    'cerofiafafre93', 
    null,
    'US-ASCII' // force charset different from UTF-8
);

try {
    // Search in mailbox folder for specific emails
    // PHP.net imap_search criteria: http://php.net/manual/en/function.imap-search.php
    // Here, we search for "all" emails
    $mails_ids = $mailbox->searchMailbox('TEXT "<671428003.2077041.1570588326824.JavaMail.open-xchange@opme11oxm28aub.bagnolet.francetelecom.fr>"', SE_FREE, "UTF-8");
    $mails_ids = $mailbox->searchMailbox('TEXT "Your free 30 days of Netflix awaits."', SE_FREE, "UTF-8");
    // $mails_ids = $mailbox->searchMailbox('ALL');
    // $mails_ids = $mailbox->imap('fetch_overview', '1:2');
} catch(PhpImap\Exceptions\ConnectionException $ex) {
    echo "IMAP connection failed: " . $ex;
    die();
}

// Switch server encoding
$mailbox->setServerEncoding('UTF-8');

// Loop through all emails
foreach($mails_ids as $mail_id) {
    // Just a comment, to  see, that this is the begin of an email
    // Get mail by $mail_id
    $email = $mailbox->getMail(
        $mail_id, // ID of the email, you want to get
        false // Do NOT mark emails as seen
    );



    echo "from-name: " . (isset($email->fromName)) ? $email->fromName : $email->fromAddress . "<br>";
    echo "from-email: " . $email->fromAddress . "<br>";
    echo "subject: " . $email->subject . "<br>";
    echo "message_id: " . $email->messageId . "<br>";

    if($email->textHtml) {
        echo "Message HTML:\n" . $email->textHtml;
    } else {
        echo "Message Plain:\n" . $email->textPlain;
    }
}

// Disconnect from mailbox
$mailbox->disconnect();

**Comment by Sebi94nbg** [comment]
You need to loop over each array:

```php
foreach ($mails_ids_text as $mail_id) { ... }

foreach ($mails_ids_subject as $mail_id) { ... }
```

**Comment by bapcltd-marv** [comment]
@Sebi94nbg this might relate to the IMAP2/IMAP4 issue that https://github.com/barbushin/php-imap/blob/094064bdb74893f4f470dec2c2f7739e7dd1db09/src/PhpImap/Mailbox.php#L2001 was added for.
