### ISSUE TITLE
[BUG] not correct file name in attachement

### ISSUE THREAD

**Issue by tito10047** [barbushin/php-imap#471]
**Environment**
 - PHP IMAP version: 3.0.33
 - PHP Version: 7.2
 - Type of execution: CLI

**Describe the bug**
parse not correct attachement name

**To Reproduce**
I can send original email only to private email because has restricted data

[on this line](https://github.com/barbushin/php-imap/blob/master/src/PhpImap/Mailbox.php#L1212)
```
public function downloadAttachment(....)
    ....
    elseif ((!isset($params['filename']) or empty(trim($params['filename']))) && (!isset($params['name']) or empty(trim($params['name'])))) {
    .....
```
you missed here one parenthesis. not
`(!isset($params['filename']) or empty(trim($params['filename'])) && (..)` 
but 
`((!isset($params['filename']) or empty(trim($params['filename']))) && (..)`

If you can fix it and create new fix tag. We use it in production and this bug destroys us attachments

**Comment by tito10047** [comment]
I see, you have already fixed it in develop. but can you fixed it in productuion and create new tag?
or when you will publish develop?
we have big problem with this bug

thanks

**Comment by Sebi94nbg** [comment]
Thanks for creating this issue and the information, that it's already fixed.

I'll check this week the open issues and test all the changes from @bapcltd-marv. After that I'll merge those changes into `master` and release a new version including your required fix.

**Comment by tito10047** [comment]
Hi,
Any plan to new release? Im still waiting to release this fix

**Comment by tito10047** [comment]
thanks for release this bug. I close this thread
