### ISSUE TITLE
query re: code coverage reporting

### ISSUE THREAD

**Issue by bapcltd-marv** [barbushin/php-imap#472]
**Environment (please complete the following information):**
travis + code climate

**Your Text**
I'm not overly familiar with code climate, this repo / our fork being the first time I've delved into it.

One thing I'm noticing is that code climate seems to report noticeably different coverage than coveralls when using the same coverage files:
* [24% on code climate](https://codeclimate.com/github/bapcltd-marv/php-imap)
* [53% on coveralls](https://coveralls.io/github/bapcltd-marv/php-imap)

Is there a config thing that I'm missing?

**Comment by Sebi94nbg** [comment]
That's a good question. I've only implemented a basic version. I haven't checked that further. We also can remove Code Climate and use Coveralls, if you have more / better experience with this tool.

I just googled for such a tool and used the first best one to get some statistics. :)

**Comment by bapcltd-marv** [comment]
some of the metrics code climate provides can be useful, there's no reason not to use both (and it's relatively straightforward to use both tools).

**Comment by Sebi94nbg** [comment]
Can we close that @bapcltd-marv ?

**Comment by bapcltd-marv** [comment]
sure, just take your pick of which coverage badge to use or use both ?

**Comment by Sebi94nbg** [comment]
We can add both. :)

Code Climate is currently broken.
