### ISSUE TITLE
[BUG] subject 中文乱码

### ISSUE THREAD

**Issue by sanjiwork** [barbushin/php-imap#479]
**Environment (please complete the following information):**
 - PHP Version: [PHP 7.3.13]

我想获取中文mail subject时, 会有乱码情况, 调整class Mailbox-> getMailHeader 第910行源码, 展示正常。

想询问是不是因为中文字符断行问题, 影响转码?

----
MIME header subject:
> =?utf-8?b?KOS6i+S7tuWNlee8luWPtzpURVNUQS0xMTExMTEpKOmAmuaKpSnl?= =?utf-8?b?haXlj6PmnInpmYznlJ/kuro=?=

Real mail subject:
> (事件单编号:TESTA-111111)(通报)入口有陌生人

Code output:
> (事件单编号:TESTA-111111)(通报)???口有陌生人

---

Mailbox.php->line: 910

```
$header->subject = (isset($head->subject) and !empty(trim($head->subject))) ? $this->decodeMimeStr($head->subject, $this->getServerEncoding()) : null;
```

change to :
```
$header->subject = (isset($head->subject) and !empty(trim($head->subject))) ? $this->decodeMimeStr(preg_replace('/\?\= \=\?'.$this->getServerEncoding().'\?B\?/i','',$head->subject), $this->getServerEncoding()) : null;
```

**Comment by Sebi94nbg** [comment]
Should be fixed with the last commit (see above). This fix will be included with the next release. It's currently only available in the `develop` branch.
