### ISSUE TITLE
Usage of setOAuthToken

### ISSUE THREAD

**Issue by regsunited** [barbushin/php-imap#486]
- PHP IMAP version: 3.0.33 (latest)
 - PHP Version: 7.3.14
 - Type of execution: Web Server

A question regarding the usage of setOAuthToken():
Is there anything else that has to be done before calling setOAuthToken() apart from instantiating the object of Mailbox?

In other words, is this enough:

$mbox = new Mailbox($imap_server, $account_user, $account_password);
$mbox->setOAuthToken($oauth_token);

I ask this because I get the following error:
fwrite() expects parameter 1 to be resource, null given in whatever/PhpImap/Mailbox.php on line 77

**Comment by bapcltd-marv** [comment]
The connection isn't automatically made: https://github.com/barbushin/php-imap/blob/9c1469c053d4f1473cbd3648fc7ae363f6b3aace/src/PhpImap/Mailbox.php#L77

this bug has been fixed: https://github.com/barbushin/php-imap/blob/bd5fbc5d660631839885788c6c416a5c755fc5ab/src/PhpImap/Mailbox.php#L1656

the workaround would be to call `$mbox->getImapStream();` before setting the oauth token.

**Comment by Sebi94nbg** [comment]
I'll close this ticket since OAuth is currently not supported.

We just worked on an implementation, which was not working yet. See #411.

**Comment by bapcltd-marv** [comment]
@Sebi94nbg if it's not supported, should the method be removed as part of #475 ?

**Comment by Sebi94nbg** [comment]
Mhmm. We can remove it and put it into a seperate branch and as soon as it's working there, we can merge it.

**Comment by bapcltd-marv** [comment]
> Mhmm. We can remove it and put it into a seperate branch and as soon as it's working there, we can merge it.

have updated https://github.com/barbushin/php-imap/issues/465#issuecomment-592556940 accordingly
