### ISSUE TITLE
How not to mark letters read?

### ISSUE THREAD

**Issue by StasToken** [barbushin/php-imap#487]
- PHP Version: 7.4.3 (cli)
 - Type of execution: CLI

I get a list of letters like this:
`$this->mailbox->searchMailbox('UNSEEN');`

All letters that I receive are **marked as read**

I want this not to be - how to disable it? I want to mark letters after processing manually

**Comment by bapcltd-marv** [comment]
`$this->mailbox->getMail($id, false);` https://github.com/barbushin/php-imap/blob/9c1469c053d4f1473cbd3648fc7ae363f6b3aace/src/PhpImap/Mailbox.php#L1081

**Comment by StasToken** [comment]
thanks! - I somehow did not see it

**Comment by vielhuber** [comment]
Note that `saveMail` always sets mails to unread.
To overcome this the only possibiliy is to add `markMailAsUnread` directly afterwards.
