### ISSUE TITLE
[BUG] $mailbox->imap('append') does not give the same result as imap_append

### ISSUE THREAD

**Issue by nunoperalta** [barbushin/php-imap#489]
First of all - thanks very much for this project.
It runs perfectly for reading emails, and is very simple to use.

I found a weird issue with running the "append" function, when invoking through your "imap()" method.

I generate a [Swift_Message](https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Message.php) object, which I send to the user.

Then, I want to save to the Sent folder of the mailbox.

This works very well:

	$message= new Swift_Message(...);
	$stream = imap_open($connstring.$folder, $mail_from, $password);
	imap_append($stream, $connstring.$folder, $message->toString());

The email is appended properly, and can be viewed well in Thunderbird, etc..

However, when I use PHPImap,

	$mailbox = new PhpImap\Mailbox(
		$connstring.$folder,
		$mail_from,
		$password,
		null,
		'UTF-8'
	);

	$mailbox->setAttachmentsIgnore(true);

	$message= new Swift_Message(...);
	$mailbox->imap('append', [$connstring.$folder, $message->toString()]);

The email is appended unformatted, with the headers and body all in one single line.
Every line break seems to be transformed into the following characters: "&AA0ACg-".

Example:

	Return-Path: <email@domain.com>&AA0ACg-Message-ID: <1ac6389dfc624f3.......

Do you know why this happens, and is there a way to fix this, so I don't have to have mixed code using both your project and PHP native functions? :)

I suspect this might have to do with the transformation of the arguments using encodeStringToUtf7Imap()

https://github.com/barbushin/php-imap/blob/master/src/PhpImap/Mailbox.php#L1510

Thank you very much.

**Environment:**
 - PHP IMAP version: 3.0.33
 - PHP Version: 7.3
 - Type of execution: CLI

**Comment by nunoperalta** [comment]
I suspect this might have to do with the transformation of the arguments using encodeStringToUtf7Imap()

https://github.com/barbushin/php-imap/blob/master/src/PhpImap/Mailbox.php#L1510

**Comment by Sebi94nbg** [comment]
Released with [3.1.0](https://github.com/barbushin/php-imap/releases/tag/3.1.0)! :)
