### ISSUE TITLE
[BUG] IncomingMail->textPlain contains attachments

### ISSUE THREAD

**Issue by itkfm** [barbushin/php-imap#490]
**Environment (please complete the following information):**
 - PHP IMAP version: 3.0.33
 - PHP Version: PHP 7.3.11
 - Type of execution: CLI

**Describe the bug**
`IncomingMail->textPlain` contains attachments (immediately appended, no separator)

**To Reproduce**
Send yourself a plain text mail with a text file attached (name it e.g. `backup.log`).

```
Content-Type: multipart/mixed;
 boundary="=-=TFo2nlsFmy9-9lugYWi5ooUEyArvmHvDcQ1F=-="
X-Last-TLS-Session-Version: TLSv1.3

This is a multi-part message in MIME format.

--=-=TFo2nlsFmy9-9lugYWi5ooUEyArvmHvDcQ1F=-=
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline
Content-ID: […]

Backup completed

--=-=TFo2nlsFmy9-9lugYWi5ooUEyArvmHvDcQ1F=-=
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: attachment; filename="backup.log"
Content-ID: […]

###### Starting backup on
```

The used code:
```php
$mailbox = new Mailbox(
    '{' . $host . ':' . $port . '/imap/ssl}INBOX',
    $username,
    $password,
    '',
    'UTF-8'
);

$mailbox->setAttachmentsIgnore(true);

try {
    $mails = $mailbox->searchMailbox('ALL');
} catch (ConnectionException $ex) {
    // …
}

if (!$mails) {
    die(0);
    return;
}

foreach ($mails as $mID) {
    $mail = $mailbox->getMail($mID, true);
    var_dump($mail->textPlain);
}
```

The headers of the parsed email, if required and possible (only, if it's NOT confidential):
> confidential, unfortunately… sorry :(

**Expected behavior**
Get the mail's “normal” text only.

**Screenshots / Outputs**

*Thunderbird*:
![Screenshot from 2020-04-07 19-08-26](https://user-images.githubusercontent.com/53079668/78699078-9632dd00-7903-11ea-98cf-328086aa6542.png)

*var_dump*:
![Screenshot from 2020-04-07 19-15-05](https://user-images.githubusercontent.com/53079668/78699533-58828400-7904-11ea-8bb7-88b08d276095.png)

**Additional context**
seems to be similar to #390

**Comment by michaljusiega** [comment]
I think it's not bug. You can filter attachmets using incominMail->disposition === 'attachment'.

**Comment by itkfm** [comment]
Apart from `

**Comment by itkfm** [comment]
`IncomingMail` does *not* define a property `disposition`.

Apart from that I doubt that it's intended behavior that the attachments get appended to `->textPlain` **without any separator**.

**Comment by Sebi94nbg** [comment]
@itkfm did you already test this behaviour with the current code from the `develop` branch? A lot of improvements were made here.

**Comment by itkfm** [comment]
nope, I haven't yet

**Comment by bapcltd-marv** [comment]
popping tests in currently.

**Comment by bapcltd-marv** [comment]
> popping tests in currently.

yup, seeing this bug happen.

**Comment by bapcltd-marv** [comment]
> > popping tests in currently.
> 
> yup, seeing this bug happen.

have a fix pending

**Comment by bapcltd-marv** [comment]
> nope, I haven't yet

please try d5bea08 from #503

**Comment by Sebi94nbg** [comment]
@itkfm could you please give @bapcltd-marv's fix a quick try, that we can merge it soon? :)

**Comment by itkfm** [comment]
working fine here

**Comment by Sebi94nbg** [comment]
Great! Thanks for your feedback. The fix will be included in the next release. :)
