### ISSUE TITLE
preg_match_all() error in replaceInternalLinks and embedImageAttachments

### ISSUE THREAD

**Issue by 2acode** [barbushin/php-imap#496]
- PHP IMAP version: latest
 - PHP Version: 7.2.24
 - Type of execution: Web Server

Hi,
great library, thanks for sharing!

After retrieved the message i try to show with embedded image but always get the error:
"preg_match_all() expects parameter 2 to be string, null given"
referer to IncomingEmail.php line 202

Same issue if i try the replaceInternalLinks function (errore referer to IncomingEmail line 166)

The HTML body seems to be ok:
$message = $mailbox->getMail($uid);
echo $message->textHtml;

Then the error if:
$message->embedImageAttachments();
or
echo $message->replaceInternalLinks($myPublicPath);

Can you give me a correct examples?
Thanks

**Comment by bapcltd-marv** [comment]
can you please give https://github.com/bapcltd/php-imap/commit/114463c799a6b0fb26724ef0de773cdc150a47c7 a try ?

**Comment by Sebi94nbg** [comment]
@2acode could you please test @bapcltd-marv changes? When it's working for you, we'll merge this fix.

**Comment by lexandclo** [comment]
Sorry to jump on the issue, but wondering if someone could give me an example of how to do the embedImageAttachments(), as at the moment my html returns the cid: for the image and doesn't display in the output and i would like is to display in the output.
Appreciate any pointers

**Comment by MartinWierenga** [comment]
Same issue here, output of PHP only shows cid:filename.png@RANDOMSTRING.
For example: cid:image014.png@01D50426.B7BE0650
The files are saved as .BIN files. Can we change this to be original files?

**Comment by bapcltd-marv** [comment]
@MartinWierenga have you tried with the suggested fix ?

**Comment by bapcltd-marv** [comment]
@MartinWierenga re:
> Same issue here, output of PHP only shows cid:filename.png@RANDOMSTRING.
> For example: cid:image014.png@01D50426.B7BE0650
> The files are saved as .BIN files. Can we change this to be original files?

https://github.com/bapcltd/php-imap/commit/4758d8ebad41d09505a3bd5f1433246b2d22ebe2
> "basing the $fileSysName on the attachment filename can result in a
permission denied error, or otherwise being unable to download the
attachment."

**Comment by lexandclo** [comment]
Ive tried the suggested fix but still get the cid:,  instead of the full path. thats why i asked for an example to see what i was doing wrong, maybe @MartinWierenga is having the same issue?

**Comment by bapcltd-marv** [comment]
Is the email just something you're receiving or something that you're composing & sending ?

Would need a reproduction to test this thoroughly.

**Comment by lexandclo** [comment]
its just in email receiving. is it meant to call the inline images automatically if the email is 
`$email->html`?
as it just returns ie `cid:0.28873910070.3190149461557253921.17227fca2e2__inline__img__src`

**Comment by bapcltd-marv** [comment]
> its just in email receiving.

I'll need to wait until there's time for me to tinker with the live mailbox tests for this then (unless @Sebi94nbg beats me to it)

**Comment by bapcltd-marv** [comment]
@lexandclo can you open a new issue for the cid issue? have managed to replicate it locally.

**Comment by lexandclo** [comment]
#514 added.

Thank you

**Comment by bapcltd-marv** [comment]
additional patches included: https://github.com/barbushin/php-imap/pull/515

**Comment by Sebi94nbg** [comment]
I've merged the fix into the `develop` branch. The fix will be included in the next release.
