### ISSUE TITLE
imap_search function is not fully compatible with IMAP4. the c-client used as of now supports only IMAP2

### ISSUE THREAD

**Issue by xwp93922** [barbushin/php-imap#498]
imap_search function is not fully compatible with IMAP4. the c-client used as of now supports only IMAP2

**Comment by bapcltd-marv** [comment]
is this re: search syntax that's not supported due to the underlying php extension?

**Comment by Sebi94nbg** [comment]
@xwp93922 any feedback?

**Comment by bapcltd-marv** [comment]
> I guess this is also related to #250, isn't it?

re: #508, I'm guessing no?

**Comment by Sebi94nbg** [comment]
Mhmm, ok. Thanks! :D

**Comment by bapcltd-marv** [comment]
acting on the assumption that it's just about the lack of syntax support, then I'd say yes- workarounds should probably be requested individually (I think that multiple criteria method I added was syntax-related?)

**Comment by Sebi94nbg** [comment]
Yeah, ok. Then let's close this for now. If anyone else has any issues, a respective issue should be opened, that we can take a look at this specific issue in order to fix it.

**Comment by bapcltd-marv** [comment]
I mean the alternative is to re-implement the extension in pure php via sockets, and I'm pretty sure that's waaaayyy out of scope :P

**Comment by Sebi94nbg** [comment]
Definitely, yes. :D
