### ISSUE TITLE
[BUG] open function failed for mailbox with non ASCII charact

### ISSUE THREAD

**Issue by jeanphiB** [barbushin/php-imap#499]
**Environment:**
 - IMAP c-Client Version version: 2007f
 - PHP Version: 7.4.5
 - Type of execution: localhost

**Describe the bug**
When I need to get the status of a folder, with INBOX it's ok, but if I use "Éléments envoyés", I've this error :
```
Severity: Warning
Message: imap_open(): Couldn't open stream &amp;AMk-l&amp;AOk-ments envoy&amp;AOk-s
Filename: PhpImap/Imap.php
Line Number: 700
```

**To Reproduce**
call the status function and set a mailbox with non ascii characters

**Proposed code changing**
on Imap.php change line 694 from:
  `$mailbox = static::encodeStringToUtf7Imap($mailbox_name);`
to:
  `$mailbox = static::encodeStringToUtf7Imap($mailbox);`
this avoid to lost {server:port} part of the mailbox.

**Comment by bapcltd-marv** [comment]
writing a test for this at the moment.

**Comment by Sebi94nbg** [comment]
Please test with the code from the latest `develop` branch: `composer require php-imap/php-imap:dev-develop`

**Comment by jeanphiB** [comment]
The test is succeed for me. Thank you very much.

**Comment by bapcltd-marv** [comment]
you're welcome :)
