### ISSUE TITLE
query: re try-catch block around `new fileinfo`

### ISSUE THREAD

**Issue by bapcltd-marv** [barbushin/php-imap#505]
re:  a1f383d, I was just wondering what circumstances `new fileinfo($fileinfo_const)` throws an exception?

**Comment by Sebi94nbg** [comment]
Oh, forgot to remove this test code and committed it instead. Thanks for reviewing. >.<

Just as explanation: I've tried something and when no file was provided, it has thrown an `Exception`.

But it was never catched, so... Removing it is fine.
