### ISSUE TITLE
[Feature Request] PHP IMAP: Bitmask options

### ISSUE THREAD

**Issue by SpiGAndromeda** [barbushin/php-imap#510]
**Is your feature request related to a problem? Please describe.**
PHP Imap supports a bitmask of options. The setConnectionArgs method allows only setting one option by checking if the integer is in the allowed options string.

**Describe the solution you'd like**
The options argument could be changed to an array. The bitmask could be created inside the function:
```php
$optionsBitmaskString = '';
foreach($options as $option) {
    /** @var int $option */
    if (!\in_array($option, $supported_options, true)) {
        throw new InvalidParameterException('Please check your option for setConnectionArgs()! Unsupported option "'.$option.'". Available options: https://www.php.net/manual/de/function.imap-open.php');
    }
    $optionsBitmaskString .= strval($option);
}
$optionsBitmask = ('' !== $optionsBitmaskString) ? intval($optionsBitmaskString) : 0; 
// I am not sure if 0 or null is for no option.
```

best reagrds,
SpiGAndromeda

**Comment by bapcltd-marv** [comment]
would prefer to change the exact-match input validation to bitmask operations.

**Comment by SpiGAndromeda** [comment]
Ok. Depends if you want the "user" to handle the bitmask creation. To my mind, it would be nice if the method could handle this. But you're the contributor! :D

And ... I see that I didn't understood bitmasks properly. If [this](https://medium.com/@liamhammett/bitmask-constant-arguments-in-php-cf32bf35c73) is correct, bitmask creation isn't that easy and validation would be even more difficult. Passing an array of integers would be a lot more simple for the user of this package and you wouldn't have to deal with the validation of the bismask. Array validation is much simpler.
Honestly ... I don't see the point in accepting a bitmask over passing an array.

**Comment by bapcltd-marv** [comment]
> And ... I see that I didn't understood bitmasks properly. If [this](https://medium.com/@liamhammett/bitmask-constant-arguments-in-php-cf32bf35c73) is correct, bitmask creation isn't that easy

* `$mailbox->setConnectionArgs(OP_DEBUG | OP_HALFOPEN);` seems pretty straight forward

> validation would be even more difficult.

currently testing a thing for that.

**Comment by SpiGAndromeda** [comment]
Suggestion with array of integers as options:
```php
$supported_options = [OP_READONLY, OP_ANONYMOUS, OP_HALFOPEN, CL_EXPUNGE, OP_DEBUG, OP_SHORTCACHE, OP_SILENT, OP_PROTOTYPE, OP_SECURE];
if (!empty(array_intersect($options, $supported_options)) {
    throw new InvalidParameterException('Please check your option for setConnectionArgs()! Unsupported option "'.$options.'". Available options: https://www.php.net/manual/de/function.imap-open.php');
}

$optionBitmask = 0;
foreach($options as $option) {
    /** @var $option int **/
    $optionBitmask & $option;
}
```

**Comment by SpiGAndromeda** [comment]
> > And ... I see that I didn't understood bitmasks properly. If [this](https://medium.com/@liamhammett/bitmask-constant-arguments-in-php-cf32bf35c73) is correct, bitmask creation isn't that easy
> 
>     * `$mailbox->setConnectionArgs(OP_DEBUG | OP_HALFOPEN);` seems pretty straight forward
> 
> 
> > validation would be even more difficult.
> 
> currently testing a thing for that.

Ahh yes: I see that bitwise arithmetic is pretty simple in PHP. Sorry for that. I thought calculation would be much more difficult. Than you are right: bitmask could be easily created by the user. But an example in the docs would be nice.

**Comment by bapcltd-marv** [comment]
> But an example in the docs would be nice.

will do, once i've got the automated test behaving.

**Comment by SpiGAndromeda** [comment]
Bretty nice! THX for the fast reply. Do you create the PR or should I do that?

**Comment by bapcltd-marv** [comment]
I'll post the PR once the testing behaves & travis reports no issues :)

**Comment by bapcltd-marv** [comment]
made the PR earlier, but didn't get around to fleshing out the description of the PR.

**Comment by SpiGAndromeda** [comment]
I am not that familiar with the PR process? Do I have to do something?

**Comment by bapcltd-marv** [comment]
sit and wait :P

you can manually pull down the code if you need to use it, however.

**Comment by Sebi94nbg** [comment]
Merged the fix into `develop`! I'll release a new `master` version approx. on this Sunday.
