### ISSUE TITLE
inline images returning cid:filename 

### ISSUE THREAD

**Issue by lexandclo** [barbushin/php-imap#514]
**Environment (please complete the following information):**
   PHP IMAP version: latest
   PHP Version: 7.3
   Type of execution: localhost

Upon trying to return the inline images in an received email 
`$email->embedImageAttachments();` returns cid:filename- random string

**Comment by bapcltd-marv** [comment]
the fix for this is currently on the other computer so can't push it up, but there is a fix :D

**Comment by lexandclo** [comment]
@bapcltd-marv brill stuff, look forward to it.

**Comment by bapcltd-marv** [comment]
will be PR'd briefly, I keep messing up the commit history.

**Comment by bapcltd-marv** [comment]
have PR'd, please give it a try: https://github.com/barbushin/php-imap/pull/515

**Comment by lexandclo** [comment]
@bapcltd-marv all working now, thanks for the fix :)

**Comment by Sebi94nbg** [comment]
I've merged the fix into the `develop` branch. The fix will be included in the next release.
