### ISSUE TITLE
[BUG] Inline images still not showing even after applying patch 515

### ISSUE THREAD

**Issue by wehaveaplan** [barbushin/php-imap#519]
**Environment (please complete the following information):**
 - PHP IMAP version: latest development version.
 - PHP Version: 7.3.19
 - Type of execution: Web server

**Describe the bug**
Inline images still not working after applying patches from https://github.com/barbushin/php-imap/pull/515.

**To Reproduce**
Send e-mail with inline image.

The used code:
I noticed that $attachment->disposition in the function embedImageAttachments in the file IncomingMail.php of the package returned INLINE in caps, causing 'inline' == $attachment->disposition to return false. Hosting depended maybe?

I changed this to 'inline' == strtolower($attachment->disposition) and it's working now.

**Expected behavior**
Inline images to show when using the function embedImageAttachments().

**Comment by Sebi94nbg** [comment]
I've merged those fixes from @bapcltd-marv into the develop branch.

**Comment by Sebi94nbg** [comment]
Closing this due to no feedback.
