### ISSUE TITLE
imap_last_error()

### ISSUE THREAD

**Issue by slo-nik** [barbushin/php-imap#523]
**Environment (please complete the following information):**
 - PHP IMAP version: 4.1.0
 - PHP Version: 7.2.31
 - Type of execution: Web Server

**Your Text**
Файл Imap.php, статический метод [open()](https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/Imap.php#L684). Не отрабатывается код для вывода imap_last_error(), выводит сообщение об ошибке:
 
**imap_open(): Couldn't open stream**

           $result = \imap_open($mailbox, $username, $password, $options, $n_retries, $params);

            if (!$result) {
                 $lastError = \imap_last_error();

                if ('' !== \trim($lastError)) {
                     throw new UnexpectedValueException('IMAP error:'.$lastError);
                }

                throw new UnexpectedValueException('Could not open mailbox!', 0, self::HandleErrors(\imap_errors(), 'imap_open'));
            }

В таком варианте код отрабатывается, срабатывает исключение с выводом imap_last_error(), добавил @ перед imap_open()

**IMAP error:Can not authenticate to IMAP server: [AUTHENTICATIONFAILED] Authentication failed.** 

    $result = @imap_open($mailbox, $username, $password, $options, $n_retries, $params);
            /**/
            if ('' !== \trim($lastError)) {
                     throw new UnexpectedValueException('IMAP error:'.$lastError);
                }
           

Как можно это исправить?

**Comment by Sebi94nbg** [comment]
I've merged the fix from @bapcltd-marv to the develop branch. Please test. :)

**Comment by slo-nik** [comment]
> I've merged the fix from @bapcltd-marv to the develop branch. Please test. :)

А что проверять? Я проверил перед тем, как Вам писать.

**Comment by bapcltd-marv** [comment]
i.e. does the error still occur with the latest code.

**Comment by Dasinfomedia2** [comment]
> i.e. does the error still occur with the latest code.

Yes. 
Warning: imap_open(): Couldn't open stream {mail.xxxx.com:993/imap/ssl/novalidate-cert}INBOX

if I write the 'imap_open' function manually for test then it works.

**Comment by mrcodefinger** [comment]
Same here

**Comment by mrcodefinger** [comment]
The solution for me is leaving out `OP_SECURE ` of
`$mailbox->setConnectionArgs(
    CL_EXPUNGE // expunge deleted mails upon mailbox close
);`

**Comment by Sebi94nbg** [comment]
Is this issue still reproduceable with the latest release [4.3.0](https://github.com/barbushin/php-imap/releases/tag/4.3.0)?

**Comment by Sebi94nbg** [comment]
Might be also related to the issue #571.

**Comment by Sebi94nbg** [comment]
Closing this issue for now. If the issue should still occur, please comment this issue or open a new one.
