### ISSUE TITLE
How to detect textPlain encoding

### ISSUE THREAD

**Issue by xcono** [barbushin/php-imap#525]
**Environment:**
 - PHP IMAP version: [4.1]
 - PHP Version: [e.g. 7.4]
 - Type of execution: [CLI]

Thank you for your work. The package is easy to use and works like a charm.
My question is related to `textPlain` and `textHtml` properties of  `IncomingMail` class.
As I understand the properties lazy fetched from `DataPartInfo` containing `encoding` property.

I'm stuck with some koi8-r encoded emails, where `textPlain` property has `koi8-r` encoded string, but since I have no access to `DataPartInfo` of the IncomingMail I can't detect the proper encoding of the string. 

Dump of IncomingMail object [msg-5efa2d360af79.txt](https://github.com/barbushin/php-imap/files/4847382/msg-5efa2d360af79.txt)

I can't rely on mbstring, since there is no guarantee to correct detection.
What is the best practice to convert mails to utf8?

**Comment by bapcltd-marv** [comment]
is `koi8-r` one of of those encodings that can be reliably remapped to a different encoding? #513 introduced a fix for #509, whereby `ks_c_5601-1987` could be reliably remapped to `EUC-KR`.

**Comment by xcono** [comment]
Thank you for your reply. I saw the #509 and #513 issues. In my case, I don't know the charset to set `Mailbox::decodeMimeStrDefaultCharset`. I'm fetching multiple e-mails from a mailbox, some of them are UTF encoded, others are koi-8r.

The chain of calls to fetch `textPlain` is: `IncomingMail::_get('textPlain')`, then recursively `DataPartInfo::fetch()` and at the end is `DataPartInfo::convertEncodingAfterFetch()` there proper charset exists (`koi8-r`, in my case), but after data passed to `Mailbox::decodeMimeStr()` it is not encoded to UTF, since `$charset` is `default`. So, `data` is still `koi8-r`.

But I need to convert it to `utf-8`, the problem is I can't access to `$charset` values appear in `DataPartInfo::convertEncodingAfterFetch()`, so don't know what to pass to `mb_convert_encoding($text, 'UTF-8', $charset)` as 3rd arg.

My current workaround is extending `IncomingMail` and make getter for `DataPartInfo IncomingMail::dataInfo` to extract charset and apply conversion after text fetched. I feel it is not the correct way to solve my task to fetch mail and save as utf-8 in database.

**Comment by bapcltd-marv** [comment]
> The chain of calls to fetch `textPlain` is: `IncomingMail::_get('textPlain')`, then recursively `DataPartInfo::fetch()` and at the end is `DataPartInfo::convertEncodingAfterFetch()` there proper charset exists (`koi8-r`, in my case), but after data passed to `Mailbox::decodeMimeStr()` it is not encoded to UTF, since `$charset` is `default`. So, `data` is still `koi8-r`.

Your data dump indicates the `charset` property of `DataPartInfo` is `'koi8-r'`, so *ideally* `Mailbox::decodeMimeStr()` should be using `'koi8-r'` when it reaches here: https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/Mailbox.php#L1356

meaning that either `mb_convert_encoding()` should be being called with `'koi8-r'` when it reaches here: https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/Mailbox.php#L1368

or that `iconv()` should be being called with `'koi8-r'` when it reaches here: https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/Mailbox.php#L1371

or that both would fail and be appending here: https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/Mailbox.php#L1377

However, it sounds like things are failing right up top with `imap_mime_header_decode()` https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/Mailbox.php#L1347

Can you please post a (sanitised/censored) dump of `$elements` ?

**Comment by xcono** [comment]
Hello, thank you for your attention. The dump is [here](https://github.com/barbushin/php-imap/files/4847382/msg-5efa2d360af79.txt)

You are right, failing in `imap_mime_header_decode()`, but as I understand the function can not detect charset by the string itself and requires a prefix of the string, `=?koi8-r?` for instance. I have to note, the code correctly converts `fromName` and `subject` fields when the strings have the prefix `=?koi8-r?`.

You wrote before, that

https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/Mailbox.php#L1356

meaning that either mb_convert_encoding() should be being called with 'koi8-r' when it reaches here:
https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/Mailbox.php#L1368

But in my case `decodeMimeStrDefaultCharset` stay untouched and keep `default` string, so before calling `mb_convert_encoding()` I have:
https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/Mailbox.php#L1357

That means:
```php
if ('default' === $charset) {
    $charset = $this->decodeMimeStrDefaultCharset;  // here $this->decodeMimeStrDefaultCharset === 'default'
}
```

<details><summary>My current workaround</summary><p>

I tried to find a way to make something like this
```php

$messageIds = $mailbox->searchMailbox($criteria);

foreach ($messageIds as $messageId) {
    $message= $mailbox->getMail($messageId);
    $message->decodeMimeStrDefaultCharset = $message->getDetectEncoding('textPlain'); // not reliable
    $message->textPlain; // force to fetch and encode datapart
    $message->decodeMimeStrDefaultCharset; // reset to next iteration
}
```
I extend `IncomingMail` class with a custom `getDetectEncoding()` method. So, it looks like a not good piece of code, since my encoding detection relies on the method such as:
```php
public function getDetectEncoding($name)
    {
        $key = $name === 'textPlain' ? DataPartInfo::TEXT_PLAIN : DataPartInfo::TEXT_HTML;
        // is it possible multipart $this->dataInfo[$key][0] and $this->dataInfo[$key][1] has different charset?
        $data = $this->dataInfo[$key][0] ?? null; 

        if ($data instanceof DataPartInfo) {
            return $data->charset;
        }

        return `default`;
    }
```

**Comment by bapcltd-marv** [comment]
> Hello, thank you for your attention. The dump is [here](https://github.com/barbushin/php-imap/files/4847382/msg-5efa2d360af79.txt)

that does not appear to be a dump of `$elements` ?

**Comment by xcono** [comment]
Well, I checked $elements, it has `'default'` charset. [Message dump](https://github.com/barbushin/php-imap/files/4871787/5effaf86734a8.txt) and [elements dump](https://github.com/barbushin/php-imap/files/4871790/5effb4efa76ef-elements.log) from `decodeMimeStr` for dataPart of 'textPlain'.

It is the case I can't avoid extending the library classes (or extending too many classes). The message `dataInfo[0]` array has two data parts with different charset. And the point is `Mailbox::initMailPart` detect proper charset and set it to `DataPartInfo::charset`. But `DataPartInfo::convertEncodingAfterFetch()` method know about proper charset, but don't pass it to `Mailbox::decodeMimeStr()`:

https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/DataPartInfo.php#L110-L114

**Comment by twmobius** [comment]
Just found this ticket, it's the same case on my #530 which I've just created.

**Comment by felix-goecking** [comment]
Hi guys, nice to see this thread because we are having exactly the same problem. In my point of view the _charset_ in the DatePartInfo.php is not used for mail body to set the encoding. Instead _imap_mime_header_decode_ is used also for the body parts. Here is an example for an part of one of our problematic mails:

```
--00000000000035bb5705ae7bcde0
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: base64

5L2g5aW977yM5pyJ5pu05aSa6Zec5pa86Jaq6YWs6LOH5paZ5ZeO77yfDQoNCuOAjEhPIE1hcmt1
cyA8bWFya3VzaG8xMDMwQGdtYWlsLmNvbT7jgI3lnKggMjAyMOW5tDnmnIgz5pelIOmAseWbm++8
jDIxOjI4IOWvq+mBk++8mg0KDQo+IOS9oOWlve+8jOaIkeacg+eboeW/q+Whq+WlveS4puS4lOaK
iuihqOagvOS6pOWbnu+8jOS9huaIkeacieWAi+WVj+mhjOaYr+iWqumFrOWmguS9leioiOeul++8
nw0KPg0KPiBDbG91ZHdvcmtlcnMgQWdlbnRzIEhLIDxqb2JzLmhrQGNsb3Vkd29ya2Vycy5jb21w
YW55PiDmlrwgMjAyMOW5tDnmnIgz5pelIOmAseWbmw0KPiDkuIvljYg2OjQ45a+r6YGT77yaDQo+
DQo+Pg0KPj4NCj4+DQo+Pg0KPj4g5oKo5aW977yM5YaN5qyh5oSf6Kyd5oKo5bCH6KaB5rGC55qE
5paH5Lu26YCA6YKE57Wm5oiR5YCR44CCDQo+Pg0KPj4NCj4+DQo+Pg0KPj4g5L2G5piv77yM55Sx
5pa857y65bCR5YW25Lit55qE5paH5qqU77yM6KuL5YaN5qyh55m86YCB6YCZ5Lqb5paH5qqU77yM
5Lul5L6/5oiR5YCR6IO95aSg5b+r6YCf6JmV55CG5oKo55qE55Sz6KuL77yM5Lim5biM5pyb5oKo
5pys6YCx6IO95aSg5Yqg5YWl44CCDQo+Pg0KPj4NCj4+DQo+Pg0KPj4g6Yyv6Kqk5oiW5pyq6YCB
55qE5paH5Lu277yaDQo+Pg0KPj4NCj4+DQo+Pg0KPj4NCj4+DQo+PiAxLlNlbGYgQmlsbGluZyBB
Z3JlZW1lbnQNCj4+DQo+Pg0KPj4NCj4+DQo+PiAyLkNsb3Vkd29ya2VycyBDb250cmFjdA0KPj4N
Cj4+IDMgQXV0byBQYXkgSW5mbw0KPj4NCj4+DQo+PiBQUzsg5q+U6LW36YqA6KGM5oiR5pu05o6o
6JamcGF5cGFs77yM5Zug54K65omL57qM6LK75pyD5pu05YiS566X44CCDQo+Pg0KPj4NCj4+DQo+
Pg0KPj4g6KuL6YCA5Zue5LiK6Z2i5YiX5Ye655qE5paH5Lu2LCDpnZ7luLjph43opoHnmoTmmK/v
vIzpgJnkupvoq4vlhJjlv6vmrbjpgoTntabmiJHlgJHjgIINCj4+DQo+Pg0KPj4NCj4+DQo+Pg0K
Pj4NCj4+DQo+Pg0KPj4NCj4+IOisneisneaCqOeahOWQiOS9nOOAgg0KPj4NCj4+DQo+Pg0KPj4N
Cj4+DQo+Pg0KPj4NCj4+DQo+Pg0KPj4gKkNMT1VEV09SS0VSUyBDT01QQU5ZKg0KPj4NCj4+DQo+
Pg0KPj4NCj4+ICpSZWNydWl0aW5nIE9mZmljZSoNCj4+DQo+Pg0KPj4NCj4+DQo+PiBGb246ICs0
NCAoMCkgMjA4MDgwNjU3MQ0KPj4NCj4+DQo+Pg0KPj4NCj4+IDEyOCBDYW5ub24gV29ya3Nob3Bz
IENhbm5vbiBEcml2ZQ0KPj4NCj4+DQo+Pg0KPj4NCj4+IEUxNCA0QVMgTG9uZG9uDQo+Pg0KPj4N
Cj4+DQo+Pg0KPj4gd3d3LmNsb3Vkd29ya2Vycy5jb21wYW55DQo+Pg0KPj4NCj4+DQo+Pg0KPg0K
Pg0K
```

The charset is set to UTF-8 and the DataPartInfo.php recognizes that correctly. But in the method convertEncodingAfterFetch this charset isn't used anymore. Instead the method decodeMimeStr uses imap_mime_header_decode, which extracts the element and returns default as charset. With barbushin/php-imap#513 I can override the "default", which I need to do since some of our mails need to be converted. Thus the previous correct string is converted and is now corrupted. 

Maybe the decodeMimeStr method needs an extra parameter to know if the charset has been given/extracted before and if this has been done the _imap_mime_header_decode_ needs to be skipped?

@bapcltd-marv Does this example helps you?

**Comment by bapcltd-marv** [comment]
> Maybe the decodeMimeStr method needs an extra parameter to know if the charset has been given/extracted before and if this has been done the _imap_mime_header_decode_ needs to be skipped?

It used to have the extra parameter and I have no idea why it was removed.

**Comment by twmobius** [comment]
@bapcltd-marv Check out my ticket (#530), since I've pretty much implemented the solution required and provide reference that led to the code being changed and getting at this point

**Comment by bapcltd-marv** [comment]
> @bapcltd-marv Check out my ticket (#530), since I've pretty much implemented the solution required and provide reference that led to the code being changed and getting at this point

there's a currently a PR (probably) relating to this - #542 



> > Maybe the decodeMimeStr method needs an extra parameter to know if the charset has been given/extracted before and if this has been done the _imap_mime_header_decode_ needs to be skipped?
> 
> It used to have the extra parameter and I have no idea why it was removed.

see: https://github.com/barbushin/php-imap/pull/542#discussion_r471470900



> Check out my ticket

see also: https://github.com/barbushin/php-imap/pull/542#discussion_r471541790

**Comment by felix-goecking** [comment]
Any news on this? It causes a lot of damage for us...

**Comment by bapcltd-marv** [comment]
ping @Sebi94nbg

**Comment by felix-goecking** [comment]
So I posted an pull request here https://github.com/barbushin/php-imap/pull/551. As I'm not good at writing tests maybe someone else can do it. We are using this code for 3 weeks now and it works well for us.

**Comment by Sebi94nbg** [comment]
I guess this is solved, so we can close it, right?

**Comment by felix-goecking** [comment]
Yes, can be closed, thanks
