### ISSUE TITLE
[BUG] Exception thrown when querying empty inbox while sorting emails.

### ISSUE THREAD

**Issue by webkod3r** [barbushin/php-imap#526]
**Environment (please complete the following information):**
 - PHP IMAP version: 3.1.0 - 4.1.0
 - PHP Version: 7.2
 - Type of execution: CLI

**Describe the bug**
When querying the mail inbox sorting emails and non results fetched the library throws an exception:

```php
throw new UnexpectedValueException('Could not sort messages!', 0, self::HandleErrors(\imap_errors(), 'imap_sort'));
```

You can find the line causing the bug here.
https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/Imap.php#L938-L940

**To Reproduce**
I have a job in Laravel to check incoming emails with requests from users. Those emails are sorted by the oldest unseen first.

The used code:
```php
$mailsIds = $this->getMailBoxInstance()->sortMails(SORTARRIVAL, false, 'UNSEEN', 'utf-8');
```

**Expected behavior**
If there are no new emails unseen the code should return an empty array without throwing an exception.

**Comment by bapcltd-marv** [comment]
Documentation indicates `imap_sort()` is only intended to return `array` on success, zero results should be a "success" state.

#524 contains the class added for `Imap` class-specific tests, so I'll be awaiting merging of this before I make time to investigate thoroughly.

**Comment by bapcltd-marv** [comment]
@webkod3r does this fix your issue? https://github.com/barbushin/php-imap/pull/535/commits/de4f55c4604062a45f8537f55e6937df79944093

**Comment by GDmac** [comment]
I'm bumping into this issue too (sortMails() on empty inbox throws)
Using work-around ->searchMailbox('ALL') (no sort :-( )

Any Idea when this/#535 might be merged into master?
