### ISSUE TITLE
[Feature Request] Seen and Unseen option not available

### ISSUE THREAD

**Issue by jaqsamacode** [barbushin/php-imap#529]
When I am trying to print_r($email), all available options are showing but seen and unseen option are not.

PhpImap\IncomingMail Object ( [attachments:protected] => Array ( ) [hasAttachments:protected] => 1 [dataInfo:protected] => Array ( [0] => Array ( [0] => PhpImap\DataPartInfo Object ( [id] => 6 [encoding] => 0 [charset] => us-ascii [part] => 1 [mail] => PhpImap\Mailbox Object ( [decodeMimeStrDefaultCharset] => default [imapPath:protected] => {imap.one.com:993/imap/ssl}INBOX [imapLogin:protected] => kashmalakanwal@wfpspk.com [imapSearchOption:protected] => 1 [connectionRetry:protected] => 0 [connectionRetryDelay:protected] => 100 [imapOptions:protected] => 0 [imapRetriesNum:protected] => 0 [imapParams:protected] => Array ( ) [serverEncoding:protected] => UTF-8 [attachmentsDir:protected] => [expungeOnDisconnect:protected] => 1 [timeouts:protected] => Array ( ) [attachmentsIgnore:protected] => 1 [pathDelimiter:protected] => / [mailboxFolder:protected] => INBOX [imapStream:PhpImap\Mailbox:private] => Resource id #11 ) [options] => 3 [data:protected] => ) ) [1] => Array ( ) ) [textPlain:PhpImap\IncomingMail:private] => [textHtml:PhpImap\IncomingMail:private] => [id] => 6 [imapPath] => {imap.one.com:993/imap/ssl}INBOX [mailboxFolder] => INBOX [isDraft] => [date] => 2020-07-16T17:14:44+05:00 [headersRaw] => Return-Path: Delivered-To: kashmalakanwal@wfpspk.com Received: from mx4.pub.mailpod9-cph3.one.com ([10.27.39.14]) by mailstorage14.cst.mailpod9-cph3.one.com with LMTP id 0IjbDLZEEF8vIQAAYQUlgA for ; Thu, 16 Jul 2020 12:14:46 +0000 Received: from mailout1-2.pub.mailoutpod1-cph3.one.com (mailout1-2.pub.mailoutpod1-cph3.one.com [46.30.212.6]) by mx4.pub.mailpod9-cph3.one.com (Halon) with ESMTPS id efc1c3c2-c75d-11ea-8c68-3448edec68e8; Thu, 16 Jul 2020 12:14:45 +0000 (UTC) DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=wfpspk.com; s=20191106; h=content-transfer-encoding:content-type:mime-version:message-id:reply-to:from: date:subject:to:from; bh=NZwyD8f3tE1Sin1c1GT4xVrYZtRfpsEUCXSeZgPPoJs=; b=D0XqYYHY0AgUXH/vsKDZyfATlp8lhRRt6GL0Xv5r8hVUcK2v4kQG6QeiyZ3iybD2X8sQx0rP0/w5+ L9oyKBTIsh9jPi9KpLlecBGrBzcNlv/tbFdlsALEuo2jWYk79suwdXQBZ8LfD8dm8QdJ6qD1wl5R+z Y8thMUjLBT+5UPztGqVOcbSz63t0dL1tKQc1Z7bvqCqB3GomKxYonWaIYL0Hg3vrdkSg3fg7StLhPT ns+FM/DKwjuVuU15+r6i+ZDHb115PbFFGpeRB3Fbo0GdBCjn8KLO2DF8MvO71hDgHUAqxQEjHadDa6 FDQXa7d9x8KHGxiHEF+uZBr/e+WVdBQ== X-HalOne-ID: efc1c3c2-c75d-11ea-8c68-3448edec68e8 Received: from wfpspk.com (customer-nat.pub.webpod11-cph3.one.com [193.202.110.17]) by mailout1.pub.mailoutpod1-cph3.one.com (Halon) with ESMTPSA id ef48c076-c75d-11ea-bb65-d0431ea8a29d; Thu, 16 Jul 2020 12:14:44 +0000 (UTC) Received: from 182.182.77.220 by wfpspk.com via /software/e-school/student_login/upload_assignments.php with HTTP; Thu, 16 Jul 2020 12:14:44 +0000 To: Kashmala Kanwal Subject: Assignment from Hussain Mehdi Class Prep-2 X-PHP-Originating-Script: 4436096:PHPMailer.php Date: Thu, 16 Jul 2020 17:14:44 +0500 From: Hussain Mehdi Assignment Reply-To: Hussain Mehdi Message-ID: X-Mailer: PHPMailer 6.1.7 (https://github.com/PHPMailer/PHPMailer) MIME-Version: 1.0 Content-Type: multipart/mixed; boundary="b1_IgZ6WluoCuy4mtPX85tdGA8FY3N0CJe3jtPbGtyk4" Content-Transfer-Encoding: 8bit [headers] => stdClass Object ( [date] => Thu, 16 Jul 2020 17:14:44 +0500 [Date] => Thu, 16 Jul 2020 17:14:44 +0500 [subject] => Assignment from Hussain Mehdi Class Prep-2 [Subject] => Assignment from Hussain Mehdi Class Prep-2 [message_id] => [toaddress] => Kashmala Kanwal [to] => Array ( [0] => stdClass Object ( [personal] => Kashmala Kanwal [mailbox] => kashmalakanwal [host] => wfpspk.com ) ) [fromaddress] => Hussain Mehdi Assignment [from] => Array ( [0] => stdClass Object ( [personal] => Hussain Mehdi Assignment [mailbox] => assignment [host] => wfpspk.com ) ) [reply_toaddress] => Hussain Mehdi [reply_to] => Array ( [0] => stdClass Object ( [personal] => Hussain Mehdi [mailbox] => hussainmehdi1016wfps [host] => gmail.com ) ) [senderaddress] => Hussain Mehdi Assignment [sender] => Array ( [0] => stdClass Object ( [personal] => Hussain Mehdi Assignment [mailbox] => assignment [host] => wfpspk.com ) ) ) [mimeVersion] => message-id:reply-to:from: [xVirusScanned] => [organization] => [contentType] => mime-version:message-id:reply-to:from: [xMailer] => PHPMailer 6.1.7 (https://github.com/PHPMailer/PHPMailer) [contentLanguage] => [xSenderIp] => [priority] => [importance] => [sensitivity] => [autoSubmitted] => [precedence] => [failedRecipients] => [subject] => Assignment from Hussain Mehdi Class Prep-2 [fromHost] => wfpspk.com [fromName] => Hussain Mehdi Assignment [fromAddress] => assignment@wfpspk.com [senderHost] => wfpspk.com [senderName] => Hussain Mehdi Assignment [senderAddress] => assignment@wfpspk.com [to] => Array ( [kashmalakanwal@wfpspk.com] => Kashmala Kanwal ) [toString] => Kashmala Kanwal [cc] => Array ( ) [bcc] => Array ( ) [replyTo] => Array ( [hussainmehdi1016wfps@gmail.com] => Hussain Mehdi ) [messageId] => )

**Comment by bapcltd-marv** [comment]
this may or may not be related to [a nearly decade-old feature request in php](https://bugs.php.net/bug.php?id=53043)

**Comment by naitsirch** [comment]
@bapcltd-marv I think he is asking for viewing seen/unseen status for fetched mails. The feature request you have linked is about adding custom imap flags ;-)

**Comment by Sebi94nbg** [comment]
@jaqsamacode what exactly is this topic here? Can you please provide more information. As you can see: Two people already have different opinions about the topic.

**Comment by Sebi94nbg** [comment]
I just had a quick look at it. It seems like as it's currently not possible to get this information.

I'll check the next days, how this can be implemented.

**Comment by Sebi94nbg** [comment]
The necessary changes have been finally implemented. See the pull request #653 for further information and an example.

**Comment by Sebi94nbg** [comment]
This feature/change has been released in version [4.5.0](https://github.com/barbushin/php-imap/releases/tag/4.5.0).
