### ISSUE TITLE
Any way to remove all quoted mails (previous mails from a thread)?

### ISSUE THREAD

**Issue by dejan7** [barbushin/php-imap#53]
Consider this scenario:
A) I send email to example@example.com
B) He replies to my mail

Now in that email that i received using your class i have in $email->textPlain:

```
Hello this is a reply from example@example.com
Lorem ipsum.

On 2015/0723/ dejan7 said:
> this is the first email
> i sent to example@example.com
```

Is there any way to get only contents of the message that example@example.com wrote i.e.:

```
Hello this is a reply from example@example.com
Lorem ipsum.
```

?

Is it somehow stored in email parts? The problems is that different clients mark the old emails differently. Some use > and some use } etc. etc. Also some include the line "On 2015/0723/ dejan7 said:" in various formats or don't include it at all! 

Great class BTW, it works great, i'm just wondering if this is somehow possible. Thanks!

**Comment by surgiie** [comment]
@christatedavies curious to see if you have expanded on this function?

**Comment by usmanolm** [comment]
> Consider this scenario: A) I send email to [example@example.com](mailto:example@example.com) B) He replies to my mail
> 
> Now in that email that i received using your class i have in $email->textPlain:
> 
> ```
> Hello this is a reply from example@example.com
> Lorem ipsum.
> 
> On 2015/0723/ dejan7 said:
> > this is the first email
> > i sent to example@example.com
> ```
> 
> Is there any way to get only contents of the message that [example@example.com](mailto:example@example.com) wrote i.e.:
> 
> ```
> Hello this is a reply from example@example.com
> Lorem ipsum.
> ```
> 
> ?
> 
> Is it somehow stored in email parts? The problems is that different clients mark the old emails differently. Some use > and some use } etc. etc. Also some include the line "On 2015/0723/ dejan7 said:" in various formats or don't include it at all!
> 
> Great class BTW, it works great, i'm just wondering if this is somehow possible. Thanks!




i have the solution which have only work for text email not working for html email

 public static String extractMostRecentReply(Messaging.InboundEmail email) {
        
        String replyBody = email.htmlBody;//email.plainTextBody != null ? email.plainTextBody: '';
        
        List<String> lines = replyBody.split('\n');
        String mostRecentReply = '';
        Boolean foundReplyStart = false;
        
        List<String> headerPatterns = new List<String>{
            'On ', 'From ', 'Sent ', 'Date ', 'To ', 'Subject: ','[: ','-: ','wrote:'};
                
                for (Integer i = lines.size() - 1; i >= 0; i--) {
                    String line = lines[i].trim();
                    Boolean isHeader = false;
                    
                    for (String pattern : headerPatterns) {
                        if (line.startsWith(pattern)) {
                            isHeader = true;
                            break;
                        }
                    }
                    
                    if (isHeader) {
                        continue;
                    }
                    if (line.startsWith('>')) {
                        foundReplyStart = true;
                    } else if (foundReplyStart) {
                        mostRecentReply = line + '\n' + mostRecentReply;
                    } else {
                        mostRecentReply = line + '\n' + mostRecentReply;
                    }
                }
        
        
        return mostRecentReply.trim();
        
    }
