### ISSUE TITLE
[DOCUMENTATION] attachment names have been changed to *.bin since 3.1.0

### ISSUE THREAD

**Issue by gitstashgithub** [barbushin/php-imap#533]
Hi,

3.1.0 changed the downloadAttachment function in Mailbox.php. Now the attachment file name is randomstring.bin, rather than the original file base name and extension name. This change is also not listed in the release log.

Thanks

**Comment by bapcltd-marv** [comment]
the change is not a bug, this was done to fix #448, as well as relating to the bugs that occur with emails having multiple attachments with the same filename overwriting each other.

**Comment by bapcltd-marv** [comment]
documentation and release notes are a separate matter, however.

**Comment by gitstashgithub** [comment]
Thank you for your reply. Since the attachment extension name was correct, my code only updated the attachment base name, so this fix actually broke it. It's very easy to fix, but I just think it's worth to mention any possible breaking changes in the release notes.

**Comment by aheman** [comment]
> Thank you for your reply. Since the attachment extension name was correct, my code only updated the attachment base name, so this fix actually broke it. It's very easy to fix, but I just think it's worth to mention any possible breaking changes in the release notes.

I've just stumbled into this change myself. It seems like IncomingMailAttachment->fileExtension worked for me for referencing images the extension for jpg, gif, png, but something about a pdf is not returning pdf but instead .bin. I must be missing something obvious for the fix.

**Comment by bapcltd-marv** [comment]
can't recall 100% off the top of my head, but it may be related to fileinfo rather than looking at the original extension ?

**Comment by aheman** [comment]
It seems like whatever I was doing originally to check the extension that I had wasn't doing anything any better than just taking it off the filename at this point.

**Comment by geoff-maddock** [comment]
New to this package, but in testing it out, I'm running into a similar issue:  any file saved ends up being _12345.bin_ rather than the attached filename.

**Comment by Sebi94nbg** [comment]
There is only the documentation in form of code:
https://github.com/barbushin/php-imap/blob/13bdfa9a6f541798253e24e2d8f44332c8be098c/src/PhpImap/Mailbox.php#L1404-L1408

...but this might will change in the future again: #645

So at the moment, you can for example change this behaviour to use the original file name like this:
```php
// Create PhpImap\Mailbox instance for all further actions
$mailbox = new PhpImap\Mailbox(
	'{imap.gmail.com:993/imap/ssl}INBOX', // IMAP server and mailbox folder
	'some@gmail.com', // Username for the before configured mailbox
	'*********', // Password for the before configured username
	__DIR__, // Directory, where attachments will be saved (optional)
	'UTF-8', // Server encoding (optional)
	true, // Trim leading/ending whitespaces of IMAP path (optional)
	true // Attachment filename mode (optional; false = random filename; true = original filename)
);
```
