### ISSUE TITLE
textHtml and textPlain both NULL

### ISSUE THREAD

**Issue by Regentix** [barbushin/php-imap#538]
Hello, I'm currently using [this example](https://github.com/barbushin/php-imap/blob/master/examples/get_and_parse_unseen_emails.php) to retrieve all "UNSEEN" emails from an office365 mailbox.

It works fine for marketing emails and other emails that contain valid HTML, but whenever I simply send a mail e.g. "Hello world" trough my mail client to the corresponding mail address, the mail is successfully retrieved trough imap, but the textPlain and textHtml are both NULL.

I'm not sure why this is the case, but I was wondering if there is a fix for this, as I need it to work in both cases.

Thanks in advance.

**Comment by bapcltd-marv** [comment]
This may have already been resolved on the dev branch.

**Comment by Regentix** [comment]
Issue is fixed, I was using [secit-pl/imap-bundle](https://github.com/secit-pl/imap-bundle) which uses "php-imap/php-imap": "~2.0|~3.0". I've removed the bundle and required php-imap/php-imap latest version.
