### ISSUE TITLE
[BUG] Encoding not detected

### ISSUE THREAD

**Issue by ekstrakt** [barbushin/php-imap#539]
**Environment:**
 - PHP IMAP version: 4.1.0
 - PHP Version: 7.2.11
 - Type of execution: Web request (Apache)

**Describe the bug**
After upgrading from 3.1.0 to 4.1.0, I've noticed that mails do not have proper encoding and have question mark characters when output to screen. The mails are coming from Gmail account.

**The used code:**
```php
$mailbox = new Mailbox(
	'{imap.gmail.com:993/imap/ssl}INBOX',
	'johndoe@gmail.com', 
	'password'
);  
$mail = $mailbox->getMail(5498, false);		
echo $mail->textPlain;
//echo $mail->textHtml;
```
Same code works fine with version 3.1.0.

**Expected behavior**
Encoding should be properly set.

**Screenshots**

![phpimap3 1](https://user-images.githubusercontent.com/4181656/90083503-010d7e00-dd13-11ea-8bc8-00158378cf36.png)

![phpimap4 1](https://user-images.githubusercontent.com/4181656/90083517-079bf580-dd13-11ea-9c71-c64b4162ff38.png)
Btw, those letters are croatian (ć and č)

**Email in question:**  
[pastebin](https://pastebin.com/32zknu7a) or as zip [allorder 24.7.v2.zip](https://github.com/barbushin/php-imap/files/5066668/allorder.24.7.v2.zip)

**Comment by bapcltd-marv** [comment]
do the master or dev branches make a difference?

**Comment by ekstrakt** [comment]
No, I'm getting same as with the 4.1.0 release

**Comment by Sebi94nbg** [comment]
This might have been already fixed in a newer release. Closing this issue for now.

Feel free to re-open it, if you should still have this issue in the release [4.3.0](https://github.com/barbushin/php-imap/releases/tag/4.3.0) and newer.
