### ISSUE TITLE
Encoding Issues Driving Me Insane!

### ISSUE THREAD

**Issue by glenelkins1984** [barbushin/php-imap#543]
Hi

I like this library but i am going insane with the encoding. Pulling 5000 emails from GMAIL works fine, but a lot of the html has encoding problems. I can't even seem to convert it all to proper UTF-8 with mbstring or utf8_encode, i just still have weird characters all over the place. I also can't just insert the html directly as the utf8 database wont' accept it.

There must be a way to have the emails displaying properly! Can someone help me here, ideally i should be able to just get the encoding from the message object, something like:

/** @var PhpImap\IncomingMail */
$mesaage->getEncoding()

But there doesn't seem to be such a thing on the IncomingMail object, if i could know what the encoding was then i could use mbstring to convert it properly.

**Comment by bapcltd-marv** [comment]
I think the issue with that approach is different chunks of the message can be encoded differently- you'd need to be able to inspect 
`DataPartInfo::$charset` on all `IncomingMail::$dataInfo` entries.

**Comment by glenelkins1984** [comment]
Thanks for the reply.

So how do i do that then? What you're describing is some static properties, but i'm looping over IncomingMail objects and there is no $mailObj->charset ?

**Comment by bapcltd-marv** [comment]
> Thanks for the reply.
> 
> So how do i do that then? What you're describing is some static properties, but i'm looping over IncomingMail objects and there is no $mailObj->charset there is also no property $mailObj->dataInfo ?
> 
> This is after pulling a mail in like so:
> 
> ```
> $remoteEmail = $imap->getMail($mailId,false);
> ```
> 
> So in my example $remoteEmail->charset and $remoteEmail->dataInfo both do not exist.

I'm referring to class properties, not static properties- specifically:

https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/IncomingMail.php#L35
https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/DataPartInfo.php#L38

**Comment by glenelkins1984** [comment]
Thanks, so $dataInfo is protected so how am i supposed to access that information? I don't see a public method that returns it.

**Comment by bapcltd-marv** [comment]
> There must be a way to have the emails displaying properly! Can someone help me here, ideally i should be able to just get the encoding from the message object, something like:
> 
> /** @var PhpImap\IncomingMail */
> $mesaage->getEncoding()

You proposal would need to be modified (at least in part) to either make these methods directly accessible, or to add a method into `IncomingMail` to collate the various `DataPartInfo::$charset` properties (although I'm unsure if they'd be impacted by `DataPartInfo::$encoding`)

A property would need to be routed through magic getters, and a method's return type would need to be defined for single body + single charset, multiple body + single charset, and multiple body + multiple charset.

The proposed technique would also likely need to account for non-inline text-based attachments.

**Comment by glenelkins1984** [comment]
ok, i was hoping the library would literally just have the html body encoding set on it without all this messing around.

**Comment by hrst** [comment]
I think I found the issue: decodeMimeStr() is called via convertEncodingAfterFetch(). However, at this point in time, the string no longer has the MIME header info. Hence, using imap_mime_header_decode() in decodeMimeStr() will not work and it then does not convert the encoding.

https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/DataPartInfo.php#L111

https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/Mailbox.php#L1347

**Comment by dwalczyk** [comment]
@hrst do make request, your fix is working to me

**Comment by jmbianca** [comment]
@hrst Hi, your fix works well for me too. Is there any plan to merge it soon?

**Comment by Sebi94nbg** [comment]
I've created a merge request with those changes and merged it into the `develop` branch. Feel free to test the changes using the `develop` branch.

**Comment by Tanktiger** [comment]
@Sebi94nbg When will there be a new release with this fix in it?

**Comment by hrst** [comment]
I've just updated and the new version actually re-introduces the problem:

https://github.com/barbushin/php-imap/blob/f401d85c8a6b034e8ee566e73cb948dd9e9298be/src/PhpImap/DataPartInfo.php#L111-L114

decodeMimeStr() is called with a second parameter, but the method does not even have it?

Also here:

https://github.com/barbushin/php-imap/blob/fb8be2311418176a063a89385f10f2e22d30e287/src/PhpImap/Mailbox.php#L1262

I'm very confused on what the intention here was. Am I missing something and a second decodeMimeStr() method exists somewhere that does have the second parameter? I could not find it.

**Comment by Sebi94nbg** [comment]
The `develop` branch has been merged into the `master` and released as version 4.3.0 six days ago. Please check again, if this issue still exists.

**Comment by hrst** [comment]
The current version has the same issues again, please check this comment for a fix:
https://github.com/barbushin/php-imap/issues/657#issuecomment-1036465886

**Comment by Sebi94nbg** [comment]
I've just released a new version [4.5.3](https://github.com/barbushin/php-imap/releases/tag/4.5.3) with some more improvements regarding these encoding issues and some unit tests.

Relates to #657.

Feel free to reopen this issue, if you should be still able to reproduce your issue(s) or just open a new ticket.
