### ISSUE TITLE
cid images

### ISSUE THREAD

**Issue by steveyout** [barbushin/php-imap#544]
**Environment (please complete the following information):**
 - PHP IMAP version: [>3.0.33, 4.x]
 - PHP Version: [7.4]
 - Type of execution: [apache Web Server]

**Your Text**
how do i get to diplay images with `cid:....filename` on browser?

**Comment by Sebi94nbg** [comment]
I'll close this now due to inactivity / no feedback. Feel free to re-comment this or create a new issue.
