### ISSUE TITLE
How To Use Proxy

### ISSUE THREAD

**Issue by LiuMicah** [barbushin/php-imap#545]
Thank you for your contribution! I'am' want to use proxy,  But I'm not found any method, Thank you!

**Comment by kv4nt** [comment]
> Thank you for your contribution! I'am' want to use proxy, But I'm not found any method, Thank you!

Hello! Use proxychains  https://www.linuxbabe.com/desktop-linux/how-to-use-proxychains-to-redirect-your-traffic-through-proxy-server

**Comment by Sebi94nbg** [comment]
You need to configure the proxy on the server side, not in the `php-imap` library.

Relates to https://github.com/barbushin/php-imap/issues/328.
