### ISSUE TITLE
Using X-GM-RAW in extension

### ISSUE THREAD

**Issue by amarianski** [barbushin/php-imap#546]
Hi, have you checked if X-GM-RAW commands are working? In normal php-imap extension it won't for me. Only using socket connection works.

**Comment by Sebi94nbg** [comment]
Since this library is using the PHP built-in IMAP functions, this is not supported. See https://stackoverflow.com/questions/26131700/how-to-do-an-imap-search-based-on-delivered-to-header-or-how-to-use-the-gmail.
