### ISSUE TITLE
Can't get emails using the "UNSEEN or NEW" status 

### ISSUE THREAD

**Issue by raliqala** [barbushin/php-imap#547]
- PHP IMAP version: [4.1]
 - PHP Version: [7.2.5]
 - Type of execution: [Web Server]

I want to get all the (UNSEEN/NEW) emails in my outlook inbox but am getting an error
```An error occured: Could not search mailbox!```
I want to do this because I have a high number of emails so I just want to take the new or unseen ones

Thanks  in advance
To be precise i have 75 000 emails and 500 unseen
i run my endpoints on PostMan and Insomnia design i get same error
![MicrosoftTeams-image](https://user-images.githubusercontent.com/30502407/93743602-9d6b5000-fbf0-11ea-9daf-ba6af6fd4c25.png)

**Comment by bapcltd-marv** [comment]
does it make a difference if you add in date-limiting criteria ?

**Comment by LavoTP** [comment]
Yes it works like that

**Comment by bapcltd-marv** [comment]
then it's possibly a "too much data at once" thing?

**Comment by LavoTP** [comment]
Yes. but if we use unseen we will be getting about 400 emails

**Comment by Sebi94nbg** [comment]
Do you still have this issue with the latest version @raliqala ?

**Comment by raliqala** [comment]
No. Thank you
