### ISSUE TITLE
[BUG] Not trapping 'imap_open()' warning in some environments - script stops

### ISSUE THREAD

**Issue by MDBenson** [barbushin/php-imap#553]
**Environment (please complete the following information):**
 - PHP IMAP version: 4.1.0
 - PHP Version: 7.2.24
 - Type of execution: Web Server or CLI

**Describe the bug**
In some PHP Environments (in my case FatFreeFramework 3.6) a failed imap_open() command throws a Warning level error that halts the PHP script because it is not trapped.

**To Reproduce**
Instantiate a new Mailbox connection using bad details as below. In some environments the script will halt with a stack trace.

The used code:
```
$mailbox = new \PhpImap\Mailbox(
            '{thisisnotvalid.testmail.com:143/imap}Bogus', // IMAP server and mailbox folder
            'rubbish@testmail.com', // Username for the before configured mailbox
            'ThisIsntTheRightPassword'
        );
```

**Expected behavior**
This should be trapped and processed as a \PhpImap\ConnectionException possibly?

**Screenshots / Outputs**

```
Internal Server Error

imap_open(): Couldn't open stream {thisisnotvalid.testmail.com/imap}Bogus

[/somepath/src/vendor/bcosca/fatfree-core/base.php:2261] Base->error()
[/somepath/src/vendor/php-imap/php-imap/src/PhpImap/Imap.php:708] imap_open()
[/somepath/src/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:1592] PhpImap\Imap::open()
[/somepath/src/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:1553] PhpImap\Mailbox->initImapStream()
[/somepath/src/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:436] PhpImap\Mailbox->initImapStreamWithRetry()
[/somepath/src/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:621] PhpImap\Mailbox->getImapStream()
......
```

**Additional context**
My stack is running with FatFreeFramework 3.6 with debug on (on my Dev server) which may contribute to the issue. This issue strictly speaking effects imap_open() not PhpImap but it might be nice to trap the error to an exception?

**Possible Fix**

Add
```
\set_error_handler(function() {
     $lastError = \imap_last_error();
            
     throw new Exceptions\ConnectionException("IMAP connection could not be established: " . $lastError);
});
```
directly before imap_open()

then

```
\restore_error_handler();
```
directly afterwards.

This traps and handles the error gracefully via a trappable Exceptions\ConnectionException which can be handled more easily and uses imap_last_error() to offer a more descriptive eror message for example:

```
IMAP connection could not be established: Can not authenticate to IMAP server: AUTHENTICATE failed.
[/somepath/src/vendor/php-imap/php-imap/src/PhpImap/Imap.php:705]
```

**Comment by bapcltd-marv** [comment]
> with debug on (on my Dev server) 

that's probably loading it's own error handler that intercepts ext-imap triggering an error instead of throwing an exception.

**Comment by MDBenson** [comment]
Okay, that makes sense, I'll refer this to the FatFree maintainers and see what they can give me.
