### ISSUE TITLE
How to send IMAP ID Command to mail server

### ISSUE THREAD

**Issue by hsu1943** [barbushin/php-imap#555]
**Environment:**
 - PHP Version: 7.2.31
 - yiisoft/yii2 2.0.35
 - php-imap/php-imap 4.0.0

some special mail server need **ID Command** to confirm request ID.
otherwise i can't get any mails from any mailbox.

somebody know how to send ID Command by this package？

help me please ^ ^

ID Command from [RFC 2971 - IMAP4 ID extension](https://tools.ietf.org/html/rfc2971)

**Comment by bapcltd-marv** [comment]
If I recall correctly, some IMAP commands aren't supported because this package (and many others) uses the PHP imap extension to provide functionality, rather than using a direct socket connection over which commands are issued.

If a feature cannot be implemented with the [list of available functions](https://www.php.net/manual/en/ref.imap.php), then it can't be implemented without said direct socket connection.

**Comment by hsu1943** [comment]
> If I recall correctly, some IMAP commands aren't supported because this package (and many others) uses the PHP imap extension to provide functionality, rather than using a direct socket connection over which commands are issued.
> 
> If a feature cannot be implemented with the [list of available functions](https://www.php.net/manual/en/ref.imap.php), then it can't be implemented without said direct socket connection.

Yes, php imap extension didn't support some commands includ ID Command.

Thanks for your reply. I tried python can do it.

**Comment by LuMitchell** [comment]
> > If I recall correctly, some IMAP commands aren't supported because this package (and many others) uses the PHP imap extension to provide functionality, rather than using a direct socket connection over which commands are issued.
> > If a feature cannot be implemented with the [list of available functions](https://www.php.net/manual/en/ref.imap.php), then it can't be implemented without said direct socket connection.
> 
> Yes, php imap extension didn't support some commands includ ID Command.
> 
> Thanks for your reply. I tried python can do it.

You can try pop3, I use pop3 instead, it works!
