### ISSUE TITLE
[BUG] attachments no cleaned on tmp folder

### ISSUE THREAD

**Issue by kamyweb** [barbushin/php-imap#556]
**Environment:**
 - PHP IMAP version: php7-imap-7.2.5-lp150.2.27.1.x86_64
 - PHP Version: 7.2.5
 - Type of execution: Daemon

**Describe the bug**
all files attaches to emails remains on /tmp folder as <random>.bin
I also haven't any way to get the physical name of the file from IncomingMailAttachment class to manual unlink it.

**To Reproduce**
```php
$mailbox = new \PhpImap\Mailbox(
    '{'.$this->imapHost.'/imap/ssl}INBOX', // IMAP server and mailbox folder
    $this->imapUsername, // Username for the before configured mailbox
    $this->imapPassword, // Password for the before configured username
    sys_get_temp_dir(), // Directory, where attachments will be saved (optional)
    'UTF-8' // Server encoding (optional)
);
$mailbox->setConnectionArgs(
    CL_EXPUNGE // expunge deleted mails upon mailbox close
);

$messages = $mailbox->sortMails();
foreach ($messages as $messageUID) {
    $mail = $mailbox->getMail($messageUID, false);
    if ($mail->hasAttachments()) {
        $attachments = $mail->getAttachments();
        foreach ($attachments as $attachNumber => $attachment) {
            $nomefile = basename($attachment->name);
            $nuovo_nomefile = __DIR__ . '/fileCaricamento/' . time() . '_' . $messageUID . '_' . $attachNumber . '.' . strtolower(pathinfo($nomefile, PATHINFO_EXTENSION));
            $attachment->setFilePath($nuovo_nomefile);
            if ($attachment->saveToDisk()) {
                $filesImport[] = $nuovo_nomefile;
            }
        }
    }
}
$mailbox->disconnect();
```
**Expected behavior**
After disconnect the tmp folder become empty

**Screenshots / Outputs**
![image](https://user-images.githubusercontent.com/8101573/98789500-a7e0e380-2402-11eb-8680-f29d55248874.png)

**Comment by bapcltd-marv** [comment]
store `$attachment->file_path` before overwriting it?

**Comment by kamyweb** [comment]
> store `$attachment->file_path` before overwriting it?

file_path is private

**Comment by bapcltd-marv** [comment]
it's accessible via the getter: https://github.com/barbushin/php-imap/blob/7ca3d19451bfe6de47186b52f4b266179a5858b9/src/PhpImap/IncomingMailAttachment.php#L86

**Comment by Sebi94nbg** [comment]
Is this topic solved or still open @kamyweb?

**Comment by Sebi94nbg** [comment]
I'll close this as there is a way to delete these files. See above conversation.
