### ISSUE TITLE
[BUG] Error Control Operator

### ISSUE THREAD

**Issue by rambco** [barbushin/php-imap#557]
Hi, I noticed that the error control operator in the files is backslash and not @ 
While I was using the class I could not understand why the errors were not collected by the try and catch, checking the sources I noticed this.

**Comment by bapcltd-marv** [comment]
errors are not exceptions, only exceptions are collected by try & catch blocks.

is there a particular error that's not being handled by the existing code?

**Comment by rambco** [comment]
in source file the Error Control Operator is '\'

example 
$result = \imap_open($mailbox, $username, $password, $options, $n_retries, $params);

if i susbtitute in 
$result = @imap_open($mailbox, $username, $password, $options, $n_retries, $params);

the application work.... what is the '\'

**Comment by bapcltd-marv** [comment]
backslash is not an error control operator, it's an namespace escaping operating; avoids the style of function imports where one adds `use function imap_open;` at the top of the file.

**Comment by rambco** [comment]
and why in my piece of code

			try {

				$mailsIds = $mailbox->searchMailBox('UNSEEN');

				$mails = $mailbox->getMailsInfo($mailsIds);
				$response = array_reverse($mails);
			} catch(PhpImap\Exceptions\UnexpectedValueException   $ex) {

				echo echo "Exception: " . $ex->getMessage();
				die();

			}catch(PhpImap\Exceptions\ConnectionException $ex) {
				echo "IMAP connection failed: " . $ex->getMessage();
				die();
			}

no execption where catchetd

**Comment by bapcltd-marv** [comment]
if an exception wasn't caught an exception wasn't thrown.

I'm still unclear what error you're experiencing?

**Comment by rambco** [comment]
I entered incorrect data in the configuration for connecting to the mail server to test for errors.
When executing the searchMailBox command several php warnings appear and ConnectionException is not thrown

**Comment by bapcltd-marv** [comment]
you'll want to add an error handler that throws some variant of `ErrorException` ?

**Comment by rambco** [comment]
[Code](https://ibb.co/xDZqc83)

[Results](https://ibb.co/PYNy2hF)

**Comment by bapcltd-marv** [comment]
> you'll want to add an error handler that throws some variant of `ErrorException` ?

see previous statement.

**Comment by AntonioDiPassio-AppSys** [comment]
> and why in my piece of code
> 
> ```
> 		try {
> 
> 			$mailsIds = $mailbox->searchMailBox('UNSEEN');
> 
> 			$mails = $mailbox->getMailsInfo($mailsIds);
> 			$response = array_reverse($mails);
> 		} catch(PhpImap\Exceptions\UnexpectedValueException   $ex) {
> 
> 			echo echo "Exception: " . $ex->getMessage();
> 			die();
> 
> 		}catch(PhpImap\Exceptions\ConnectionException $ex) {
> 			echo "IMAP connection failed: " . $ex->getMessage();
> 			die();
> 		}
> ```
> 
> no execption where catchetd

Because you write: echo echo in your first catch
