### ISSUE TITLE
Delete attachment files

### ISSUE THREAD

**Issue by egmen** [barbushin/php-imap#56]
Please, add a function to delete the attachment files after fetching the mail.

**Comment by stanma** [comment]
why for ? you can leave $attachmentsDir = '' and you'll get no attachments at all after parsing mailbox.

**Comment by barbushin** [comment]
I think @stanma is right :)

**Comment by egmen** [comment]
I want get attachments files. But I should manually delete them after using. My temp folder will have no space if I don't do this.
I want php-imap has it own garbage collector. If it creates attachments files itself, it should delete them before destroying or fetching next mail.

**Comment by barbushin** [comment]
Sorry, no way. php-imap is not mail management library, it's just about receiving incomings.

**Comment by daniel-adlantic** [comment]
Even just adding a method to delete downloaded attachment files would be an improvement.
But I agree with @egmen php-imap downloaded these files itself, why should I clean them up?
