### ISSUE TITLE
Uncaught Error: Undefined constant 'FILEINFO_RAW'

### ISSUE THREAD

**Issue by howitzer67** [barbushin/php-imap#561]
Example files work well on local host (with and without attachments).  Get error when running on Godaddy vps server and email has attachment.

"Fatal error: Uncaught Error: Undefined constant 'FILEINFO_RAW' in /home/newgreerhill/public_html/email1/Mailbox.php:1309 Stack trace: #0 /home/newgreerhill/public_html/email1/Mailbox.php(1685): PhpImap\Mailbox->downloadAttachment(Object(PhpImap\DataPartInfo), Array, Object(stdClass), false) #1 /home/newgreerhill/public_html/email1/Mailbox.php(1234): PhpImap\Mailbox->initMailPart(Object(PhpImap\IncomingMail), Object(stdClass), 2, false) #2 /home/newgreerhill/public_html/email1/etest.php(59): PhpImap\Mailbox->getMail(3229, false) #3 {main} thrown in /home/newgreerhill/public_html/email1/Mailbox.php on line 1309"

Code works on server when no attachments.  Any thoughts on how to solve?

**Comment by bapcltd-marv** [comment]
Do you have the fileinfo extension installed ?

**Comment by howitzer67** [comment]
Thank you very much.  Works great and now I am schooled in when to use WHM vs cPanel.
