### ISSUE TITLE
[Feature Request] PHP 8 support?

### ISSUE THREAD

**Issue by vladislavtkachenko** [barbushin/php-imap#563]
Hello, do you have any plans to support php 8?
Thank you for your work

**Comment by TheHett** [comment]
join the question

**Comment by vladislavtkachenko** [comment]
@TheHett alternative https://github.com/ddeboer/imap

**Comment by TheHett** [comment]
@vladislavtkachenko thanks, but I hope that php 8.0 support will be added soon. I can't migrate, I'm lazy.

**Comment by TheHett** [comment]
@barbushin could you provide information, will there be support?

**Comment by TheHett** [comment]
ok, I defeated laziness and moved

**Comment by akcoder** [comment]
> @vladislavtkachenko thanks, but I hope that php 8.0 support will be added soon. I can't migrate, I'm lazy.

Migration was easy. Took me < 30 minutes, and a fair bit of that time was spent figuring out how I wanted to re-work my code to make it testable.

**Comment by blu-towers** [comment]
any update on when this pull request will be added?

**Comment by Sebi94nbg** [comment]
I've merged it into `develop`. Feel free to test using the `develop` branch.

**Comment by fluxfw** [comment]
```
Fatal error: Uncaught TypeError: imap_sort(): Argument #3 ($reverse) must be of type bool, int given in ../vendor/php-imap/php-imap/src/PhpImap/Imap.php:927
```

**Comment by Sebi94nbg** [comment]
PHP 8.x support has been added with release 4.2.0.
