### ISSUE TITLE
[BUG] Set private property $textPlain of IncomingMail

### ISSUE THREAD

**Issue by lexdewilligen** [barbushin/php-imap#568]
**Environment:**
 - PHP IMAP version: 4.1.0
 - PHP Version: 7.3
 - Type of execution: CLI

**Describe the bug**
We used to be able to set textPlain of an IncomingMail to test our application. However, since this property has been made private, how are we supposed to set the contents of textPlain?

The used code:
```php
$incomingMail =  new IncomingMail();
$incomingMail->id = 1;
$incomingMail->fromAddress = 'info@example.com';
$incomingMail->textPlain = 'Some mail content';
```

**Comment by michaljusiega** [comment]
Field is private, but available are magic methods:  `__get()` and `_isset()`.

See: 
https://github.com/barbushin/php-imap/blob/master/src/PhpImap/IncomingMail.php#L51
https://github.com/barbushin/php-imap/blob/master/src/PhpImap/IncomingMail.php#L85
