### ISSUE TITLE
[BUG] Inline image not showing when part headers limited to ID

### ISSUE THREAD

**Issue by Polfo** [barbushin/php-imap#569]
**Environment (please complete the following information):**
 - PHP IMAP version: 4.1.0
 - PHP Version: 7.4.9

**Describe the bug**
When an embedded image has these headers:
```
------BC4EDC515F4648C3A810A20589F43DB9
Content-Transfer-Encoding: base64
Content-Type: image/png
Content-ID: <CFT0104_09040205BD4.png>

iVBORw0KGgoAAAANSUhEUgAAArwAAAD6CAYAAABDJJQbAAAAAXNSR0IArs4c6QAAAAlwSFlzAAAO
wwAADsMBx2+oZAAAJiBJREFUeF7t3c+yG8d1x/H7Il7GeYjYi1vkZRZepVwue5cqh1qEpPhX27xA
...
```

After using
` $mail->embedImageAttachments();`

`<img src="cid:CFT0104_09040205BD4.png">` is not modified to an inline image.

- because the attachment is not parsed due to the expected `filename `or `name` parameters
`$isAttachment = isset($params['filename']) || isset($params['name']);`

- because, even when the attachment is parsed, it is not embedded due to the missing `Content-Disposition: inline;`
 `if ($attachment->contentId == $cid && 'inline' == $attachment->disposition)`

**Expected behavior**
Both my [mail provider webmail](https://webmail.combell.com/) and [Google mail](https://mail.google.com/) show the image for these mails. I cannot ask the mail sender to modify the headers, so it would be nice to have these attachments converted to inline by `php-imap` also.

**Note**
It works as expected with headers like this
```
--_004_BD8D5EA933DFF945B7C5A0C5069DD6C559158F3CLINEAEXC01linea_
Content-Type: image/jpeg; name="image001.jpg"
Content-Description: image001.jpg
Content-Disposition: inline; filename="image001.jpg"; size=2956;
	creation-date="Thu, 31 Dec 2020 15:05:43 GMT";
	modification-date="Thu, 31 Dec 2020 15:05:43 GMT"
Content-ID: <image001.jpg@01D6DF8E.F9E3BC10>
Content-Transfer-Encoding: base64

/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAoHBwkHBgoJCAkLCwoMDxkQDw4ODx4WFxIZJCAmJSMg
IyIoLTkwKCo2KyIjMkQyNjs9QEBAJjBGS0U+Sjk/QD3/2wBDAQsLCw8NDx0QEB09KSMpPT09PT09

```

**Comment by grimmlink** [comment]
I also have a bug with the line :

`if ($attachment->contentId == $cid && 'inline' == $attachment->disposition)`

the disposition is set as INLINE, not inline though doesn't match... this quick fix would work for me too

**Comment by Sebi94nbg** [comment]
I've created a merge request with the necessary changes and merged it into the `develop` branch. Feel free to test it using the `develop` branch.

Relates to #519.

**Comment by Polfo** [comment]
I have tested e933796. It is very similar to my pull request b378ddf and it works. Thanks.

**Comment by kurznet** [comment]
` if ($attachment->contentId == $cid || 'inline' == \mb_strtolower((string) $attachment->disposition)) {`
this line is also a problem if you have more than online inline image attachment in one email.
if this is the case then the first image is always placed in all inline images because of the `|| 'inline' == \mb_strtolower((string) $attachment->disposition)` 

please fix in a future release
