### ISSUE TITLE
IMAP IDLE / NOTIFY extension

### ISSUE THREAD

**Issue by tetrode** [barbushin/php-imap#57]
Hi

I would like to use this library, but I need IMAP IDLE / NOTIFY as described in http://tools.ietf.org/html/rfc5465.

What effort would it be to implement this?

Mark

**Comment by Sebi94nbg** [comment]
As already stated: This is not possible for PHP scripts, which runs on a web server.

You can build such a functionality by using the PHP functions [`imap_ping`](https://www.php.net/manual/en/function.imap-ping.php) and [`imap_check`](https://www.php.net/manual/en/function.imap-check.php) for PHP scripts, which will be executed on the CLI (as a daemon).

All PHP IMAP functions can be called / used by `php-imap` like this:
```php
$mailbox->imap('ping');
$mailbox->imap('check');
```

Below an untested example code:
```php
RECONNECT:
// Connect to mailbox
$mailbox = new PhpImap\Mailbox('{imap.gmail.com:993/imap/ssl}INBOX', 'some@gmail.com', '*********', __DIR__);

CHECKMAILS:
// Search unseen (unread) mails
$mailsIds = $mailbox->searchMailbox('UNSEEN');

if(!$mailsIds) {
	echo 'Mailbox is empty. Waiting 60 seconds until next check...\n';
        sleep(60);

       // Clear IMAP cache to prevent high memory consumption
       $mailbox->imap('gc', array(IMAP_GC_ELT));

       if(!$mailbox->imap('ping')) {
              goto RECONNECT;
       }

       $mailbox_check = $mailbox->imap('check');

       if($mailbox_check->Recent > 0) {
              echo 'New emails arrived. Parsing them...\n';
              goto PARSEEMAILS;
       }
}

// Parse emails
PARSEEMAILS:
foreach($mailsIds as $mailId) {
       $mail = $mailbox->getMail($mailId);

       // Do something with $mail; eg. saving to database, sending autom. responses, ...
}

// Go back and check for new emails
goto CHECKMAILS;
```

Please note, that you should add a logic to restart the PHP script after some time.

---
References:
- https://stackoverflow.com/questions/1093066/support-for-imap-idle-in-php

**Comment by dartrax** [comment]
@Sebbo94BY: Could you update your example code, as `$mailbox->imap('ping');` does not work any more because the imap-function got removed (refactored?) in commit dab9937d060f6f111db6d7acd6623388e05792e2 ? Thanks :)
