### ISSUE TITLE
Get only reply attachemtns

### ISSUE THREAD

**Issue by Arlovas** [barbushin/php-imap#573]
I was wondering if there's a way to `getAttachments()`  only for the current message. When I got a reply  and use getAttachments i get all the previous attachments as well. 

I'm planning to filter the already seen attachments by the contentId. My question is, there's a way to get the attachments only for the current mail/reply ?

**Comment by Sebi94nbg** [comment]
You are usually calling this function on a single mail, so you only should get the attachments for a single mail - not a thread/conversation.

```php
// Get any message
// In this example, we will just take the first one
$mail = $mailbox->getMail($mailsIds[0]);

// Show, if $mail has one or more attachments
echo "\nMail has attachments? ";
if($mail->hasAttachments()) {
	echo "Yes\n";
} else {
	echo "No\n";
}
```

Are those attachments maybe always a part of the previous mail from the thread in your case? When somebody replies or forwards an email, it's always possible to keep the attachments from the mail to which you reply. Some mail clients keep those attachments by default.

**Comment by sunnyzss928** [comment]
Pictures and attachments cannot be displayed in my email details. Why?

I found that the suffixes of attachments saved locally have become  .bin

**Comment by Sebi94nbg** [comment]
Closing this due to no feedback.
