### ISSUE TITLE
[BUG] textHtml returns NULL in some cases 

### ISSUE THREAD

**Issue by saadmehmood** [barbushin/php-imap#581]
**Environment (please complete the following information):**
 - PHP IMAP version: 4.1
 - PHP Version:7.3
 - Type of execution: Web Server

**Describe the bug**
I was using version 3.0 and got issue of both textHtml and textPlain was null so I updated to php-imap to version 4.1, my issue got fixed, but now I am facing an issue for texthtml is null for few mails only even same other mails return textHtml. dont know the exact reason of issue, I have checked the origin message, it contains both parts textPlain and textHtml as well. Is there any solution for this issue. I am using php -imap with symfony 3.4

The used code:
```php
$mailbox = new Mailbox($mailboxUrl, $mailboxUser, $mailboxPassword, $mailAttachmentsDir);
$newMailsIds = $mailbox->searchMailbox('UNSEEN');
foreach ($newMailsIds as $id) {
$incomingMail = $mailbox->getMail($id);
$plainText = $incomingMail->textPlain;
$htmlText = $incomingMail->textHtml;
}
```

**Comment by Sebi94nbg** [comment]
Did you also already test it with the `develop` branch? There is maybe already a fix for it.

**Comment by Sebi94nbg** [comment]
The version [4.3.0](https://github.com/barbushin/php-imap/releases/tag/4.3.0) has been released.

Due to no feedback, I'll close this issue now. Feel free to comment or re-open it, if the issue still persists.
