### ISSUE TITLE
[Feature Request] CC equivalent of toString

### ISSUE THREAD

**Issue by cjsfj** [barbushin/php-imap#582]
**Is your feature request related to a problem? Please describe.**
No. Just a convenience

**Describe the solution you'd like**
The `to` field of emails has a nice `toString` that compiles a string of all of the names and recipients in the `to` line of the email. It would be convenient if it was also available for the `cc`

**Describe alternatives you've considered**
Duplicating the code for toString and implementing it on my own. But there are many rules in place here that I think would be beneficial as a standard implementation

Thank you!

**Comment by Sebi94nbg** [comment]
Implemented. Check out the `develop` branch for now in order to test this.

`Cc` has now the same behaviour as `To`:
- `to` (Array) /  `toString`: (String)
- `cc` (Array) /  `ccString`: (String)

**Comment by Sebi94nbg** [comment]
This change is included in the release [4.3.0](https://github.com/barbushin/php-imap/releases/tag/4.3.0) and newer.
