### ISSUE TITLE
[Feature Request] PHP 8 Support

### ISSUE THREAD

**Issue by luchaninov** [barbushin/php-imap#587]
It works with PHP 8. Please update dependencies in composer.json

**Comment by themodernpk** [comment]
@luchaninov when can we expect php 8 support.

**Comment by luchaninov** [comment]
@themodernpk  I've made pull request a month ago:
https://github.com/barbushin/php-imap/pull/588

Now it's up to Sergey @barbushin

**Comment by Sebi94nbg** [comment]
Duplicate: #563
