### ISSUE TITLE
Move to Github actions, test pull requests

### ISSUE THREAD

**Issue by codedge** [barbushin/php-imap#592]
Any plans to move (or help needed) to move to Github Actions in favour of travis? And in connection to that also to run checks (code-style, unit tests, testing in general...) against all new PRs?

I'd be open to prep some PR if that is something that would help.

**Comment by Sebi94nbg** [comment]
Any improvements and refactorings are welcome. This project got quiet huge in the last year and we've already improved a lot, but I still have the feeling, that we could do much more.

I'm not that familiar with unit tests etc. at all, so @bapcltd-marv maybe needs to answer your question if that's better or makes more sense.

We also need to keep in mind, that only @barbushin is the admin/owner of this repository. Only he can do administrative stuff, if we need something for this.

**Comment by Sebi94nbg** [comment]
Closing this as we are already using Github actions. :)
