### ISSUE TITLE
Remove php 7.2

### ISSUE THREAD

**Issue by codedge** [barbushin/php-imap#593]
As php 7.2 is EOL and reading through issue #465 I wanted to give a _ping_ to remove 7.2. IMHO 7.3 could also be removed as it only receives security updates, and just prevents the code base to be updated with property type-hints.

If ok, I can create a PR, lmk.

**Comment by finwe** [comment]
Let me vote for this as it would make way to allow PHP 8 which is now blocked by other older dependencies.

**Comment by codedge** [comment]
So who is deciding if that should be done or not? I just want to know if I can create a PR which is then actually being merged 😉

**Comment by Sebi94nbg** [comment]
PHP 8.0 is already allowed in the `develop` branch: https://github.com/barbushin/php-imap/blob/develop/composer.json#L26

**Comment by finwe** [comment]
@Sebi94nbg I am not quite sure this change is enough without change of dependencies. Made the same in my fork and many of them had to be updated for composer to run. https://github.com/finwe/php-imap/commit/dce42bc7be7339e51b4c549bdb67f10fe59f1d69

(notice ~8.0 for more elegant 8.1 exclusion)

**Comment by finwe** [comment]
I am aware this discussion is a bit off-topic here, if needed, please point me to a more suitable place.

**Comment by bapcltd-marv** [comment]
I get the feeling that it'd be safer to jump from `^7.2 || ^8.0 <8.1` to `^8.1` because of the object type change- i.e. dropping a php version just because it's no longer supported when there's no syntax/code changes that need to be made is unhelpful to people stuck on legacy systems.

**Comment by finwe** [comment]
That's not plausible for reasons I describe above. Let's continue the discussion in a dedicated issue https://github.com/barbushin/php-imap/issues/599

**Comment by bapcltd-marv** [comment]
[this has proved to be quite possible](https://github.com/bapcltd/php-imap/actions/runs/881573667), so php 7.2 is a non-issue pending merge of #598

**Comment by Sebi94nbg** [comment]
I think, we can slowly get rid of PHP 7.2 and 7.3 starting next year since both versions are end of life now: https://www.php.net/supported-versions.php

I'll try to work on it in Q1/2022. If anyone should be faster: I'll be happy to merge the pull request. :)
