### ISSUE TITLE
Using deprecated php-cs-fixer methods

### ISSUE THREAD

**Issue by codedge** [barbushin/php-imap#594]
Using `PhpCsFixer\Config::create()` is deprecated and reported in [travis tests ](https://travis-ci.org/github/barbushin/php-imap/jobs/768740438).

Furthermore it seems code style haven't been fixed for some time.

**Comment by bapcltd-marv** [comment]
This is highlighted but not addressed by the github actions added in #598

**Comment by Sebi94nbg** [comment]
I've changed, improved and updated the php-cs-config.

See release [4.3.0](https://github.com/barbushin/php-imap/releases/tag/4.3.0) and newer.
