### ISSUE TITLE
[BUG] Type Error in error handling due to strict types

### ISSUE THREAD

**Issue by rmontagud** [barbushin/php-imap#602]
**Environment (please complete the following information):**
 - PHP IMAP version: 4.1.0
 - PHP Version:7.3.28
 - Type of execution: cli

**Describe the bug**
Uncaught TypeError: trim() expects parameter 1 to be string, bool given in -path-/vendor/php-imap/php-imap/src/PhpImap/Imap.php:707

When imap_last_error() is called in line 705 and returns false a TypeError exception is thrown on line 707 due to strict types

**To Reproduce**
Steps to reproduce the behavior.

The used code:
Not appliable

The headers of the parsed email, if required and possible (only, if it's NOT confidential):
Not appliable

**Expected behavior**
UnexpectedValueException that can be handled. TypeError exceptions shouldn't be handled in production code IMHO, `$lastError` should be checked to be a sting (because I assume you're not going to drop the stict types declaration)

**Screenshots / Outputs**
-

**Additional context**
-

**Comment by hrst** [comment]
Can confirm this, still not fixed. Is the project dead?

**Comment by rmontagud** [comment]
Related patch got merged in pull request #608
