### ISSUE TITLE
[BUG] 163mail 不能抓取邮件

### ISSUE THREAD

**Issue by yks-center** [barbushin/php-imap#607]
**Environment (please complete the following information):**
 - PHP IMAP version: [e.g. 3.0.11]
 - PHP Version: [e.g. 7.1.9]
 - Type of execution: CLI

**Describe the bug**
163邮箱可以连接邮箱但是获取getMailboxes方法无法获取到邮箱文件夹

**To Reproduce**
Steps to reproduce the behavior.

The used code:
```php
  $mailbox = new PhpImap\Mailbox(
  '{imap.163.com:143/imap/tls}INBOX', // IMAP server and mailbox folder
  '******@163.com', // Username for the before configured mailbox
  '**********', // Password for the before configured username
  __DIR__, // Directory, where attachments will be saved (optional)
  'UTF-8' // Server encoding (optional)
)
$mailbox->setTimeouts(60); //设置超时时间
$mailbox->setImapSearchOption(SE_FREE); //返回id为邮件序号
$folders = $mailbox->getMailboxes();
$mailTotal = $mailbox->countMails(); //邮箱邮件总数
echo "<pre>";
print_r($mailTotal);
print_r($folders);
die;

**Expected behavior**
163邮箱通过getMailboxes方法获取到邮箱文件夹

**Comment by LuMitchell** [comment]
https://github.com/barbushin/php-imap/issues/555#issuecomment-883259879

#555 
Use pop3 instead.
> 由于163使用的imap协议php扩展不支持，用pop3协议就可以了。

**Comment by Sebi94nbg** [comment]
Can you please specify this issue in English, so that everyone understands it and doesn't need to translate it?

**Comment by Sebi94nbg** [comment]
Ignoring this due to the missing requested translation.

(Yes, I could use a translation tool, but I could not verify, if the translation is at the end the expected text.)
