### ISSUE TITLE
UNSEEN gives me all emails

### ISSUE THREAD

**Issue by herlon214** [barbushin/php-imap#61]
Hello, following the example file.

```
$mailBox = new ImapMailbox('{pop.afilie.com.br:995/pop3/ssl/novalidate-cert}INBOX', 'herlon@afilie.com.br', 'lordbr01', dirname(__FILE__) . '/attch', 'utf-8');
$mails = array();

$mailsIds = $mailBox->searchMailBox("UNSEEN");
if(!$mailsIds) {
    die('Mailbox is empty');
}
var_dump($mailsIds);
```

Gives me all emailsId, but I just need UNSEEN e-mails. 
I'm using RoundCube to read emails, and I thing that the flags don't match.
Thanks in advance.

**Comment by naitsirch** [comment]
I have the same issue as @herlon214 and found this question at [stackoverflow](https://stackoverflow.com/a/13381337/1119601). It seems like there is a confusion between SEEN and RECENT flags in php's `imap_fetchbody`.
