### ISSUE TITLE
[BUG] ServerEncoding is ignored for Attachment Filenames

### ISSUE THREAD

**Issue by jonnsn** [barbushin/php-imap#613]
**Environment:**
 - PHP IMAP version: ? (unknown)
 - PHP Version: 7.4.24
 - Type of execution: CLI

**Describe the bug**
When fetching mails from an Imap Server any Mail-Content and Subject including Special Characters like e.g. german umlauts is totally fine. But Attachment Names containing special characters are wrong:
Ger▒t.jpg
should be:
Gerät,jpg

in Mailbox::decodeMimeStr the $charset is 'default' as Mailbox::downloadAttachment does not pass $charsetPreffered,  so nothing is done to convert the content.

**To Reproduce**
connect to a mailbox and fetch a mail with an attachment that contains special Characters. I guess the server should have an encoding other than UTF-8, e.g. iso-8859-1. Setting $serverEncoding in constructor to 'iso-8859-1' does not have any effect on this in my case.

**Expected behavior**
The filename should have correct encoding.

**Comment by Sebi94nbg** [comment]
Thanks for the bug report and merge request!

I've merged it into the `develop` branch. Feel free to test it. The change will be included in the next release.
