### ISSUE TITLE
Problem with outlook.office365.com

### ISSUE THREAD

**Issue by mdenitti** [barbushin/php-imap#616]
**Environment (please complete the following information):**
 - PHP IMAP version: latest
 - PHP Version: 7.4
 - Type of execution: Webserver

**Your Text**
Unknown: Can not authenticate to IMAP server: AUTHENTICATE failed.

Works fine with all imaps, but can't get it to work with office365... authentication always fails:
I'm using this host string:  $imapserver = "{outlook.office365.com:993/imap/ssl/novalidate-cert/authuser=".$imapuser."/user=".$imapuser."}INBOX";

Any suggestions?
Thx!!!

**Comment by Sebi94nbg** [comment]
My test code is still working fine with this format:
```php
$mailbox = "{outlook.office365.com:993/imap/ssl}Sent";
$mailbox_username = "my-inbox@outlook.com";
$mailbox_password = "secretPassword";

$mbox_connection = new Mailbox($mailbox, $mailbox_username, $mailbox_password, __DIR__ . '/files/');

try {
        $mbox_connection->setServerEncoding('US-ASCII');
} catch(InvalidParameterException $ex) {
        echo "Setting server encoding failed: " . $ex->getMessage() . "\n";
        die();
}

[...]
```

**Comment by mdenitti** [comment]
Thx guys, wil test this asap!
