### ISSUE TITLE
Why are the pictures of the email content encoded and saved? How can I use it to show it?

### ISSUE THREAD

**Issue by sunnyzss928** [barbushin/php-imap#617]
**Environment (please complete the following information):**
 - PHP IMAP version: [e.g. 3.0.11]
 - PHP Version: [e.g. 7.1.26]
 - Type of execution: [e.g. Daemon / CLI or Web Server]

**Your Text**
Attachments and pictures cannot be displayed in the content of my email
I am a Chinese student. This plugin is great, but there are a lot of things that you don't understand.

**Comment by Sebi94nbg** [comment]
Can you please specify the current situation and your expected result, that it's more clear what you want?

**Comment by sunnyzss928** [comment]
> Can you please specify the current situation and your expected result, that it's more clear what you want?

My e-mail attachment cannot be obtained!
I can’t get the attachment. The picture is the name that I replaced after I modified it.

Mailbox.php->downloadAttachment:

        if (null != $attachmentsDir) {
            // $fileSysName = \bin2hex(\random_bytes(16)).'.bin';
            // $filePath = $attachmentsDir.DIRECTORY_SEPARATOR.$fileSysName;
            // $filePath = $attachmentsDir.DIRECTORY_SEPARATOR.$attachment->name;
            $filePath = ROOT_PATH . 'public' .DS.'email_file/'.$attachment->name;
            if (\strlen($filePath) > 255) {
                
                $ext = \pathinfo($filePath, PATHINFO_EXTENSION);
                $filePath = \substr($filePath, 0, 255 - 1 - \strlen($ext)).'.'.$ext;
              
            }
            $attachment->setFilePath($filePath);
            $attachment->saveToDisk();
        }

**Comment by Sebi94nbg** [comment]
This sounds identical to your other issue #622. Thus, I would close this to get a better overview of the open issues, ok?
