### ISSUE TITLE
I have a question. If the checked mailbox list cannot be paginated! Do I need to save the checked email details in the local mysql?

### ISSUE THREAD

**Issue by sunnyzss928** [barbushin/php-imap#626]
**Environment (please complete the following information):**
 - PHP IMAP version: [e.g. 4.2.1]
 - PHP Version: [e.g. 7.3]
 - Type of execution: [e.g. Daemon / CLI or Web Server]

**Your Text**
I have a question. If the checked mailbox list cannot be paginated! Do I need to save the checked email details in the local mysql?

**Comment by Sebi94nbg** [comment]
This is currently not supported. See #464 for further information.

@sunnyzss928 for the future, please use the "issues" search first, before you create new issues, which already exists. If there already exists a similar issue, give this a +1 or something, but please avoid creating duplicate issues. Thank you.
