### ISSUE TITLE
need to move mail to another folder

### ISSUE THREAD

**Issue by sudsin95** [barbushin/php-imap#662]
public function moveMail($mailId, string $mailBox): void
    {
        Imap::mail_move($this->getImapStream(), $mailId, $mailBox, CP_UID);
        $this->expungeDeletedMails();
    }

how to get $mailId

**Comment by Sebi94nbg** [comment]
Please take a look at the wiki for getting started: https://github.com/barbushin/php-imap/wiki/Getting-Started

And see the examples: https://github.com/barbushin/php-imap/tree/master/examples
