### ISSUE TITLE
Incoming attachment

### ISSUE THREAD

**Issue by PavelSachenko** [barbushin/php-imap#673]
- PHP IMAP version: ["php-imap/php-imap": "^4.1",]
 - PHP Version: [7.4]
 - Type of execution: [incoming mail attachment]

Bug message:

finfo::buffer(): Failed identify data 0:JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=11, manufacturer=motorola, model=moto x4, orientation=upper-right, xresolution=164, yresolution=172, resolutionunit=2, software=payton_amz-user 9 PPWS29.69-26-5 a87fd release-keys, datetime=2022:04:06 14:29:54, GPS-Data]name use count (30) exceeded

Bug file: vendor/php-imap/php-imap/src/PhpImap/IncomingMailAttachment.php
Bug line: 140

**Comment by Synergie-RL** [comment]
Same issue already open : https://github.com/barbushin/php-imap/issues/548
