### ISSUE TITLE
[BUG] Fatal error: Uncaught ValueError: IMAP\Connection is already closed

### ISSUE THREAD

**Issue by eddi13** [barbushin/php-imap#680]
- PHP IMAP version: 5.0.0
 - PHP Version: 8.1.10

PHP Fatal error: Uncaught ValueError: IMAP\Connection is already closed in .../PhpImap/Mailbox.php:479
Stack trace:
#0 .../PhpImap/Mailbox.php(479): imap_ping()
#1 .../PhpImap/Mailbox.php(544): PhpImap\Mailbox->hasImapStream()
#2 .../PhpImap/Mailbox.php(187): PhpImap\Mailbox->disconnect()

**Comment by ghnp5** [comment]
Probably because of this: https://www.php.net/ChangeLog-8.php

Version 8.1.10

IMAP:
Fixed bug [GH-9309](https://github.com/php/php-src/issues/9309) (Segfault when connection is used after imap_close()).

**Comment by ghnp5** [comment]
To me, this happens because I'm calling `unset($mailbox)` which calls `$mailbox->destruct()` which will try to close the IMAP connection which I've already closed by invoking `$mailbox->disconnect()`.

**Comment by underdpt** [comment]
I can confirm this happens also with version 8.1.13.

**Comment by Sebbo94BY** [comment]
Should be fixed in version [5.0.1](https://github.com/barbushin/php-imap/releases/tag/5.0.1).

**Comment by applibs** [comment]
And what about: public static function ping($imap_stream): bool
 in Imap class?

**Comment by cracksalad** [comment]
The commit which fixes this issue has somehow been lost and is missing from branch 6.x-dev and the current 6.0.0 release. It is present in the master branch though. I am talking about this commit: https://github.com/barbushin/php-imap/commit/9857a1dc4c9c5f37c51ba2a63ce7cc2da9cab41b from 2022!

Could you please merge this commit again and create a new release? @Sebbo94BY
