### ISSUE TITLE
stdClass scope ignore

### ISSUE THREAD

**Issue by mickaelCOLLET** [barbushin/php-imap#80]
I don't understand why i have this error : 

Call to undefined function PhpImap\imap_search() in /var/www/htdocs/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 176

the stdClass is ignored

**Comment by DjMomo** [comment]
How did you solve your problem ?

**Comment by toddmbloom** [comment]
You need to recompile PHP with IMAP support.

**Comment by designloud** [comment]
I also am receiving this exact error.  It would be helpful if you posted your solution @mickaelCOLLET
