### ISSUE TITLE
Mailbox.php seems to not include IncomingMail.php

### ISSUE THREAD

**Issue by goosehub** [barbushin/php-imap#81]
Installing this onto my project, I found that I had to add this line at the top of Mailbox.php

    require('IncomingMail.php');

Else I get this error

    Fatal error: Class 'PhpImap\IncomingMail' not found in C:\wamp\www\hydra\Resources\php-imap\src\PhpImap\Mailbox.php on line 411

I did not use composer to install php-imap, so that may be the cause of this. Otherwise, please explain why I needed to add this line where it seems nobody has needed to.

**Comment by barbushin** [comment]
See 70f748a7c36768dc120fd608de46423dbd9c057b
