### ISSUE TITLE
Error with Microsoft Exchange 2003

### ISSUE THREAD

**Issue by robincle** [barbushin/php-imap#82]
Hey, if i try to connect to a Microsoft Exchange 2003 IMAP Mailbox the connection crashes with the following error: "Specified character set not supported. (errflg=2)"

If i try another imap mailbox, it works correctly.  Maybe a charset check is needed?

**Comment by robincle** [comment]
Found some things via google for this topic: http://mailing.www.horde-bugs.narkive.com/Zt0UWCwd/tickets-10726-re-exchange-2003-imap-error-specified-character-set-not-supported

> Issue is that Exchange 2003 does not appear to support UTF-8 in SEARCH
queries (which is kind of ridiculous in this day and age...) RFC 3501
only requires compliant servers to handle US-ASCII.

**Comment by robincle** [comment]
Changed line #20 in Mailbox.php from
````php
	public function __construct($imapPath, $login, $password, $attachmentsDir = null, $serverEncoding = 'UTF-8') {
````

to this one

````php
	public function __construct($imapPath, $login, $password, $attachmentsDir = null, $serverEncoding = 'US-ASCII') {
````

and the connection works fine! I think a charset parameter besides the connection parameter would be a solution?

**Comment by barbushin** [comment]
Hey! You don't need to change __constructor code. You can just pass encoding when initialize `PhpImap\Mailbox` instance, like this `$mailbox = new PhpImap\Mailbox($imapPath, $login, $password, null, 'US-ASCII');`.
