### ISSUE TITLE
Use secondary interface with a different IP

### ISSUE THREAD

**Issue by skynet** [barbushin/php-imap#83]
I want to use a secondary interface with a different IP when making requests to the IMAP server. How do I accomplish that?

**Comment by barbushin** [comment]
I'm not sure that it's possible, but you can check http://php.net/imap. Good luck :)

**Comment by skynet** [comment]
With curl is as easy as setting up a flag: 
```
curl_setopt($curlh, CURLOPT_INTERFACE, "xxx.xxx.xxx.xxx");
```
The only remaining option is to bind php to a different interface.
