### ISSUE TITLE
Mails always seen

### ISSUE THREAD

**Issue by Funfare1337** [barbushin/php-imap#84]
Hi,

the function imap_fetchbody marks mails automatically as seen. This behavior could be changed with the additional options parameter FT_PEEK.
Can you please make the parameter configurable?

Thanks

**Comment by barbushin** [comment]
Hey! See https://github.com/barbushin/php-imap/commit/6c4e45e3cca06c3b1c689c672706b565a32e3942 

Could you please test if it works properly? Then I'll add it to release.
Thanks!

**Comment by barbushin** [comment]
Done https://github.com/barbushin/php-imap/releases/tag/2.0.2
