### ISSUE TITLE
get downloaded attachment directory

### ISSUE THREAD

**Issue by mechlod** [barbushin/php-imap#97]
Hi!
Sorry for my bad english...
How can i put to a variable the specified filepath?
With   "  var_dump($mail->getAttachments());  " i get like this: 
{"12553843001916375063":{"id":"12553843001916375063","name":"Munkaf\u00fczet1.xlsx","filePath":"\/home....

Thanks!
Miklós

**Comment by barbushin** [comment]
Hey. See $attachmentsDir argument in constructor https://github.com/barbushin/php-imap/blob/master/src/PhpImap/Mailbox.php#L20
